### ISSUE TITLE
Slider issues

### ISSUE THREAD

**Issue by miniskulljob** [trimox/angular-mdc-web#1037]
### What Angular MDC version are you using?
0.35.7

### What browser(s) is this bug affecting?
Chrome 67.0.3396.79

### What OS are you using?
Windows 10

### What are the steps to reproduce the bug?

* Insert the slider tag in a blank project.
* Insert the slider tag in a MdcDialog component.

### What is the expected behavior?

* The slider should be disabled when you use the `[disabled]` property.
* The slider should start at the given value in the `[value]` property when there's no `[min]` property.
* The slider line should be at the same level as the marker when the slider is inserted in an MdcDialog component.

### What is the actual behavior?

* The `[disabled]` property doesn't work at all.
* The `[value]` property doesn't work when there's no `[min]` property set.
* The slider line is ahead of the marker when you insert the slider in a MdcDialog component.

### Any other information you believe would be useful?
Dependencies used in the project:

```
"dependencies": {
    "@angular-mdc/web": "^0.35.7",
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.4",
    "@angular/router": "^6.0.4",
    "angularfire2": "^5.0.0-rc.10",
    "core-js": "^2.4.1",
    "firebase": "^5.0.4",
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.0.0-rc.0",
    "zone.js": "^0.8.19"
  },
```

**Comment by trimox** [comment]
Duplicated, working on a fix.

**Comment by trimox** [comment]
Closing.
