### ISSUE TITLE
MdcTabBar selectedTabChange event is called twice

### ISSUE THREAD

**Issue by miniskulljob** [trimox/angular-mdc-web#1039]
### What Angular MDC version are you using?
0.35.7

### What browser(s) is this bug affecting?
Chrome 67.0.3396.79

### What OS are you using?
Windows 10

### What are the steps to reproduce the bug?
Use the `selectedTabChange` property in a `mdc-tab-bar` element and bind it to a method in the _Component_.

### What is the expected behavior?
The method should be called once per tab change.

### What is the actual behavior?
The method is called twice.

### Any other information you believe would be useful?
```
"dependencies": {
    "@angular-mdc/web": "^0.35.7",
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.4",
    "@angular/router": "^6.0.4",
    "angularfire2": "^5.0.0-rc.10",
    "core-js": "^2.4.1",
    "firebase": "^5.0.4",
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.0.0-rc.0",
    "zone.js": "^0.8.19"
  },
```

**Comment by trimox** [comment]
Hoped I'd have this resolved for v0.36.2 today, moved to v0.36.3 (1-2 days)
