### ISSUE TITLE
mdc-text-field outline not drawn correctly if field initially hidden

### ISSUE THREAD

**Issue by luccascorrea** [trimox/angular-mdc-web#1040]
### What Angular MDC version are you using?
0.35.7

### What browser(s) is this bug affecting?
I am using Google Chrome.

### What OS are you using?
macOS

### What are the steps to reproduce the bug?
Add an mdc-text-field element but make it invisible at first ([hidden]="true"). Then, make it visible after clicking a button, for example. You will see that after the field is shown, the outline is drawn incorrectly:

<img width="224" alt="screen shot 2018-06-10 at 3 22 33 pm" src="https://user-images.githubusercontent.com/9159316/41204999-a214f170-6cc2-11e8-99b9-eaeb543142a8.png">

This only happens if the ngModel connected to the text field is not empty.

**Comment by trimox** [comment]
Duplicated. Working on a fix.

**Comment by trimox** [comment]
PR incoming. Really glad you reported this, as switching between `outline` and `box` variants was broken as well.

![outlined](https://user-images.githubusercontent.com/11887843/41324732-4b3ce0c4-6e84-11e8-9ab6-f2515d582762.gif)

**Comment by luccascorrea** [comment]
@trimox great job! Glad I could help a bit
