### ISSUE TITLE
Will it work with ionic 2 or above?

### ISSUE THREAD

**Issue by ansarikhurshid786** [trimox/angular-mdc-web#1041]
I am looking for material design for ionic 2. I found this is good one. someone is tried but replied it is not working with ionic 2. 

Can any one tell me is it support for ionic 2 or above?

Thanks in advance

**Comment by ansarikhurshid786** [comment]
I tried it but it is not working.

**Comment by ansarikhurshid786** [comment]
Exactly I don't know the problem. Style is not applying

**Comment by trimox** [comment]
Have a project I could pull and take a look?

**Comment by vially** [comment]
One of the issues seems to be that `angular-mdc-web` requires `@angular/router` which is not available in ionic projects. Is there any chance this dependency could be removed or at least be made into an optional dependency?

**Comment by trimox** [comment]
@vially Thanks for the info. Lemme investigate making that optional. Anything else you know of?

**Comment by trimox** [comment]
@vially Appreciate the info! 💎 

Hopefully Ionic's Angular 6 support is made available soon. I'm interested in hearing any issues from anyone who could test using Ionic 4 alpha with angular-mdc. We can certainly try and get ahead of the Ionic 4 release.

I'll create a separate issue for investigating making `@angular/router` optional.

**Comment by trimox** [comment]
Closing for now.
