### ISSUE TITLE
Building with buildOptimizer

### ISSUE THREAD

**Issue by janwol** [trimox/angular-mdc-web#1099]
Great work man, but there is an issue, when i'm trying to build with the build-optimizer option.

### What Angular MDC version are you using?
angular:
6.0.7
angular-mdc-web
0.36.3

### What OS are you using?
Windows 10

### What are the steps to reproduce the bug?
building with this configuration:
{
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": true,
              "buildOptimizer": **true**
}
### Any other information you believe would be useful?
Build output:
...
WARNING in ./node_modules/@angular-mdc/web/dialog/typings/index.ngfactory.js
15:473-480 "export 'ɵa10' (imported as 'i3') was not found in '@angular-mdc/web/overlay'

WARNING in ./src/app/app.module.ngfactory.js
74:3539-3547 "export 'ɵa10' (imported as 'i20') was not found in '@angular-mdc/web/overlay'

Browser:
TypeError: l._renderer.addClass is not a function
    at Object.addClass (vendor.767a79ee5466304a8152.js:1)
    at e.value (vendor.767a79ee5466304a8152.js:1)
    at t.setUnbounded (vendor.767a79ee5466304a8152.js:1)
    at t.attachTo (vendor.767a79ee5466304a8152.js:1)
    at new t (vendor.767a79ee5466304a8152.js:1)
    at ml (vendor.767a79ee5466304a8152.js:1)
    at dl (vendor.767a79ee5466304a8152.js:1)
    at ql (vendor.767a79ee5466304a8152.js:1)
    at ti (vendor.767a79ee5466304a8152.js:1)
    at Jl (vendor.767a79ee5466304a8152.js:1)

**Comment by trimox** [comment]
@janwol Much appreciated!

Couple things to try...
1. Remove folder `@angular-mdc` from node_modules, and reinstall.
2. or try upgrading to `@angular-mdc/web` v0.37.0

Let me know!

**Comment by janwol** [comment]
Thanks for the fast response!

The update works, but unfortunately not the optimised build process:

WARNING in ./node_modules/@angular-mdc/web/snackbar/typings/index.ngfactory.js
13:311-330 "export 'MdcPortalService' (imported as 'i2') was not found in '@angular-mdc/web/portal'

WARNING in ./node_modules/@angular-mdc/web/snackbar/typings/index.ngfactory.js
13:332-351 "export 'MdcPortalService' (imported as 'i2') was not found in '@angular-mdc/web/portal'

WARNING in ./node_modules/@angular-mdc/web/snackbar/typings/index.ngfactory.js
13:466-485 "export 'MdcPortalService' (imported as 'i2') was not found in '@angular-mdc/web/portal'

WARNING in ./node_modules/@angular-mdc/web/dialog/typings/index.ngfactory.js
14:423-442 "export 'MdcPortalService' (imported as 'i3') was not found in '@angular-mdc/web/portal'

WARNING in ./node_modules/@angular-mdc/web/dialog/typings/index.ngfactory.js
14:444-463 "export 'MdcPortalService' (imported as 'i3') was not found in '@angular-mdc/web/portal'

WARNING in ./node_modules/@angular-mdc/web/dialog/typings/index.ngfactory.js
14:572-591 "export 'MdcPortalService' (imported as 'i3') was not found in '@angular-mdc/web/portal'

WARNING in ./node_modules/@angular-mdc/web/dialog/typings/index.ngfactory.js
14:606-619 "export 'DIALOG_REF' (imported as 'i1') was not found in '@angular-mdc/web/dialog'

WARNING in ./node_modules/@angular-mdc/web/dialog/typings/index.ngfactory.js
14:876-889 "export 'DIALOG_REF' (imported as 'i1') was not found in '@angular-mdc/web/dialog'

WARNING in ./node_modules/@angular-mdc/web/dialog/typings/index.ngfactory.js
14:926-945 "export 'DIALOG_CONTAINER' (imported as 'i1') was not found in '@angular-mdc/web/dialog'

WARNING in ./node_modules/@angular-mdc/web/dialog/typings/index.ngfactory.js
14:988-1004 "export 'DIALOG_CONFIG' (imported as 'i1') was not found in '@angular-mdc/web/dialog'

WARNING in ./src/app/app.module.ngfactory.js
72:10238-10252 "export 'DIALOG_REF' (imported as 'i21') was not found in '@angular-mdc/web/dialog'

WARNING in ./src/app/app.module.ngfactory.js
72:10290-10310 "export 'DIALOG_CONTAINER' (imported as 'i21') was not found in '@angular-mdc/web/dialog'

WARNING in ./src/app/app.module.ngfactory.js
72:10354-10371 "export 'DIALOG_CONFIG' (imported as 'i21') was not found in '@angular-mdc/web/dialog'

WARNING in ./src/app/app.module.ngfactory.js
72:3441-3461 "export 'MdcPortalService' (imported as 'i20') was not found in '@angular-mdc/web/portal'

WARNING in ./src/app/app.module.ngfactory.js
72:3463-3483 "export 'MdcPortalService' (imported as 'i20') was not found in '@angular-mdc/web/portal'

WARNING in ./src/app/app.module.ngfactory.js
72:3594-3614 "export 'MdcPortalService' (imported as 'i20') was not found in '@angular-mdc/web/portal'

WARNING in ./src/app/app.module.ngfactory.js
72:3629-3643 "export 'DIALOG_REF' (imported as 'i21') was not found in '@angular-mdc/web/dialog'

WARNING in ./src/app/app.module.ngfactory.js
72:3718-3738 "export 'MdcPortalService' (imported as 'i20') was not found in '@angular-mdc/web/portal'

ERROR in ./node_modules/@angular-mdc/web/esm5/web.es5.js
Module not found: Error: Can't resolve '@angular-mdc/web/overlay' in '[...]\node_modules\@angular-mdc\web\esm5'
ERROR in ./node_modules/@angular-mdc/web/esm5/dialog.es5.js
Module not found: Error: Can't resolve '@angular-mdc/web/overlay' in '[...]\node_modules\@angular-mdc\web\esm5'

**Comment by trimox** [comment]
I noticed the last two errors logged state "Can't Resolve `@angular-mdc/web/overlay`"; which was removed in v0.37.0. 

Very very odd. The demo-app for our site uses `buildOptimizer` as well.
```
            {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": false,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
           }
```

It's almost like something is cached or "broken" in the node_modules folder. Can you remove the `node_modules` folder AND the `package-lock.json`. Re-run `npm i`, let's see..

**Comment by trimox** [comment]
@janwol Duplicated with internal project today, and removing `node_modules` folder and `package-lock.json`, than `npm i` fixed whatever caused it.

**Comment by trimox** [comment]
Closing. Let me know if ya need assistance.
