### ISSUE TITLE
 how can I help ?

### ISSUE THREAD

**Issue by hiepxanh** [trimox/angular-mdc-web#11]
this is my first time to contribute to a public repository, how can I help you ? where should i start from ? Can you let me try on something easy ?

**Comment by trimox** [comment]
Hey @hiepxanh, appreciate the offer of help! I'd encourage you to familiarize yourself with any presently available components and related code. If you'd like to start by testing components and filing issues for any bugs in the source code or a mistake in the documentation it'd be a huge help. 
I'll also compose Contribution guidelines for the community and have it posted sometime this weekend. 
Thanks again for your interest!
