### ISSUE TITLE
MdcDialog service: the dialog reference remains in the open dialogs collection after closing if there happens to be a parent dialog service

### ISSUE THREAD

**Issue by ibelenski** [trimox/angular-mdc-web#1110]
@angular-mdc/web version: 0.37.1

I end up with a situation where I can't open a dialog more than once because after it closes the first time around, the dialog reference remains in the `.openDialogs` collection.

As far as I can tell the culprit is the `._registerDialogRef()` method of the MdcDialog service: it pushes the dialogRef into `.openDialogs` but later tries to remove it from `._openDialogs` which is a different array if `._parentDialog` is defined.

```
private _registerDialogRef(dialogRef: MdcDialogRef<any>): void {
  this.openDialogs.push(dialogRef);

  const dialogCloseSub = dialogRef.afterClosed().subscribe(() => {
    const dialogIdx = this._openDialogs.indexOf(dialogRef);
    if (dialogIdx !== -1) { this._openDialogs.splice(dialogIdx, 1); }

    if (!this._openDialogs.length) {
      this.afterClosed.next();
      dialogCloseSub.unsubscribe();
    }
    this._portalService.dispose();
  });
}
```

**Comment by trimox** [comment]
@ibelenski Would you be able to pull https://github.com/trimox/angular-mdc-web/pull/1113, and give the fix a test run?

**Comment by ibelenski** [comment]
@trimox Works for me with #1113 applied, my workaround no longer finds the dialog reference in .openDialogs after closing.

But Dominic, we need to get a life...
