### ISSUE TITLE
Snackbar not showing properly from AJAX error handler

### ISSUE THREAD

**Issue by JPtenBerge** [trimox/angular-mdc-web#1120]
### What Angular MDC version are you using?
The latest, 0.37.0.

### What browser(s) is this bug affecting?
All that I can see. Chrome 67 and Edge 17.

### What OS are you using?
Windows 10.

### What are the steps to reproduce the bug?
[I've reproduced it in StackBlitz](https://stackblitz.com/edit/angular-mdc-snackbar-sjle7v).

I've created a component where I make an AJAX request in the `ngOnInit` and I've set it up that the server can't be reached, thus the request will fail. I also added a generic errorhandler using:

```ts
  providers: [
    { provide: ErrorHandler, useClass: AppErrorHandler },
  ],
```
Inside this errorhandler, I want to use the snackbar to alert the user that something has gone wrong. This leads to the strange result.

### What is the expected behavior?
The snackbar to appear at the bottom of the screen, as it should.

### What is the actual behavior?
The message and the dismiss action link are shown, but without the markup. They're shown inline on the page, not fixed at the bottom of the screen.

### Any other information you believe would be useful?
What surprised me is that it has to be an AJAX error that originated in the `ngOnInit`. I've tried to reproduce it with a simple method that prints a non-existent property like `console.log((this as any).property.does.not.exist);`. This results in an exception and the error handler gets triggered, but miraculously, the snackbar pops up as it should. I've only found this strange behavior to happen in the use case of a failing AJAX request in the `ngOnInit`.

Curious to what your findings are!

JP

**Comment by trimox** [comment]
@JPtenBerge Thanks for the StackBlitz! I've duplicated internally, and working on a fix for ya.

**Comment by JPtenBerge** [comment]
Nice! Thanks again.

**Comment by JPtenBerge** [comment]
Hate to be the bearer of bad news, but it doesn't seem fixed. [Here is the new reproduction on StackBlitz](https://stackblitz.com/edit/angular-mdc-snackbar-smxuqx). Something has definitely changed though, earlier the markup was gone but the text and the action link were visible on the page. Now both are completely invisible.

**Comment by trimox** [comment]
No bad news 😄 

I forked you're StackBlitz, https://stackblitz.com/edit/angular-mdc-snackbar-6kelsy

Inside `app.handler.ts`
https://stackblitz.com/edit/angular-mdc-snackbar-6kelsy?embed=1&file=app/app.handler.ts

You need to execute `snackbar.show()` within the Angular zone..

**Comment by JPtenBerge** [comment]
Aaahh. Because an errorhandler runs outside of a zone. First time I'm running into something like that. Praise to you and big thanks again!
