### ISSUE TITLE
Add a way to disable selecting mdc-list-items but keep hover/ripples

### ISSUE THREAD

**Issue by draoncc** [trimox/angular-mdc-web#1138]
As of version 0.36.3, it is not possible to disable the "selection" effect on mdc-list-items without also disabling the ripples and coloration on hover using [interactive]. My proposal is to separate [interactive] from the selection effect, as the selection effect is not part of a regular MDC list to begin with, and control whether a list is selectable via another input that by default is false.

**Comment by trimox** [comment]
@draoncc Thanks for the proposal, and I agree. Working on a PR for this now.

**Comment by trimox** [comment]
PR #1153 results

![list](https://user-images.githubusercontent.com/11887843/43194816-4f959562-8fd1-11e8-9e84-11bf5928e243.gif)
