### ISSUE TITLE
Add a way to set a list item as activated

### ISSUE THREAD

**Issue by draoncc** [trimox/angular-mdc-web#1139]
As per the appendix to the [CSS Classes list of the MDC List documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-list#css-classes), list items can be either in selected or activated state. Currently, list items of angular-mdc-web are missing a way to be set to an activated state via an input. Instead, the class must be set through other means.

**Comment by trimox** [comment]
@draoncc Hey, revisiting issue after completing recent improvements upstream for MDC List. From what I gathered, `mdc-list-item--selected` and `mdc-list-item--activated` share the same styling properties. 

```sass
// "Selected" is ephemeral and likely to change soon. E.g., selecting one or more photos to share in Google Photos.
// "Activated" is more permanent. E.g., the currently highlighted navigation destination in a drawer.
.mdc-list-item--selected,
.mdc-list-item--activated {
  @include mdc-list-item-primary-text-ink-color(primary);
  @include mdc-list-item-graphic-ink-color(primary);
}
```

Would you by chance have an example I could compare to our current implementation for v0.38.0 ?

**Comment by trimox** [comment]
Closing. Fixed upstream in upcoming build.

https://github.com/material-components/material-components-web/pull/3388
