### ISSUE TITLE
ngValue does not work with mdc-select

### ISSUE THREAD

**Issue by daniloarcidiacono** [trimox/angular-mdc-web#1146]
### What Angular MDC version are you using?
The latest available at the time, 0.37.2.

### What browser(s) is this bug affecting?
I've tested it only on Chrome, but I think this issue does not depend from the browser.

### What OS are you using?
Ubuntu 16.04 LTS but, as for the browser, this should be irrelevant.

### What are the steps to reproduce the bug?
I've reproduced the bug using [Stackblitz](https://stackblitz.com/edit/angular-mdc-select-ngvalue-bug).

### What is the expected behavior?
The form data should be populated with the object passed to `ngValue`.

### What is the actual behavior?
The form data is populated with the `<option>` label instead.

### Any other information you believe would be useful?
It seems that when `mdc-select` is used, the [SelectControlValueAccessor](https://angular.io/api/forms/SelectControlValueAccessor) is not applied to it. Maybe because the `formControlName` attribute is not applied to the internal `select` tag?

**Comment by trimox** [comment]
Thanks for reporting, and the StackBlitz. We'll need to implement `compareWith(o1: any, o2: any) => boolean` property for `mdc-select`.
