### ISSUE TITLE
custom font icon is not working in app bar

### ISSUE THREAD

**Issue by mohammadrafigh** [trimox/angular-mdc-web#1147]
### What Angular MDC version are you using?
0.37.2
### What browser(s) is this bug affecting?
All
### What OS are you using?
Ubuntu
### What are the steps to reproduce the bug?
```
<mdc-app-bar>
  <mdc-app-bar-row>
    <mdc-app-bar-section align="start">
      <mdc-icon mdcAppBarNavIcon fontSet="fa" fontIcon="fa-camera"></mdc-icon>
    </mdc-app-bar-section>
  </mdc-app-bar-row>
</mdc-app-bar>
```
### What is the expected behavior?

all font icons should be rendered correctly.
### What is the actual behavior?

only official material design icons work.
### Any other information you believe would be useful?

the problem is fontawesome and many other font icons try to set content in ":before" but when mdc-icon is used with mdcAppBarNavIcon or mdcAppBarActionItem, these directives overwrite :before styles.

**Comment by trimox** [comment]
@mohammadrafigh Thanks for reporting. I'm in the early stages of improving our support for Font Awesome and other icon sets. Related discussion on PR #1001.

For now, here's a workaround..
```html
<mdc-icon mdcAppBarNavIcon fontSet="fa"><i class="fa fa-camera"></i></mdc-icon>
```

**Comment by mohammadrafigh** [comment]
Thanks for answering with patience

**Comment by trimox** [comment]
Sorry for the delay..PR incoming

**Comment by mohammadrafigh** [comment]
sorry but the issue still exists with custom font icon.
