### ISSUE TITLE
unable to import MdcDialog  

### ISSUE THREAD

**Issue by iamgurdip** [trimox/angular-mdc-web#1148]
### What Angular MDC version are you using?
0.37.2

unable to import MdcDialog in Angular, typescript does not find it in the @angular-mdc/web
import { MdcDialog , MdcSwitchChange } from '@angular-mdc/web';

**Comment by trimox** [comment]
@iamgurdip Hey, what's your project Angular version? 

If this is a recent upgrade..
Remove the `node_modules` folder AND `package-lock.json`. 
Re-run `npm i`

**Comment by iamgurdip** [comment]
Got it working. Removed `node_modules` folder and reinstalled. Also had to re-start VS2017 IDE. This seems to have fixed it. 

Thank you so much for the quick response, and keep up the good work, really appreciate it.
