### ISSUE TITLE
mdc-tab-bar-indicator gets out of sync with active tab if set programmatically

### ISSUE THREAD

**Issue by mjswensen** [trimox/angular-mdc-web#1149]
Thanks for your work on this package!

### What Angular MDC version are you using?

`0.37.2`

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

MacOS

### What are the steps to reproduce the bug?

Place the following in the template:

```html
<mdc-tab-bar>
  <mdc-tab [active]="test">Active First</mdc-tab>
  <mdc-tab [active]="!test">Active Later</mdc-tab>
</mdc-tab-bar>
```

And the following in `ngOnInit`:

```js
this.test = true;
setTimeout(() => {
  this.test = false;
}, 1000);
```

### What is the expected behavior?

When the active tab is updated (after 1,000 ms), both the indicator and the text style should reflect the new active tab.

It should look like this:

![image](https://user-images.githubusercontent.com/1591879/43152104-d9bb4c2a-8f2a-11e8-885c-fc65e5eca8f9.png)

### What is the actual behavior?

Only the text style changes. The indicator remains on the old tab.

It looks like this:

![image](https://user-images.githubusercontent.com/1591879/43152088-cec2c410-8f2a-11e8-9ec7-5d99bdc0d323.png)

### Any other information you believe would be useful?

Unfortunately the following workaround also has no effect:

```html
<mdc-tab-bar [selectedIndex]="test ? 0 : 1">
  <mdc-tab>Active First</mdc-tab>
  <mdc-tab>Active Later</mdc-tab>
</mdc-tab-bar>
```

**Comment by mjswensen** [comment]
One more note: the `MdcTabChangeEvent` does not emit with the `active` state change either.

**Comment by trimox** [comment]
@mjswensen Thanks for reporting. Duplicated, working on a PR.

**Comment by mjswensen** [comment]
Thank you, @trimox !

**Comment by trimox** [comment]
@mjswensen The original mdc-tabs were recently deprecated, and replaced with new `mdc-tab / mdc-tab-bar / mdc-tab-scroller / mdc-tab-indicator` package(s). 

New documentation: https://trimox.github.io/angular-mdc-web/#/tabs-demo

Care to try em out and see if this resolves?

**Comment by mjswensen** [comment]
Thanks so much for the additional information, @trimox ! Our team has actually decided to move off of MDC for the time being. But thank you again for the suggestion.
