### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#1158]
- Allow user to expand and collapse API documentation segments.
- Show code snippets using `highlightjs` for syntax highlighting.

Open to suggestions from community? What would help you?

**Comment by daniloarcidiacono** [comment]
Hi,
I think it would be very useful to have code snippets (HTML and TypeScript) directly into the documentation, without having to open StackBlitz.
 
I'm skeptical about the usefulness of embedding StackBlitz into the documentation instead, because as far as I've seen it's very heavy (the dev server can easily take two minutes to start).

**Comment by trimox** [comment]
@daniloarcidiacono Completely agree. I've been researching since posting this issue, and I'm also not sold on embedding StackBlitz examples. 

Using `highlightjs` or some variant should get us exactly what we're looking for..

Thanks for the feedback!

**Comment by trimox** [comment]
Tackling improved documentation next..

**Comment by trimox** [comment]
This is coming along nicely. Implemented lazy loaded modules, abstracted documentation generation into shared component, and making use of `mdc-tab` for separating api and examples.

**Comment by trimox** [comment]
Sample of the redesign..

![sample](https://user-images.githubusercontent.com/11887843/50574707-d976d580-0dbb-11e9-97bc-f2c16c10ae54.gif)

**Comment by trimox** [comment]
@daniloarcidiacono Thanks for the suggestion! 💎 
Implemented tabs to display HTML/Sass/TS example code when available. I'll post another sample from dialog, since it's probably the most complex.

![sample](https://user-images.githubusercontent.com/11887843/50576948-f4147300-0dea-11e9-83d5-9bedc3298f01.gif)

**Comment by trimox** [comment]
@daniloarcidiacono Here's the largest of the bunch, dialog..

![sample](https://user-images.githubusercontent.com/11887843/50680274-17027b00-0fd5-11e9-8173-06c2e2db64e4.gif)

**Comment by daniloarcidiacono** [comment]
Nice, the documentation now looks much more quick to consult!

**Comment by trimox** [comment]
Thanks, working to get this deployed today.

**Comment by trimox** [comment]
Planning to phase out individual StackBlitz examples. Instead a single StackBlitz starter project for playground, and duplicating issues.
