### ISSUE TITLE
Broken outline on pre-filled text-field in ionic 4 with angular 6

### ISSUE THREAD

**Issue by SplicePHP** [trimox/angular-mdc-web#1159]
### What Angular MDC version are you using?
0.37.3
### What browser(s) is this bug affecting?
Chrome
### What OS are you using?
( Linux mint 19, Cinnamon ) Ubuntu 18.04
### What are the steps to reproduce the bug?
Create Ionic 4 project with angular 6.
( Disabled all ionic css )
Create TextField with outlined enabled.
Outline of text is broken if prefilled.

### What is the expected behavior?
Outline to be working with prefilled text

### What is the actual behavior?
Broken outline

### Any other information you believe would be useful?
I believe you are aware of the issue.
I get the same result as in issue: #1040
Will use non outlined version for now till this is resolved.

**Comment by trimox** [comment]
@SplicePHP Thanks for reporting. Duplicated, working on a PR.

**Comment by trimox** [comment]
@SplicePHP Is this still a problem with the v0.38.1 release?
