### ISSUE TITLE
Attempting to close a dialog and display a snackbar at the same time fails.

### ISSUE THREAD

**Issue by luccascorrea** [trimox/angular-mdc-web#1173]
### What Angular MDC version are you using?
0.37.3

### What browser(s) is this bug affecting?
I am using Chrome but it could be affecting other browsers as well.

### What OS are you using?
OSX 10.12.6

### What are the steps to reproduce the bug?
You can see it on [StackBlitz](https://angular-mdc-snackbar-dialog.stackblitz.io).

### What is the expected behavior?
If a snackbar is shown at the same time that a dialog is to be closed, the snackbar should be shown and the dialog should be closed.

### What is the actual behavior?
The first time you click the button to close the dialog and show the snackbar, nothing happens. If you click the button again, the snackbar is shown and the dialog is not closed. 

### Any other information you believe would be useful?
I solved this in my own project by wrapping the call to display the snackbar in a `setTimeout` call like so:

    setTimeout(() => {
        this.snackbar.show("This is a snackbar");
    });

**Comment by trimox** [comment]
Thanks for the StackBlitz. I've been tied up with the upcoming v0.38.0 release but will take a look.

**Comment by trimox** [comment]
Adding the StackBlitz edit url
https://stackblitz.com/edit/angular-mdc-snackbar-dialog

**Comment by trimox** [comment]
While adding Snackbar parent support for #1144, I encountered this issue as well. 
reference #1144 as related.

**Comment by trimox** [comment]
Fixed in upcoming v0.40.
