### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by gedw99** [trimox/angular-mdc-web#1201]
Do you support RTL like  MDC demos do ?

Here is what i mean:
Code: https://github.com/material-components/material-components-web
Demo: https://material-components-web.appspot.com/

**Comment by gedw99** [comment]
hey @trimox i was searching for an example in your code. 

Maybe you could add one. Its difficult to knwo how the code differs from Googles standard MDC without seeing an example in your code i feel. Others might also want it.

And while i am at it what about i18N etc ? no examples of that either.

**Comment by trimox** [comment]
@gedw99 For the most part, using RTL is as easy as the demos for `material-components-web`

```html
<mdc-form-field dir="RTL">
  <mdc-switch></mdc-switch>
  <label>off/on</label>
</mdc-form-field>
```
Example from https://stackblitz.com/edit/angular-mdc-switch?file=app%2Fapp.component.html

i18n support is not yet documented for Angular MDC. Composing examples/documentation is definitely something we could look to incorporate using Angular i18n docs, https://angular.io/guide/i18n

**Comment by gedw99** [comment]
@trimox 

Ok the RTL looks easy. 

Shall i close this ?

**Comment by trimox** [comment]
Yep, sgtm. Thanks!
