### ISSUE TITLE
Prominent app bar doesn't appear again after hided

### ISSUE THREAD

**Issue by imdo3** [trimox/angular-mdc-web#1226]
### What Angular MDC version are you using?
0.38.1

### What browser(s) is this bug affecting?
Chrome

### What OS are you using?
Window

### What are the steps to reproduce the bug?
1. Add 'prominent' property to this line instead of 'fixed' and 'fixedAdjustElement'.
https://github.com/trimox/angular-mdc-web/blob/ea09759d530642565a5f524007c37c66b8de0a05/demos/app-layout/app-layout.html#L1
1. Open my app
1. Scroll down
1. App bar hided immediately
1. Scroll up

### What is the expected behavior?
App bar appear.

### What is the actual behavior?
App bar doesn't appear.

### Any other information you believe would be useful?
topAppBarHeight value is 0

# Desc
root cause is https://github.com/trimox/angular-mdc-web/blob/ea09759d530642565a5f524007c37c66b8de0a05/packages/app-bar/app-bar.ts#L67 is called before view initialization. This sets _isFoundationInit to True and it is not called in afterviewinit hook at https://github.com/trimox/angular-mdc-web/blob/ea09759d530642565a5f524007c37c66b8de0a05/packages/app-bar/app-bar.ts#L188

**Comment by trimox** [comment]
@imdo3 Thanks for the assistance! 🏆  PR incoming..
