### ISSUE TITLE
mdc-text-field: box property not working

### ISSUE THREAD

**Issue by daniloarcidiacono** [trimox/angular-mdc-web#1227]
### What Angular MDC version are you using?
0.38.1
### What browser(s) is this bug affecting?
I've tested it only on Chrome, but I think allbrowsers are affected.
### What OS are you using?
Windows 10 at the moment of opening this issue.
### What are the steps to reproduce the bug?
I've reproduced the bug with [StackBlitz](https://stackblitz.com/edit/angular-mdc-button-box-bug), as usual.
### What is the expected behavior?
Setting [box]="false" should remove the boxed style.
### What is the actual behavior?
The [box]="false" attribute is ignored.
### Any other information you believe would be useful?
Setting box.false through TypeScript works.

**Comment by trimox** [comment]
@daniloarcidiacono Hey man, unfortunately the `non-box` variant of text-field is deprecated and scheduled for removal upstream - https://github.com/material-components/material-components-web/pull/2859

This line was added with the intent to have developers start using the new variants `box` and `outline`. As you found it can be bypassed for the time being, at least until upstream PR removes it totally.
https://github.com/trimox/angular-mdc-web/blob/ea09759d530642565a5f524007c37c66b8de0a05/packages/textfield/text-field.ts#L320

reference Angular MDC issue: https://github.com/trimox/angular-mdc-web/issues/1049

Hope this helps!

**Comment by daniloarcidiacono** [comment]
Oops, I didn't notice that. Thank you
