### ISSUE TITLE
Theme import in getting started guide

### ISSUE THREAD

**Issue by rapropos** [trimox/angular-mdc-web#129]
[The "getting started" guide](https://github.com/trimox/angular-mdc-web/blob/master/docs/getting-started.md#step3) says in its "theme" section that the following import should work for angular-cli projects:

```
@import "material-components-web/material-components-web";
```

It didn't, for me (angular-cli 1.3.2). What did was:

```
@import "~material-components-web/dist/material-components-web.css";
```

I don't know if this is something peculiar to my project or environment, or a problem with the docs.

**Comment by trimox** [comment]
@rapropos Check out closed issue #87

**Comment by rapropos** [comment]
I added the `stylePreprocessorOptions` to my angular-cli.json, but it had no effect. Still get the following error:

```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./src/styles.css
Module not found: Error: Can't resolve './material-components-web/material-components-web' in `[path-to-project]/src'
```

**Comment by trimox** [comment]
Sorry to hear that didn't help. One goal with our upcoming Theme component is to make the need to import the MDC theme package optional. I don't think a day goes by we don't see a developer struggling with importing the MDC scss library.

**Comment by trimox** [comment]
@rapropos any luck? If not, please let me know. I'd like to compose an Angular CLI-MDC guide this week.

**Comment by rapropos** [comment]
I just went back to the workaround in my OP for now.

**Comment by trimox** [comment]
@rapropos See duplicate #157. Should have it figured out by Wednesday.

**Comment by trimox** [comment]
@rapropos Hope this helps!
Angular CLI - Step by step guide
https://github.com/trimox/angular-mdc-web/blob/master/docs/guide-angular-cli.md
