### ISSUE TITLE
Can't see the selected item on reducing the height of the mdc-select tag

### ISSUE THREAD

**Issue by gupta82anish** [trimox/angular-mdc-web#1310]
### What Angular MDC version are you using?
0.39.2
### What browser(s) is this bug affecting?
I'm using Google Chrome, the latest version.
### What OS are you using?
Ubuntu 18.04
### What are the steps to reproduce the bug?
Just reduce the height of the mdc-select tag in scss file
### What is the expected behavior?
The selected item text should be visible
### What is the actual behavior?
The selected item is not visible

**Comment by trimox** [comment]
@gupta82anish Thanks for reporting. This may be an issue upstream, but I'll take a look.

**Comment by trimox** [comment]
Closing. Upstream issue that'll be resolved in upcoming density specs.
