### ISSUE TITLE
MdcTabBar makes it a bit tricky to set the initial active tab using custom logic and .activateTab()

### ISSUE THREAD

**Issue by ibelenski** [trimox/angular-mdc-web#1311]
@angular-mdc/web v0.39.1

In a nutshell, after updating an array that controls the rendering of the tabs by the template, I use `setTimeout()` to execute some logic that calls `.activateTab()`.

The current implementation of `MdcTabBar.prototype._initializeSelection()` ends up overriding my tab selection by activating the first tab. As a workaround, I'm executing my tab selection logic after a second timeout, but it's a bit ugly as the tab indicator ends up visibly sliding from the first tab to the one I select (if different).

It seems to me it would be better if `_initializeSelection()` didn't separate the check for an active tab and the activation of tab 0 with a timeout, e.g.

```
private _initializeSelection(): void {
  // Defer setting the value in order to avoid the "Expression
  // has changed after it was checked" errors from Angular.
  setTimeout(() => {
    if (this.tabs.find((_) => _.active)) {
      this.scrollIntoView(this.getActiveTabIndex());
    } else {
      this.activateTab(0);
    }
  });
}
```

Or, as a diff:

```
diff --git a/packages/tab-bar/tab-bar.ts b/packages/tab-bar/tab-bar.ts
index df757bc3..b10dcba7 100644
--- a/packages/tab-bar/tab-bar.ts
+++ b/packages/tab-bar/tab-bar.ts
@@ -197,13 +197,11 @@ export class MdcTabBar implements AfterContentInit, OnDestroy {
   private _initializeSelection(): void {
     // Defer setting the value in order to avoid the "Expression
     // has changed after it was checked" errors from Angular.
-    Promise.resolve().then(() => {
+    setTimeout(() => {
       if (this.tabs.find((_) => _.active)) {
         this.scrollIntoView(this.getActiveTabIndex());
       } else {
-        setTimeout(() => {
-          this.activateTab(0);
-        });
+        this.activateTab(0);
       }
     });
   }
```

Best regards.

**Comment by trimox** [comment]
@ibelenski Any chance you'd be able to test with PR #1314 ? It seems better from my side, but I'd like a second opinion..

**Comment by ibelenski** [comment]
@trimox, thanks for looking into this.

#1314 works for me in the sense that I can eliminate the extra defer. I still get the visible slide of the tab indicator from tab 0. I guess I can live with that.

I can't figure out when to activate a tab so that it happens before you check if there's an active tab and default to 0. I'm having some weird troubles using `AfterContentChecked` and `AfterViewChecked`. I wish I could do it through a template input attribute. 

I don't want to bore you with details of my use case but in a nutshell I have a shell component that may render different sets of tabs throughout its lifetime based on a tab set model and sensitive to the current route.

**Comment by trimox** [comment]
Thoughts on not setting `activateTab(0)` within the framework? What if we left that to the developer to decide.

**Comment by trimox** [comment]
@ibelenski Thanks again for testing and the info. I've updated #1314  with some additional refactoring.

**Comment by trimox** [comment]
Got it 😄 
Pushing new commit

**Comment by ibelenski** [comment]
Great!

Two comments:

- Shouldn't `this.activateTab(this.selectedIndex ? this.selectedIndex : 0);` be done in response to the `tabs.changes` observable firing?
- Consider changing the name of the input attribute to use the adjective 'active' rather than 'selected' to be consistent with the rest of the interface (e.g. `getActiveTabIndex()`).

**Comment by trimox** [comment]
@ibelenski Give latest commit a try. Think we got it nailed down

Renamed to `activeTabIndex` 👍

**Comment by trimox** [comment]
@ibelenski Meant to say, great suggestion to move activateTab into observable!

**Comment by trimox** [comment]
Added unit tests, and fixed a couple other items.

**Comment by ibelenski** [comment]
@trimox , thanks again, good work, works for me quite nicely.
