### ISSUE TITLE
Add MDC circular progress

### ISSUE THREAD

**Issue by JeroenRoodIHS** [trimox/angular-mdc-web#1321]
There are two progress indicators documented under "Progress Indicators" > "Usage" > "Types":  [https://material.io/design/components/progress-indicators.html#usage](https://material.io/design/components/progress-indicators.html#usage)

The circular progress indicator: [https://material.io/design/components/progress-indicators.html#circular-progress-indicators](https://material.io/design/components/progress-indicators.html#circular-progress-indicators)

**Comment by trimox** [comment]
@JeroenRoodIHS Thanks for filing. Looks like there is an existing request upstream `material-components-web`. Once it's made available, we'll incorporate here.
https://github.com/material-components/material-components-web/issues/30

**Comment by JeroenRoodIHS** [comment]
My bad, thank you for pointing it out!
