### ISSUE TITLE
MDC TEXTFIELD setValid() method bug

### ISSUE THREAD

**Issue by Flashunt** [trimox/angular-mdc-web#1322]
### What Angular MDC version are you using?
0.39.1
### What browser(s) is this bug affecting?
All
### What OS are you using?
Windows 10
### What are the steps to reproduce the bug?
https://stackblitz.com/edit/angular-mdc-text-field-vgcjh5?file=app/app.component.ts
I create a custom validation for text field onKeyUp event with setValid() method, and it isn't working.
### What is the expected behavior?
If i set the valid property false, with the method it remaining false.
### What is the actual behavior?
I call setValid() method with false parameter and it isn't working.
### Any other information you believe would be useful?
https://stackblitz.com/edit/angular-mdc-text-field-vgcjh5?file=app/app.component.ts

**Comment by trimox** [comment]
@Flashunt Thanks for reporting. I'm re-working `mdc-text-field` validity handling in #1320, I'll be sure this is resolved.

**Comment by trimox** [comment]
@Flashunt Quick workaround until PR is merged.

```ts
input.nativeValidation = false;
input.setValid(false);
```
