### ISSUE TITLE
dialog and noImplicitAny

### ISSUE THREAD

**Issue by rapropos** [trimox/angular-mdc-web#133]
Adding the `noImplicitAny` compiler option for TypeScript causes the dialog component to break:

```
typescript: node_modules/@angular-mdc/web/dialog/dialog.component.d.ts, line: 3 
            Could not find a declaration file for module 'focus-trap'. 
            '[path-to-project]/node_modules/focus-trap/index.js' implicitly has an 'any' type. Try `npm 
            install @types/focus-trap` if it exists or add a new declaration (.d.ts) file containing `declare module 
            'focus-trap';` 
```

The issue is discussed [here](https://github.com/Microsoft/TypeScript/issues/15031) and [here](https://github.com/Microsoft/TypeScript/issues/14379), so if anybody else runs across this problem, add the following to some global .d.ts file:

```
declare module 'focus-trap';
```

It would be great if we could fix this within angular-mdc itself, but nothing I have tried so far has been successful at doing that. I may also file something against focus-trap in case it can be done upstream there.

**Comment by trimox** [comment]
Working on resolving. Thank you for reporting it!

**Comment by trimox** [comment]
@rapropos merged! :)
