### ISSUE TITLE
Investigate options for not activating initial tab

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#1342]
Hey @ibelenski Going to pick your brain again. With the current version, we default `activeTabIndex` to `0`. Thought/opinions if we check to see if `activeTabIndex` is  `-1`, and if so do not activate an initial tab? I'm hoping to help others avoid "racing" the indicator slide from another tab.

For an example of what I mean, see **Tabs (using active-tab-router)**
https://stackblitz.com/edit/angular-mdc-tabs?file=app%2Fapp.component.html

**Comment by ibelenski** [comment]
@trimox,

I think if the tab bar

- always honors the `activeTabIndex` input attribute
- defaults it to `0` if not specified
- accepts an invalid value (`< 0`  or `>= tabs.length`) to mean 'no active tab'

it'll handle most, if not all, use cases.

An app that uses the tab bar to trigger route navigation will always want the active tab to reflect the current route, so it'll always have to specify an `activeTabIndex` value, and since people can type anything in the address bar, 'no active tab' should probably be a valid option.

If 'default to the first tab' is what makes sense for the use case, you just leave `activeTabIndex` unspecified, i.e. `0`.

**Comment by ibelenski** [comment]
In my current project, the tab bar serves to provide a 'second level' or 'sub-' route navigation in certain activity components (the 'top' or 'main' navigation is triggered from a list of navigation links in a drawer). The tab bar is backed by a simple array of tab model objects with a `label` and a `url` attributes.

Currently I simply handle the tab `click` events and call `Router.navigateByUrl()`  myself to trigger the navigation; I also subscribe to the router `NavigationEnd` events to update the active tab; my routes are very basic so I can match the current route to a tab like this:

```
const url = this.router.routerState.snapshot.url;
const tabIndexToActivate = this.tabSet.tabs.findIndex(tab => url.startsWith(tab.url));
```

What I'd love to be able to do is to specify `[routerLink]="..."` attributes on my tabs and something like `[routeActivation]="true"` on the tab bar, with some sort of control over the route-to-tab matching.

I seem to recall something like this in an earlier incarnation of the tab bar although I never got to try it.

**Comment by trimox** [comment]
@ibelenski Thank you for your time and suggestions! 💎 Much appreciated.

> always honors the activeTabIndex input attribute
> defaults it to 0 if not specified
> accepts an invalid value (< 0 or >= tabs.length) to mean 'no active tab'
> it'll handle most, if not all, use cases.

I'm working on incorporating this logic now. Let ya know.

**Comment by trimox** [comment]
@ibelenski Starting to push PR's. Internal testing looked good and caught a faulty listener.

Tab Scroller required a filter, and be run outside angular..
https://github.com/trimox/angular-mdc-web/pull/1346/files

**Comment by trimox** [comment]
@ibelenski Have you seen the directive I have on StackBlitz? It's purpose is to listen for route changes, and re-activate a tab after browser refresh. 

Once the next Angular MDC update is published, it should be much easier to integrate using `activeTabIndex` prop.
https://stackblitz.com/edit/angular-mdc-tabs?file=app%2Factive-tab-router.directive.ts

**Comment by ibelenski** [comment]
Thanks, @trimox, I saw it, haven't had a chance to try it.
