### ISSUE TITLE
cannot enable fullwidth and outlined directives simultaneously

### ISSUE THREAD

**Issue by cequella** [trimox/angular-mdc-web#1382]
### What Angular MDC version are you using?
"@angular-mdc/web": "^0.39.3"

### What browser(s) is this bug affecting?
only tested at chrome

### What OS are you using?
Windows 10

### What are the steps to reproduce the bug?
Only created a html component with fullwidth and outlined directives
<mdc-text-field #demofullwidth label="Subject" fullwidth outlined></mdc-text-field>

### What is the expected behavior?
A full width singleline outlined editable text box

### What is the actual behavior?
A full width singleline outlined NON-EDITABLE text box

**Comment by ajosecueto** [comment]
i have the same problem, and alson when i change the width value for a textfield my body width and height changes. i dont know why...

**Comment by trimox** [comment]
Hey @cequella and @ajosecueto, there's an recently opened issue upstream with `material-components-web`. Soon as the mixin is made available, we can incorporate here.

**Comment by ajosecueto** [comment]
> Hey @cequella and @ajosecueto, there's an recently opened issue upstream with `material-components-web`. Soon as the mixin is made available, we can incorporate here.

So, for now i have a simple solution, work on a fixed layout solves my problem when i want to change text field width. Really you have been doing a good work, congratulations. Thanks for develop this library.

**Comment by trimox** [comment]
I meant to update this thread. Please take a look at `mdc-form-field` feature discussed here
https://github.com/trimox/angular-mdc-web/issues/1518#issuecomment-435520283
