### ISSUE TITLE
disabled tabs again

### ISSUE THREAD

**Issue by rapropos** [trimox/angular-mdc-web#1392]
### What Angular MDC version are you using?
0.38+

App code dependent on the ability to disable tabs that was graciously provided in [#147](https://github.com/trimox/angular-mdc-web/issues/147) now breaks in 0.38+ as the `disabled` attribute is not available on the new tab bar implementation. Can this feature please be restored somehow?

**Comment by trimox** [comment]
Can do. Thanks for reminding me.

**Comment by trimox** [comment]
PR incoming
![image](https://user-images.githubusercontent.com/11887843/46322831-17940b80-c5b9-11e8-8b8e-672dcd3e4308.png)

**Comment by trimox** [comment]
Will be releasing v0.40.1 today.

**Comment by trimox** [comment]
Just fyi, I may need to submit another PR for disabling navigation via keyboard.

**Comment by rapropos** [comment]
Thank you so much.
