### ISSUE TITLE
Autocomplete on input text fields

### ISSUE THREAD

**Issue by jonbesga** [trimox/angular-mdc-web#1393]
Hi!

Is there any way to put an attribute like "autocomplete" directly in the input element of `mdc-text-field`?

The autocomplete attribute is very useful for autofill forms

More about it: https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands

**Comment by trimox** [comment]
Sure can. Pushed in PR https://github.com/trimox/angular-mdc-web/pull/1396
