### ISSUE TITLE
Mdc Dialog - data sharing

### ISSUE THREAD

**Issue by Flashunt** [trimox/angular-mdc-web#1397]
### What Angular MDC version are you using?
0.40.0
### What browser(s) is this bug affecting?
Chrome
### What OS are you using?
Windows 10

### BUG
When the dialog is an entry component, doesn't exists data property of dialogRef.
![image](https://user-images.githubusercontent.com/43272066/46340498-37b9de00-c63e-11e8-8875-4286466e8a15.png)

### stackblitz link
https://stackblitz.com/edit/angular-mdc-dialog-mqhsby?file=app%2Fapp.component.html

**Comment by trimox** [comment]
Hey @Flashunt, I've forked the StackBlitz and provided an updated example for ya with two methods for sharing data. Looks like the documentation is outdated for sharing data. I'll update that

https://stackblitz.com/edit/angular-mdc-dialog-fktt3x?file=app%2Fapp.component.ts

**Comment by Flashunt** [comment]
Thanks.

**Comment by trimox** [comment]
Docs updated. Closing.
