### ISSUE TITLE
Dialog. Imperative Usage (via service)

### ISSUE THREAD

**Issue by AKlaus** [trimox/angular-mdc-web#141]
Feature request.

Other Angular wrappers for UI frameworks provide imperative usage of dialogs - create your dialogs from your TypeScript code. 
E.g.:
* [MdDialog](https://material.angular.io/components/dialog/overview) in [@angular/material](https://github.com/angular/material2)
* [MdlDialogService](https://github.com/mseemann/angular2-mdl/wiki/How-to-use-the-MdlDialogService) in [angular2-mdl](https://github.com/mseemann/angular2-mdl)
* [NgbModal](https://long2know.com/2017/01/angular2-dialogservice-exploring-bootstrap-part-2/) in [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap)

Would it be possible to have a such feature in _angular-mdc-web_?

A similar thing would be useful for the `SnackbarComponent ` also.

P.S. It's not a blocker, as I managed to wrap it up into a service with using [this approach](https://stackoverflow.com/a/40788926/968003).

**Comment by trimox** [comment]
Really good feature request. Dynamically instantiating Dialog and Snackbar through a service is definitely doable and something we should offer.

**Comment by trimox** [comment]
Began design on a Snackbar service, should have a PR soon.

**Comment by trimox** [comment]
Snackbar released as service. I'll rearchitect Dialog this week.

**Comment by trimox** [comment]
PR incoming 😄

**Comment by trimox** [comment]
Closing. PR merged.
