### ISSUE TITLE
Badges feature request

### ISSUE THREAD

**Issue by studnickea19** [trimox/angular-mdc-web#1426]
### What Angular MDC version are you using?
0.40

**Comment by trimox** [comment]
Sorry, I've not found a mention for a `badge` component. You may want to ask on the `material-components-web` , and see if it's been discussed internally.

Also, feel free to track the MDC project plan on their public tracker, https://www.pivotaltracker.com/n/projects/1664011

**Comment by trimox** [comment]
Closing. Issue created upstream. Will monitor for activity.
