### ISSUE TITLE
disabled tabs

### ISSUE THREAD

**Issue by rapropos** [trimox/angular-mdc-web#147]
I am not sure whether this needs to be proposed upstream at mdc-web, or could be handled here. Frankly, [upstream's feature request policy](https://github.com/material-components/material-components/blob/develop/COMPONENTS_REQUEST_POLICY.md) is rather intimidating, and if their tab component has no disabled attribute, perhaps it is considered "out of guidelines". I couldn't find one.

In any event, I often find it useful for certain tabs to become unselectable due to certain conditions. For example, say we have a user management screen that ordinarily has a tab for deleting users. The system would become unusable if all users are deleted, so in the situation that there is only one user in the system, I would want this tab to become disabled. I don't want to nuke it out of the tab bar entirely due to users getting kinetically adjusted to the position of various tabs, just make it unresponsive and visually indicated that it is not available.

For reference, angular/material2 did it [this way](https://github.com/angular/material2/pull/934).

**Comment by trimox** [comment]
Hey @rapropos

Good points. Since MD guidelines do not include specs for disabled tabs, lemme reach out to MCW team for guidance.

**Comment by trimox** [comment]
Hey @rapropos, MCW team is gathering info from the teams. Will update soon as I hear back.

**Comment by trimox** [comment]
I heard back from MCW team, and no other teams have design details for disabled tabs. So, we'll design a `disabled tab` in Angular MDC. I plan to go through the lengthy process and submit a formal feature request though.

**Comment by trimox** [comment]
@rapropos Disabled tab will be available shortly; including the change with a few other Tab commits.

**Comment by trimox** [comment]
All set. Once PR #369 is merged, I'll close issue.
