### ISSUE TITLE
tab-scroller: Fix server side rendering

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#1474]

**Comment by trimox** [comment]
@jeetChaudhari Found some more in `tab-scroller`. Pushing PR in a few. I've began adding platform detection to our unit testing. Should help identify all the code we have that isn't SSR ready.

**Comment by JeetChaudhari** [comment]
@trimox Does this mean that we can unit test this lib for SSR? If this it then just awesome. It is very time-consuming to set-up SSR project and then copy all updated files from demo and start prerendering. One more issue is if an error occurs, I need to comment that part of the code and again start prerendering.

**Comment by trimox** [comment]
Yep, we're able to test for SSR compatibility. Trust me, I know! That manual testing was unbearable..huge propz to you for doing that! :gem:
