### ISSUE TITLE
text-field adapter registerValidationAttributeChangeHandler throws errors in Universal

### ISSUE THREAD

**Issue by JSMike** [trimox/angular-mdc-web#1486]
### What Angular MDC version are you using?
0.40.2

### What browser(s) is this bug affecting?
Angular Universal

### What OS are you using?
Windows

### What are the steps to reproduce the bug?
Setup a Universal Server and have a text-field on the page that's loaded

### What is the expected behavior?
No errors

### What is the actual behavior?
Throws error for non-existant MutationObserver

### Any other information you believe would be useful?

https://github.com/trimox/angular-mdc-web/blob/1ca6b885a7925155e59683fbd9093f9baef6e617/packages/textfield/text-field.ts#L232

MutationObserver isn't defined in Domino, which is used by Universal to render the DOM. This is causing server-side errors when loading a page through Universal.

```
ReferenceError: MutationObserver is not defined
message:"MutationObserver is not defined"
```

**Comment by JSMike** [comment]
Instead of using MutationObserver would it make sense to add a FormControl to the input field and listen to ValueChanges?

**Comment by trimox** [comment]
Replacing `MutationObserver`, expecting to have PR pushed tomorrow.

**Comment by trimox** [comment]
@JSMike If you want to try the latest version.

`npm i @angular-mdc/web@next` or `yarn upgrade @angular-mdc/web@next`

**Comment by trimox** [comment]
@JSMike All good, you'll want `@angular-mdc/web@latest` 😄

**Comment by JSMike** [comment]
Hi @trimox I'm having issues with the latest version, not sure if it's related, but on loading a form with pre-filled fields that are disabled the "mdc-floating-label--float-above" class isn't being added. I'll reproduce and post link.

**Comment by JSMike** [comment]
@trimox looks like it's happening regardless of if it's disabled at the start, my local example just happened to be disabled. It's not detecting that there's a value on the initial load so it's not adding the class to float above.

https://stackblitz.com/edit/angular-dmyu1p

**Comment by JSMike** [comment]
@trimox found the issue: https://github.com/trimox/angular-mdc-web/commit/739b8aff1be4a14828a04c6220b80f0dd0ec760c#r31196280 it was separate, I'll create a new issue.
