### ISSUE TITLE
first item gets "selected/highlighted" when open up menu

### ISSUE THREAD

**Issue by kzsense** [trimox/angular-mdc-web#1490]
The first mdc-list-item in the menu gets auto "highlighted" whenever I open up menu. Can someone please help how to prevent that from happening?

I have tried:
1. invoke blur() on the first item of menu whenever open up menu, no luck.
2. try to find sass mixins to change the highlight color, but didn't find it in either menu or list.
3. set the selected or activated state to false for that item, but it looks like it they are different stuffs, nothing to do with this "highlight".

please help...

when I click "open menu" from the link below, the first item "fight" gets auto highlighted.
https://stackblitz.com/edit/angular-mdc-menu?file=app%2Fapp.component.html

### What Angular MDC version are you using?
0.40.2
### What browser(s) is this bug affecting?
chrome
### What OS are you using?
mac os ojmave

**Comment by trimox** [comment]
@kzsense Hey there is a **long** discussion on this topic here https://github.com/material-components/material-components-web/issues/3922

Lemme digest everything discussed and see if it's possible to implement on our side.

**Comment by kzsense** [comment]
Thanks for the reply @trimox , I have read through the replies in that thread and understand there is behavior or modularity issues involved not only just menu itself.
I mean it's not a huge issue for me in my app for now, so if it's not easy to do just leave it.
Thanks!
