### ISSUE TITLE
select: Outlined select border doesn't match the theme color

### ISSUE THREAD

**Issue by kenpb** [trimox/angular-mdc-web#1502]
### What Angular MDC version are you using?

0.40.1

### What browser(s) is this bug affecting?

Firefox/Chrome

### What OS are you using?

Linux Mint 19

### What are the steps to reproduce the bug?

Using the select component with the outline property, click the select to focus.

### What is the expected behavior?

The border should match the primary color theme.

### What is the actual behavior?

The border color doesn't change.

### Any other information you believe would be useful?

The behaviour can be seen in the demo page, tried forcing the recolour with mdc-select-focused-outline-color

**Comment by trimox** [comment]
Thanks for reporting this.

I'm currently working on #1402, and will try to duplicate.

**Comment by trimox** [comment]
@kenpb Tested against master, and it's good to go. Working to get new version v0.41.0 out the door, and you'll be set.

**Comment by trimox** [comment]
Here are some custom Sass examples for select.

https://github.com/trimox/angular-mdc-web/blob/master/demos/sass/_select.scss

**Comment by kenpb** [comment]
@trimox awesome, thank you very much, just pulled master and everything looks great!

Off topic:

I've found a weird behaviour with the scrolling tabs component, it seems like it will only autoscroll correctly (centring the selected tab) if it's wrapped in a flex div just like in the "Scrolling Tabs with Scroll Buttons" demo from the page, the bug is consistent across Android, iOS and in Chrome, Google App, Safari and Firefox of each platform.

Dunno if this workaround is indeed a workaround or the intended way of using the component, should I open another issue?

**Comment by trimox** [comment]
No prob! Could you create another issue for the tab question? I'll take a look.

Closing resolved.
