### ISSUE TITLE
TextField Input Character broken

### ISSUE THREAD

**Issue by realgsong** [trimox/angular-mdc-web#1508]
### What Angular MDC version are you using?
Tested with master branch of commit 4929e8b3

### What browser(s) is this bug affecting?
Chrome 70.0.3538.77 (64bit)

### What OS are you using?
Ubuntu 18.04.1 LTS
You need Korean IME to type in Korean letters.

### What are the steps to reproduce the bug?
1. clone git repository
1. npm install
1. npm start
1. open localhost:4000 with browser
1. http://localhost:4000/#/textfield-demo
1. Start typing 안녕 with keyboard. You need to type them not copy&paste them.

### What is the expected behavior?
textfield value should be 안녕

### What is the actual behavior?
textfield value has 안ㄴ녕 

See below for video clip of bug repro
https://photos.app.goo.gl/xzMruLykfbBv29hv7

### Any other information you believe would be useful?
This bug is not reproduced with official demo site. https://trimox.github.io/angular-mdc-web/#/textfield-demo 

See below video from official demo site. Bug is not reproed here.
https://photos.app.goo.gl/KWqWQKqiURZ5yp1j7

**Comment by trimox** [comment]
@realgsong Thanks for reporting this. 

I believe this was resolved in the last pre-release, but I want to make sure first.

**Comment by realgsong** [comment]
Ok. I will try it and let you know the result.

2018년 11월 2일 (금) 오전 6:52에 Dominic Carretto <notifications@github.com>님이 작성:

**Comment by trimox** [comment]
@realgsong Just published final v0.41.0, give that one a try if you'd like.

**Comment by realgsong** [comment]
Confirmed it's fixed with 0.41.0. Thank you!

**Comment by trimox** [comment]
Awesome! 😄 

Closing issue.
