### ISSUE TITLE
Update mdc-icon documentation

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#1517]
Not sure how I missed this. Need to include docs for using SVG, and `MdcIconRegistry`

**Comment by MatejKustec** [comment]
Hi, is it possible to get simple example how to use SVG icons? I'm trying to use it in `mdc-textfield` but not sure how. I tried with `<svg>` tag but it was not working.

**Comment by trimox** [comment]
Sure. I haven't had an opportunity to put together a proper `mdc-icon` documentation. But this gave me an opportunity to play around. Officially, the `svg` element is not fully supported with `material-components-web` until this upstream issue is resolved https://github.com/material-components/material-components-web/issues/3747

Import the `MdcIconRegistry` service, and `DomSanitizer`.
```ts
import { DomSanitizer } from '@angular/platform-browser';
import { MdcIconRegistry } from '@angular-mdc/web';

constructor(iconRegistry: MdcIconRegistry, sanitizer: DomSanitizer) {
  iconRegistry.addSvgIcon(
    'thumbup', sanitizer.bypassSecurityTrustResourceUrl('/assets/thumbup-icon.svg'));
}
```

```html
<mdc-text-field outlined label="Svg icon">
  <mdc-icon mdcTextFieldIcon leading svgIcon="thumbup"></mdc-icon>
</mdc-text-field>
```

Lastly, add `top: 0.90em` style to the `mdc-icon` component to correct alignment. Small workaround until official support of `svg` is implemented upstream. 

![sample](https://user-images.githubusercontent.com/11887843/49776612-b3817800-fcca-11e8-8f03-8ab0d997f541.gif)

**Comment by MatejKustec** [comment]
Thanks for simple explanation, it's working now.
