### ISSUE TITLE
Placeholder(label) of a select overlaps options

### ISSUE THREAD

**Issue by jacobfederer** [trimox/angular-mdc-web#1519]
### What Angular MDC version are you using?

41

### What browser(s) is this bug affecting?

Safari

### What OS are you using?

MacOS

### What are the steps to reproduce the bug?

Here is my code:

 ```
<mdc-select placeholder="Unit"  outlined>
              <option value="kg">kg</option>
              <option value="ml">ml</option>
            </mdc-select>
```

### What is the expected behavior?

That the placeholder is up top the selected option. 

### What is the actual behavior?

![bildschirmfoto 2018-11-02 um 17 03 57](https://user-images.githubusercontent.com/1516212/47909217-d21d7380-dec1-11e8-945e-fbc5601a54a6.png)

At first placeholder and preselected option overlap each other. This can be resolved only by clicking on the select and choosing something. Then placeholder will display correctly.

**Comment by trimox** [comment]
@jacobfederer Thanks for reporting this.

That is odd! I have an example on the demo site that closely resembles that code, I'll check it out.

**Comment by trimox** [comment]
Duplicated. Working on a PR
