### ISSUE TITLE
Is it possible to disable the ripple effect on any element?

### ISSUE THREAD

**Issue by zunamo** [trimox/angular-mdc-web#1521]
In my case, I would like to disable the ripple effect on chips.
Is this possible? If so how can I achieve this?

**Comment by trimox** [comment]
@zunamo Thanks for the question. 
Currently there is no option to disable ripple on chips, however we could add a `disableRipple` property. I'll investigate and let ya know.

**Comment by zunamo** [comment]
Perfect thanks!

**Comment by zunamo** [comment]
I forgot to give you some info on why I had this request originally. I made a scroll-able chip bar and the ripple effect was causing the scrolling to be choppy on iOS saffari ( with webkit-overflow-scrolling: touch). I just tested with disableRipple and it scrolls smoothly. But just so you are aware, this same issue will probably occur for other elements with ripple enabled. I believe it is because the ripple temporarily enlarges the element (and also its parent), causing the scrolling to become choppy.
