### ISSUE TITLE
Tab scroller will not scroll correctly on mobile

### ISSUE THREAD

**Issue by kenpb** [trimox/angular-mdc-web#1529]
### What Angular MDC version are you using?
0.41.0

### What browser(s) is this bug affecting?
I've tested 

### What OS are you using?
Android, iOS

### What are the steps to reproduce the bug?
This is a recording from the demo page
![out](https://user-images.githubusercontent.com/2224388/47959821-16d50780-dfb3-11e8-8cfa-c3807707c902.gif)

### What is the expected behavior?
The tabs should be centered on selection as seen in the last example

### What is the actual behavior?
The component scrolls more than it should

### Any other information you believe would be useful?
Seems like this will happen unless the tab component is wrapped with a `display: flex;` container, this is appreciated in the last example of the demo page.

Tested in Chrome, Google App, Safari and Firefox in iOS and Chrome on Android

**Comment by trimox** [comment]
Possibly related to #1543

**Comment by trimox** [comment]
Got this resolved! Thanks again! PR incoming.

**Comment by kenpb** [comment]
Thank you for your support!

**Comment by trimox** [comment]
@kenpb Apologizes, this wasn't resolved fully. PR incoming for issue #1685
