### ISSUE TITLE
Swipe to close the drawer

### ISSUE THREAD

**Issue by ofekashery** [trimox/angular-mdc-web#1532]

**Comment by trimox** [comment]
@ofekashery Yep, drawer was recently reimplemented, and investigating best approach to implement gestures.

**Comment by ofekashery** [comment]
I want to be able to close it by swipe (right to left)

**Comment by trimox** [comment]
Sure. Definitely doable via library such as hammerjs.

http://hammerjs.github.io/recognizer-swipe/

**Comment by Techno11** [comment]
Any update on this feature?  Thanks!
