### ISSUE TITLE
MdcTextField mdcFloatingLabel not floating when field has initial value

### ISSUE THREAD

**Issue by JSMike** [trimox/angular-mdc-web#1534]
### What Angular MDC version are you using?
0.41.1

### What browser(s) is this bug affecting?
Chrome (All)

### What OS are you using?
Windows (Not an OS dependent issue)

### What are the steps to reproduce the bug?
Add MdcTextfield to page with initial value from formControl

https://stackblitz.com/edit/angular-dmyu1p

### What is the expected behavior?
An MdcTextField with an initial value should have the label floating

### What is the actual behavior?
The label is not floating when an MdcTextField has an initial value

### Any other information you believe would be useful?
`AfterViewInit` is after `AfterContentInit` in the component lifecycle. I think that changing the init function call to `AfterViewInit` would be enough to resolve this issue.

Issue was introduced with this commit/line: https://github.com/trimox/angular-mdc-web/commit/739b8aff1be4a14828a04c6220b80f0dd0ec760c#r31196280

**Comment by JSMike** [comment]
@trimox FYI: Confirmed solution locally by modifying my project's textfield.es5.js file from `AfterContentInit` to `AfterViewInit`

**Comment by trimox** [comment]
@jsmike Thank you for reporting this. 

I could have sworn another problem arose using `AfterViewInit`, but I'm probably confusing another component. Thanks for researching and testing! Will check it out.
