### ISSUE TITLE
BUILD ERROR: Warning messages when building with --prod related to MdcIconRegistry + MDC_ICON_LOCATION, making build not functional

### ISSUE THREAD

**Issue by zunamo** [trimox/angular-mdc-web#1535]
I am getting the following warning messages when building with --prod. I get these 2 messages for every component using mdc-icon. 

`WARNING in ./src/app/compare/compare.component.ngfactory.js
99:571-589 "export 'MdcIconRegistry' (imported as 'i7') was not found in '@angular-mdc/web/icon'`

`WARNING in ./src/app/compare/compare.component.ngfactory.js
99:602-622 "export 'MDC_ICON_LOCATION' (imported as 'i7') was not found in '@angular-mdc/web/icon'`

When the build is complete, my app does not show up at all and I get this error message in the console:

`ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'ngInjectableDef' of undefined
TypeError: Cannot read property 'ngInjectableDef' of undefined`

### What Angular MDC version are you using?
0.41.1 (Angular 6.0.1)

### What is the expected behavior?
No warning/error messages, functional build

### What is the actual behavior?
Warning messages when building with --prod, build not functional

**Comment by jorgecuevas92** [comment]
I'm experiencing the same behavior, and the build does not work, the only difference are my warnings and version of mdc and angular I get these warnings:
```
WARNING in ./node_modules/@angular-mdc/web/esm5/overlay.es5.js
132:127-146 "export 'coerceCssPixelValue' was not found in '@angular-mdc/web/common'

WARNING in ./node_modules/@angular-mdc/web/esm5/overlay.es5.js
132:182-201 "export 'coerceCssPixelValue' was not found in '@angular-mdc/web/common'

WARNING in ./node_modules/@angular-mdc/web/esm5/overlay.es5.js
132:240-259 "export 'coerceCssPixelValue' was not found in '@angular-mdc/web/common'

WARNING in ./node_modules/@angular-mdc/web/esm5/overlay.es5.js
132:298-317 "export 'coerceCssPixelValue' was not found in '@angular-mdc/web/common'

WARNING in ./node_modules/@angular-mdc/web/esm5/overlay.es5.js
132:356-375 "export 'coerceCssPixelValue' was not found in '@angular-mdc/web/common'

WARNING in ./node_modules/@angular-mdc/web/esm5/overlay.es5.js
132:75-94 "export 'coerceCssPixelValue' was not found in '@angular-mdc/web/common'

WARNING in ./node_modules/@angular-mdc/web/esm5/overlay.es5.js
168:67-78 "export 'coerceArray' was not found in '@angular-mdc/web/common'

WARNING in ./node_modules/@angular-mdc/web/esm5/web.es5.js
19:0-298 "export 'coerceArray' was not found in '@angular-mdc/web/common'

WARNING in ./node_modules/@angular-mdc/web/esm5/web.es5.js
19:0-298 "export 'coerceCssPixelValue' was not found in '@angular-mdc/web/common'

WARNING in ./node_modules/@angular-mdc/web/esm5/web.es5.js
39:0-126 "export 'MdcRippleConfig' was not found in '@angular-mdc/web/ripple'

WARNING in ./node_modules/@angular-mdc/web/esm5/web.es5.js
48:0-208 "export 'MdcTextFieldIcon' was not found in '@angular-mdc/web/textfield'
```

What Angular MDC version are you using?
0.40.2 (Angular 6.0.2)

What is the expected behavior?
No warning/error messages, functional build

What is the actual behavior?
Warning messages when building with --prod, build not functional

**Comment by trimox** [comment]
@zunamo @jorgecuevas92 Very odd. I've not yet duplicated. 

Could you try removing the `node_modules` folder, and reinstall via `npm i` or `yarn`? I'm guessing `npm` left some pointers to removed files on your systems.

**Comment by zunamo** [comment]
This worked for me! Thanks.

**Comment by jorgecuevas92** [comment]
This also worked for me!
Thank you @zunamo
