### ISSUE TITLE
Tabs have a focus highlight upon activation, even with focusOnActivate set to false

### ISSUE THREAD

**Issue by zunamo** [trimox/angular-mdc-web#1536]
I noticed that tabs now have a focus highlight after activation. Following the documentation, I tried to set focusOnActivate to false on the tab-bar. This does not seem to do anything. Am I missing something?

### What Angular MDC version are you using?
0.41.1

### What is the expected behavior?
Focus highlight removed from tab after selecting / activating

### What is the actual behavior?
Focus highlight stays even with 'focusOnActivate' set to false

**Comment by ofekashery** [comment]
That happens to me, too. I would be happy if it will be fixed as soon as possible

**Comment by trimox** [comment]
@zunamo @ofekashery Thanks for reporting this! 

Sorry for the delay, just returned from vacation. Looks like I forgot to push the value to the `tab` component!

**Comment by zunamo** [comment]
Are you sure this has been fixed? I do not see any change with before.
