### ISSUE TITLE
Add Data Table Component

### ISSUE THREAD

**Issue by ofekashery** [trimox/angular-mdc-web#1539]
Re #587

**Comment by ofekashery** [comment]
https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#310-2019-07-22

Added yesterday 😄

**Comment by joselcvarela** [comment]
@trimox will this feature implemented soon?

**Comment by bryyyanribo** [comment]
Hi @trimox, any plans for this feature to be implemented soon?

**Comment by trimox** [comment]
Very soon 5-7 days. I'm ramping back up to support latest version of MDC.

**Comment by joselcvarela** [comment]
@trimox You are an angel :D
Thank you very much for this awesome project

**Comment by trimox** [comment]
All set. Merging https://github.com/trimox/angular-mdc-web/pull/1954
