### ISSUE TITLE
ngModel in the text-field is not change at time

### ISSUE THREAD

**Issue by ofekashery** [trimox/angular-mdc-web#1541]
### What Angular MDC version are you using?
0.41.1
### What browser(s) is this bug affecting?
Chrome
<br/><br/>
This is changed only after I type another letter.
Example code:
```HTML
<mdc-text-field label="Team #" [(ngModel)]="team" (change)="getTeam()"></mdc-text-field>
```
```TS
getTeam() {
    console.log(this.team);
}
```
If I write ``X``, it doesn't print anything
If I write ``XY``, It prints ``X``
If I write ``XYZ``, It prints ``XY``

**Comment by ofekashery** [comment]
This is the ``ngModel`` that does not change at the time. The ``(change)`` is called

**Comment by ofekashery** [comment]
I really don't understand what's going on there, but it doesn't work properly

**Comment by trimox** [comment]
Duplicated. Working on it now

**Comment by trimox** [comment]
Fix incoming. Just had to set `ControlValueAccessor` prior to emitting change event.

**Comment by trimox** [comment]
Fyi, publishing v0.41.2 in next couple of hours, includes this and few other fixes.
