### ISSUE TITLE
Scrollbar visible below mdc-tab-scroller on Edge and Firefox

### ISSUE THREAD

**Issue by zunamo** [trimox/angular-mdc-web#1543]
### What Angular MDC version are you using?
0.39

### What browser(s) is this bug affecting?
Firefox and Edge

### What OS are you using?
Windows 10

### What is the expected behavior?
No visible scrollbar under tab bar

### What is the actual behavior?
Scrollbar visible below tab bar

### Any other information you believe would be useful?
Firefox:
![firefox_2018-11-18_01-41-27](https://user-images.githubusercontent.com/44700257/48667356-099c3a80-ead4-11e8-82e8-27a50703ae43.png)

Edge:
![applicationframehost_2018-11-18_01-42-00](https://user-images.githubusercontent.com/44700257/48667357-099c3a80-ead4-11e8-9f8f-1fd4cc50b9a0.png)

I hope this can be fixed, especially in this situation where there is nothing to scroll.

**Comment by trimox** [comment]
@zunamo Thanks for reporting this.

Testing this, see if I can find the problem.

**Comment by saulbensach** [comment]
Helloo
This is also happening to me in firefox, getting an horizontal scrollbar.
mdc-tab-scroller injects the class .mdc-tab-scroller__scroll-area--scroll where overflow-x is scroll instead of hidden.

**Comment by trimox** [comment]
Duplicated. Not seeing this occur with upstream MDC demos, so next step is reviewing component template..

**Comment by trimox** [comment]
Ah, narrowed it down to an adapter problem. Testing

**Comment by trimox** [comment]
Still investigating.

**Comment by trimox** [comment]
Got this resolved! Thanks again! PR incoming.
