### ISSUE TITLE
Add Autocomplete

### ISSUE THREAD

**Issue by ofekashery** [trimox/angular-mdc-web#1554]

**Comment by trimox** [comment]
Please follow upstream issue, https://github.com/material-components/material-components-web/issues/45. 

If and when an autocomplete is made available, we'll definitely incorporate here.

**Comment by trimox** [comment]
Closing. No upstream activity

**Comment by gpulido** [comment]
Hello, I know that this feature is waiting to be available upstream on the mdc, but it seems to be completelly stalled there, although from my pow is one of the main missing features to make mdc a complete usable library.
So while it is implemented on mdc on a couple of years I'm trying to replicate it with a custom angular component just wrapping a mdc-text-field and a menu and duplicating some of the code of the mdc-selector. this is the gist of the component: 
https://gist.github.com/gpulido/4bae80a5be4fd5c7ed61f1f1667da039
My problem now is that thiscomponent lacks proper integration with the error management on forms.
After looking to the mdc-select or mdc-formfield I'm not sure of the best approach to integrate it as it seems that heavely depends on the mdc mixins and "foundation" classes.
Any suggestion on how can I add it?
Thanks in advance,
(Of course my idea is to publish it as a public component or at least as a gist)
