### ISSUE TITLE
Drawer animation, hammerjs compatibility and thank you

### ISSUE THREAD

**Issue by Extarys** [trimox/angular-mdc-web#156]
Hi! I'm new to angular and the first thing I did was installing Angular Material 2, but they lack a lot of features I want/need. Mostly Mobile/Tablet/PC friendly.

Found it this little library, awesome. Thanks for all the time you are putting into this.

Question:
The drawers don't seems animated (sliding), is it just me or it's not yet implemented?
Would this work with hammerjs? 

Comment:
I did the suggestion too in the Material Github but it would be great to also have css helper, live round avatar, badges, etc.

Thanks again xx

**Comment by trimox** [comment]
Hey @Extarys , thank you!
Drawers have slide in/out animations. What platform & browser are you're using? I'll run it through  SauceLabs test.

Yep! Our WIP theming directives include an optional SASS library for common MD use cases.
Follow issue: [Implement MDC Theme](https://github.com/trimox/angular-mdc-web/issues/112)

**Comment by Extarys** [comment]
Thanks for you reply. I had an issue with some js files not loading (too much security in DDWRT). I see them now sorry.

Thanks for linking that, once we figure out how to use this with `angular-cli` I'll check it out ;)

**Comment by sandangel** [comment]
Drawers have slide in/out animations but the toolbar is pushed immediately to the right when open persistent drawer. Any work around to fix this?

**Comment by Extarys** [comment]
I could clone the project and take a look bvut I won't have time until next week maybe

**Comment by Extarys** [comment]
Thanks for you reply. I had an issue with some js files not loading (too much security in DDWRT). I see them now sorry.

Thanks for linking that, once we figure out how to use this with `angular-cli` I'll check it out ;)

**Comment by trimox** [comment]
@sandangel Persistent drawers sit on the same surface elevation as the content, and when toggled open they force other content to adapt to a smaller viewport (not intended for mobile). It sounds like you'd want to use the Temporary drawer `mdc-temporary-drawer`, which opens temporarily above all other content and is suitable for all device sizes.

**Comment by sandangel** [comment]
@trimox I want to use persistent drawer but I as you can see, while drawer is smoothly slide in/ out, all other content on viewport  is not smoothly transitioned with the drawer, instead they immediately forced to smaller view port, which i think is a poor user experience

**Comment by trimox** [comment]
Good point. Since MD guidelines do state that an opened persistent drawer does force content to change size and adapt to the smaller viewport, we need to address this.

**Comment by trimox** [comment]
Created a new directive called `mdc-content`.
PR incoming
