### ISSUE TITLE
top appbar navigation icon is remained as selected

### ISSUE THREAD

**Issue by realgsong** [trimox/angular-mdc-web#1563]
### What Angular MDC version are you using?
Built from source code with commit 4ce51c32

### What browser(s) is this bug affecting?
Mobile Chrome 70.0.3538.110 

### What OS are you using?
Android 9.0

### What are the steps to reproduce the bug?
1. Remove onclick listener from demo code. See diff here https://github.com/realgsong/angular-mdc-web/commit/01d0cf262f635453247fd9d6e77ff1b94cdb5052
1. npm install
1. npm start
1. Open Chrome in Android.
1. go to localhost:4000 in Android Mobile Chrome browser. You need to remote-debug. See https://developers.google.com/web/tools/chrome-devtools/remote-debugging/ for more detail
1. Click on menu icon in top app bar

### What is the expected behavior?
Icon is not selected. 

### What is the actual behavior?
icon is selected. It causes android to suggest google search result. See 
 https://photos.app.goo.gl/hQJnTrEjd3JSDyYq7 for screenshot

### Any other information you believe would be useful?
Not reproed with desktop chrome

**Comment by trimox** [comment]
@realgsong Thanks for reporting this. Duplicated it, and noticed same thing on a couple card examples.

**Comment by trimox** [comment]
@realgsong Give this a try.

```html
<button mdcIconButton mdcTopAppBarNavIcon icon="menu"></button>
```
