### ISSUE TITLE
how to make top app bar responsive

### ISSUE THREAD

**Issue by kzsense** [trimox/angular-mdc-web#1565]
### What Angular MDC version are you using?
0.40.2
### What browser(s) is this bug affecting?
mobile chrome
### What OS are you using?
ios 12.0

the top app bar didn't collapse when I shrink the width of the browser window... Can you please suggest how to approach the responsive top app bar please and thank you?

**Comment by trimox** [comment]
Hey @kzsense 

`mdc-top-app-bar` only collapses for a scroll event. You can however, control when it's collapsed with the `shortCollapsed: boolean`; maybe listening for resize.

**Comment by kzsense** [comment]
Sure thanks @trimox I will try this see if there is any luck.
And by the way I noticed the drawer on angular mdc website stays as 'dismissble' when the browser window has enough width, and it automatically turns into 'Modal' when the width is shrinked, is there any properties in drawer for me to control this or I have to do it manually like "shortCollapsed" ?

Sorry I was stucked at the responsive part of my website

**Comment by trimox** [comment]
@kzsense I may have misunderstood the question. It sounds like you'd like the same functionality as the demo app, this may help.

The change happens here, 
```html
[drawer]="isScreenSmall() ? 'modal' : 'dismissible'"
```

Full code https://github.com/trimox/angular-mdc-web/blob/master/demos/app-layout.html
```html
<mdc-drawer class="demo-drawer" #appdrawer="mdcDrawer" [open]="!isScreenSmall()" [drawer]="isScreenSmall() ? 'modal' : 'dismissible'" mdcTopAppBarFixedAdjust>
```

and the TypeScript
https://github.com/trimox/angular-mdc-web/blob/master/demos/app-layout.ts

**Comment by kzsense** [comment]
Thanks so much @trimox !
