### ISSUE TITLE
File to import not found / SCSS [Help]

### ISSUE THREAD

**Issue by Extarys** [trimox/angular-mdc-web#157]
I had to `@import "../node_modules/material-components-web/material-components-web.scss";` and the erorr changed to :

```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
Module build failed: 
@import "@material/animation/mdc-animation";
^
      File to import not found or unreadable: @material/animation/mdc-animation.
Parent style sheet: /media/DarkHawk/srv/NodesProjects/TestApp/node_modules/material-components-web/material-components-web.scss
      in /media/DarkHawk/srv/NodesProjects/TestApp/node_modules/material-components-web/material-components-web.scss (line 17, column 1)
Error: 
@import "@material/animation/mdc-animation";
^
      File to import not found or unreadable: @material/animation/mdc-animation.
Parent style sheet: /media/DarkHawk/srv/NodesProjects/TestApp/node_modules/material-components-web/material-components-web.scss
      in /media/DarkHawk/srv/NodesProjects/TestApp/node_modules/material-components-web/material-components-web.scss (line 17, column 1)
    at options.error (/media/DarkHawk/srv/NodesProjects/TestApp/node_modules/node-sass/lib/index.js:291:26)
 @ ./src/styles.scss 4:14-187
 @ multi ./src/styles.scss ./node_modules/froala-editor/css/froala_editor.pkgd.min.css ./node_modules/froala-editor/css/froala_style.min.css
 
webpack: Failed to compile.
```

My setup is the one that come with the angular-cli.
I'm hesitating to change the paths directly because future updates will break it.

How should I fix this?

(Maybe it's basic, I'm total noob to Angular/Webpack/etc)

**EDIT**

Maybe it's a similar issue (path), but I copy/paste the [sample provided here](https://trimox.github.io/angular-mdc-web/#/toolbar-demo) for the navbar and I got a succesful compile (without the scss of course), but in the browser I get:

```
ERROR 
TypeError: _co.handleToolbarChange is not a function
Stack trace:
View_AppComponent_0/<@ng:///AppModule/AppComponent.ngfactory.js:15:23
handleEvent@http://127.0.0.1:4200/vendor.bundle.js:70736:98
callWithDebugContext@http://127.0.0.1:4200/vendor.bundle.js:72197:39
```
[Full backtrace here](https://gist.github.com/Extarys/9fbb6a0f0dbbe4a43861aacb8c523295).

app.module.ts include: `import { MaterialModule } from '@angular-mdc/web';` Before you ask ;)

**Comment by trimox** [comment]
@Extarys Same issue as #129. I've not tried the Angular-CLI yet. Sounds like developers do not have access to a Webpack config to use `sass-loader` + `includePaths` (e.g.: `includePaths: ['../node_modules', '../node_modules/@material/*']`)

I'll grab Angular-CLI and figure this out, should have an answer by Wednesday.

**Comment by Extarys** [comment]
Thank you so much!
If I come up wiith something I'll let you know

**Comment by trimox** [comment]
Got it working 😄  

I'm writing a quick "how-to-guide" doc, should be available 20-30 minutes.

**Comment by Extarys** [comment]
HURRAY!

Thanks @trimox ;) I knew you were the best ;)

**Comment by Extarys** [comment]
`@import "~material-components-web/material-components-web";`In `app.component.scss` gives the following error:

```
ERROR in ./src/app/app.component.scss
Module build failed: 
@import "@material/animation/mdc-animation";
^
      File to import not found or unreadable: @material/animation/mdc-animation.
Parent style sheet: /media/DarkHawk/srv/NodesProjects/Acknitor/node_modules/material-components-web/material-components-web.scss
      in /media/DarkHawk/srv/NodesProjects/Acknitor/node_modules/material-components-web/material-components-web.scss (line 17, column 1)
Error: 
@import "@material/animation/mdc-animation";
^

      File to import not found or unreadable: @material/animation/mdc-animation.
Parent style sheet: /media/DarkHawk/srv/NodesProjects/Acknitor/node_modules/material-components-web/material-components-web.scss
      in /media/DarkHawk/srv/NodesProjects/Acknitor/node_modules/material-components-web/material-components-web.scss (line 17, column 1)
    at options.error (/media/DarkHawk/srv/NodesProjects/Acknitor/node_modules/node-sass/lib/index.js:291:26)
 @ ./src/app/app.component.ts 22:17-48
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
 
webpack: Failed to compile.
```

Removing the `~` gives the same error as before. No error importing the Module though.

**Comment by trimox** [comment]
Not a problem @Extarys! Glad to help.

**Comment by trimox** [comment]
@Extarys Here's quick link
Angular CLI - Step by step guide
https://github.com/trimox/angular-mdc-web/blob/master/docs/guide-angular-cli.md

**Comment by Extarys** [comment]
Sorry I post before seeing it, I though I deleted my post before anyone sees it.

Everything seems to be working for now. Thanks bud'
