### ISSUE TITLE
What a find! this is awesome! + Feature request: Mini variant drawer

### ISSUE THREAD

**Issue by devlfm** [trimox/angular-mdc-web#158]
Hi!

Thank you very much for this effort! Do you have any milestone for the slider/select component?

I'll try this great lib today night at home!

Thank you very much sir!

**Comment by trimox** [comment]
@devlfm Thank you! 💐 
Sure do. Our select component will be made available shortly after material-components/material-components-web#1097 is merged. The select component received quite an overhaul and it looks amazing 😄 

You'll see a pull request for Slider in the next 5-7 days, and it'll deploy with v0.5.0..
Thanks again, and if you need assistance getting started, please reach feel free to ask.
-Trimox

**Comment by devlfm** [comment]
oh great! Can't wait to try those! (in fact I can't go without them ^^)

I can also suggest that you make the drawer implementation of [Mini variant](https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior)  

there's a discussion [here](https://github.com/angular/material2/issues/1728) but seems to be going nowhere.. this would be a very welcome feature.

If I make some improvements while testing I'll let you know :)

thank you!

**Comment by trimox** [comment]
Thanks @devlfm! I'm adding this to our tracker.

![image](https://user-images.githubusercontent.com/11887843/30516467-394b0ae8-9b0e-11e7-8e4f-34da05f0c865.png)

**Comment by marcusrichards** [comment]
Agreed, thanks @trimox , this is a great job - have built our AI [website](http://www.appliedmachinelearning.co.uk) with mdc and people like it so far! Have a lot of data grid and data components stuff coming up to build, and charting etc, so any components along those lines would really help :) No pressure!

**Comment by trimox** [comment]
Closing.
