### ISSUE TITLE
Select options should look like menu surface list

### ISSUE THREAD

**Issue by JeetChaudhari** [trimox/angular-mdc-web#1592]
Actually, this is a question, I know it is not according to material design, however, can we please provide two options for select so that select does not look awful?

Here is what I would like. Angular Material, as well as Material UI for React, has this feature.

Angular Material
https://material.angular.io/components/select/overview

Material UI for React
https://material-ui.com/demos/selects/#selects

These both packages have two options for selecting as Basic and Native but currently, we have the only Native option. I tried to use Menu but it doesn't go well look and feel wise.

**Comment by trimox** [comment]
@JeetChaudhari Hey, great timing for the question. Enhanced select will be finished and ready for v0.42.1.

reference: https://github.com/material-components/material-components-web/tree/master/packages/mdc-select#enhanced-select
