### ISSUE TITLE
Text Field: error state displayed inconsistently when required set to true

### ISSUE THREAD

**Issue by ddaspit** [trimox/angular-mdc-web#1606]
### What Angular MDC version are you using?
0.42.0
### What browser(s) is this bug affecting?
Chrome 71
### What OS are you using?
Windows 10
### What are the steps to reproduce the bug?
This issue can be reproduced using the first demo in the Text Field [documentation](https://trimox.github.io/angular-mdc-web/#/text-field-demo). It is important that the `required` attribute is set to `true`.
- Type the value "test" in the text field
- Click on another control so the text field loses focus
- Click back on the text field, so that the cursor is at the end of the value
- Hit backspace twice
- The text field will correctly display the validation error.
- Hit backspace once
- The text field will no longer display the validation error.
### What is the expected behavior?
It is expected that the text field will continue to display the validation error, since the value is below the minimum length of 3.
### What is the actual behavior?
The text field no longer displays the validation error.
### Any other information you believe would be useful?
I did a little bit of investigation in to the code. It looks like this is caused by the `_handleValidationAttributeChange()` method when it is called by the `setValue()` method. The `_handleValidationAttributeChange()` calls the `handleValidationAttributeChange()` method on the text field foundation and passes in an array of all attributes that have been set, including `required`. When MDC Web is told that the `required` attribute has changed, it removes the `mdc-text-field--invalid` class from the element by directly manipulating the DOM. It seems to do this whenever the text field value is changed.

**Comment by trimox** [comment]
@ddaspit Thanks for reporting and the investigative work! 💎  I'll take a look.

**Comment by trimox** [comment]
PR submitted.

**Comment by trimox** [comment]
Fixed, merged with #1596

**Comment by ddaspit** [comment]
Thank you for fixing this.
