### ISSUE TITLE
mdc-icon is not rendering icons when font-family is changed

### ISSUE THREAD

**Issue by saulbensach** [trimox/angular-mdc-web#1608]
### What Angular MDC version are you using?
"@angular-mdc/web": "^0.40.2"

### What browser(s) is this bug affecting?
Google Chrome Versión 70.0.3538.110 (Build oficial) (64 bits)
Firefox Quantum 64.04 64 bits
Others not tested

### What OS are you using?
Windows 10 Home

### What are the steps to reproduce the bug?
Change font-family: on css or scss to something like  'Roboto', sans-serif;
* {
   font-family: 'Roboto', sans-serif;
}
if this is placed in the main stylesheet all icons will be broken

### What is the expected behavior?
mdc-icon showing the icon

### What is the actual behavior?
mdc-icon shows the actual name of the icon, not the icon

### Any other information you believe would be useful?

edit: added firefox

**Comment by trimox** [comment]
@saulbensach Thanks for reporting this. Will take a look.

**Comment by trimox** [comment]
@saulbensach Closing issue. If it didn't work, please let me know thanks!
