### ISSUE TITLE
top app bar doesn't backdropped when dialog pops

### ISSUE THREAD

**Issue by KanathanZhou** [trimox/angular-mdc-web#1626]
### What Angular MDC version are you using?
0.42.0
### What browser(s) is this bug affecting?
chrome

not sure if it is the material's spec but here is what I get:
![bug1](https://user-images.githubusercontent.com/20479084/50264018-bbbc7e80-0453-11e9-9b5e-e73af7a18669.jpeg)

I basically mimicked the code from demo app, and the dialog pops by clicking the button from the top app bar.
Not sure why the top app bar didn't become the backdrop... the problem with this is that I can still click on the same button and the dialog will keep pop up which is weird.

please help

**Comment by trimox** [comment]
Sure, all you should have to do is set `clickOutsideToClose` to `false`.

```ts
let dialogRef = dialog.open(yourDialogComponentHere, {
  clickOutsideToClose: 'false'
});
```

**Comment by trimox** [comment]
I noticed the app bar just now; was difficult to see in pic. Can you duplicate in StackBlitz? It should be behind backdrop.

**Comment by KanathanZhou** [comment]
Hi @trimox , thanks for the reply, so I know why... 
I have both drawer and top app bar on the main page, and I just noticed drawer has default z-index = 6, so in order to make top app bar on top of drawer, I set the z-index of top app bar = 15, but I also just noticed dialog has default z-index = 7, that's why top app bar doesn't become the backdrop lol.

So now the question is what's the best way to resolve it? I mean I manually set the z-index of top app bar to 7 which works well, but not sure if this is the best solution and not sure about any other side effects
