### ISSUE TITLE
[helperText] in mdc-text-field breaks the ng build --prod process

### ISSUE THREAD

**Issue by KanathanZhou** [trimox/angular-mdc-web#1627]
### What Angular MDC version are you using?
0.42.0

error: 
`ERROR in src/app/sign-in/sign-in.component.html(14,29): : Property 'phoneNumberHelper' does not exist on type 'SignInComponent'.
src/app/sign-in/sign-in.component.html(28,29): : Property 'passwordHelper' does not exist on type 'SignInComponent'.`

my code:
            <mdc-text-field #phoneNumberInput type="tel" autocomplete="off" label="Phone Number" maxlength="11"
                            formControlName="phoneNumber" name="phoneNumber"
                            [helperText]="phoneNumberHelper" [errorStateMatcher]="errorMatcher"
                            (change)="togglePhoneNumberInputFocus(true)" (blur)="togglePhoneNumberInputFocus(false)"
                            outlined dense required>
            </mdc-text-field>
            <mdc-text-field-helper-text #phoneNumberHelper="mdcHelperText" validation *ngIf="signInForm.controls['phoneNumber'].dirty && !focusOnPhoneNumberInput && signInForm.controls['phoneNumber'].errors">
....
            </mdc-text-field-helper-text>

I have to add:
`  phoneNumberHelper: any;`
in the corresponding typescript file in order to remove the error, not sure if this is the correct to way to do but.

**Comment by trimox** [comment]
@KanathanZhou Hey, I took your code, but I've as yet been unable to duplicate the issue.

I've put together a StackBlitz, if you'd like to try and duplicate. 
https://stackblitz.com/edit/angular-mdc-text-field-bbevvd

Just a heads up, if you upgrade to yesterdays `v0.42.1` release, you can handle `maxlength`, and `required` attributes via TypeScript.

FormGroup example
```ts
  userForm = new FormGroup({
    phone: new FormControl(
      { value: null, disabled: false }, [Validators.required, Validators.maxLength(11)])
  });
```

Example without `mdc-form-field` wrapper.
```html
<form [formGroup]="userForm" (ngSubmit)="submit()" autocomplete="off">
  <mdc-text-field type="tel" label="Phone Number"
    formControlName="phone" [helperText]="phoneHelper"
    (change)="togglePhoneInputFocus(true)" (blur)="togglePhoneInputFocus(false)"
    outlined dense></mdc-text-field>
  <mdc-helper-text #phoneHelper validation>
    <span *ngIf="userForm.controls['phone'].hasError('required')">Phone is required</span>
    <span *ngIf="userForm.controls['phone'].hasError('maxlength')">Phone max length is 11</span>
  </mdc-helper-text>
</form>
```

Example with `mdc-form-field` wrapper. Notice that the helperText is automated via `mdc-form-field`..
```html
<form [formGroup]="userForm" (ngSubmit)="submit()" autocomplete="off">
  <mdc-form-field>
    <mdc-text-field type="tel" label="Phone Number"
      formControlName="phone" (change)="togglePhoneInputFocus(true)"
      (blur)="togglePhoneInputFocus(false)"
      outlined dense></mdc-text-field>
    <mdc-helper-text validation>
      <span *ngIf="userForm.controls['phone'].hasError('required')">Phone is required</span>
      <span *ngIf="userForm.controls['phone'].hasError('maxlength')">Phone max length is 11</span>
    </mdc-helper-text>
  </mdc-form-field>
</form>
```

**Comment by trimox** [comment]
Forgot to add, if you could provide the contents of your `tsconfig.json`.

**Comment by KanathanZhou** [comment]
sure here it is :
`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
`
