### ISSUE TITLE
mdc-select does not select the option when set value through form control asynchronously

### ISSUE THREAD

**Issue by mixth** [trimox/angular-mdc-web#1638]
### What Angular MDC version are you using?
0.42.2

### What browser(s) is this bug affecting?
Tested on Chrome, Firefox

### What OS are you using?
MacOS

### What are the steps to reproduce the bug?
0. Create template with `mdc-select` with `*ngFor` options.
1. Asynchronously assign dynamic options.
2. Set value of `FormControl` programmatically (via `FormControl::setValue` or `FormGroup::patchValue`).

### What is the expected behavior?
`mdc-select` is selected on the option that has the newly assigned value.

### What is the actual behavior?
`mdc-select` is selected on the first option.

#### Template
```html
<div [formGroup]="form">
  <mdc-select formControlName="select">
    <option *ngFor="let number of numbers" [value]="number">{{ number }}</option>
  </mdc-select>
</div>
```

#### Controller
```typescript
form = this.fb.group({
  select: '',
});

numbers = ['1', '2', '3', '4', '5'];

ngOnInit() {
  setTimeout(() => {
    this.numbers = ['6', '7', '8'];
    this.form.controls.select.setValue('7');
  }, 100);
}
```

**Comment by trimox** [comment]
@mixth Thanks for reporting this. Duplicated, and working on a solution.
