### ISSUE TITLE
demos: Close drawer when route change for small screen devices

### ISSUE THREAD

**Issue by rubenochiavone** [trimox/angular-mdc-web#1639]
### What are the steps to reproduce the bug?

- Open documentation on small screen devices (width <= 1240px)
- Click on menu button
- Select a menu item

### What is the expected behavior?

After clicking on a menu item drawer should be closed.

### What is the actual behavior?

After clicking on a menu item drawer is still open and the user should click somewhere else to close it.

**Comment by trimox** [comment]
@rubenochiavone Thanks for reporting, and the PR!
