### ISSUE TITLE
internal dependencies on MdcRippleModule

### ISSUE THREAD

**Issue by rapropos** [trimox/angular-mdc-web#164]
Several components (textfield was what bit me) rely on having an `EventRegistry` provided. If one is importing individual component modules, a rather cryptic (for me, at least) error will ensue saying there is no provider for `EventRegistry`. I see that `MdcRippleModule` declares this provider, so one way to avoid the problem is to include it in the app module. Perhaps simply documenting this in a FAQ is the best approach, or maybe importing `MdcRippleModule` in `MdcTextfieldModule` *et al* would be preferable. My primary concern with doing things that way would be potential code duplication.

**Comment by trimox** [comment]
Thanks for reporting on your initial usage, and I've updated the [getting-started guide](https://github.com/trimox/angular-mdc-web/blob/master/docs/getting-started.md). 
Keeping this issue open to research options.

**Comment by trimox** [comment]
Got this figured out today. PR incoming
