### ISSUE TITLE
Icon's vertical alignment in navbar

### ISSUE THREAD

**Issue by Extarys** [trimox/angular-mdc-web#167]
Basic code: https://gist.github.com/Extarys/cba6618f4c76de8733d3ab222de51ec0
Result:
![alignmentmaterial](https://user-images.githubusercontent.com/11581433/30356753-cb6f0946-9808-11e7-9b3b-a376eb93493d.png)

I also notice the same issue in the demo website where the right github icon isnt aligned properly and the drawer icon on the left have the same issue.

They appear a little bit too high, not centered.

EDIT: This issue is also present in material-components-web, I opened an issue there.

**Comment by trimox** [comment]
@Extarys What browser/platform are you seeing this condition?

**Comment by Extarys** [comment]
Wow sorry I forgot such info.

Both **Firefox 55.0.2 x64** and **Firefox Nightly 57.0a1 x64** on **Linux Mint 18.2** (Fully up to date)
Also, Angular Apps in general doesn't open in Midori buit that's an issue for them. (Just a general FIY)

**Comment by trimox** [comment]
@Extarys I also duplicated the issue with a SauceLabs test. It's a Firefox style issue in MDC.

![image](https://user-images.githubusercontent.com/11887843/30483022-4ffd5fc8-99f3-11e7-8886-de1ca4771f3c.png)

Thanks for filing the issue with material-components-web!
Closing this one.

**Comment by cpru2** [comment]
Just curious — is there a fix for this?
