### ISSUE TITLE
Opening persistant drawer with the Toolbar menu

### ISSUE THREAD

**Issue by Extarys** [trimox/angular-mdc-web#168]
Sorry if this sound stupid but how can I open a Persistent Drawer with the "drawer" button on the toolbar?

I cannot find the answer on the demo page.

Cheers!

**Comment by trimox** [comment]
Add a `(click)` event to your toolbar button:
```html
<button mdc-toolbar-icon-menu material-icon (click)="onMenuClick();">menu</button>
```

Add a reference variable to your `mdc-persistent-drawer` html
```html
<mdc-persistent-drawer #drawer>
```

Add an import of the `MdcPersistentDrawerComponent` to your component file:
```ts
import { MdcPersistentDrawerComponent } from '@angular-mdc/web';
```

Add Angular `@ViewChild` property
```ts
@ViewChild('drawer') drawer: MdcPersistentDrawerComponent;
```

Add menu click method:
```ts
onMenuClick() {
    !this.drawer.isOpen() ? this.drawer.open() : this.drawer.close();
  }
```

Please also check out the demo-app source:
https://github.com/trimox/angular-mdc-web/tree/master/src/demo-app/components/drawer-demo

**Comment by trimox** [comment]
I noticed Drawer API documentation is missing the available methods for each component. I'll update asap

**Comment by Extarys** [comment]
Thanks for confirming that I'm not crazy :)

Thanks for the code - and thanks for aways being around

**Comment by trimox** [comment]
Not a problem! Closing with PR #169
