### ISSUE TITLE
Add viewBox to SVGs in icon-registry

### ISSUE THREAD

**Issue by ofekashery** [trimox/angular-mdc-web#1681]

**Comment by trimox** [comment]
Hey @ofekashery, could you provide details for this use case (e.g.: how you'd expect to use it)? I'm happy to investigate adding.

**Comment by ofekashery** [comment]
If I add my icons(for ex. [mdi.svg](https://materialdesignicons.com/api/download/angularmaterial/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B)), it does not set [here](https://github.com/trimox/angular-mdc-web/blob/0a7f362fbc4122dcb7084165bc9a9f97068b5db3/packages/icon/icon-registry.ts#L509) the ``viewBox``.
Then, I cannot change the size of the icon because it cuts it instead of resizing:

Without ``viewBox``:
![image](https://user-images.githubusercontent.com/16443111/51088785-bc071b80-176c-11e9-8dd6-07abc0eebef7.png)

With ``viewBox``:
![image](https://user-images.githubusercontent.com/16443111/51088779-a7c31e80-176c-11e9-8fa9-b0d6fb5b4c5b.png)

**Comment by trimox** [comment]
Gotcha. We should be able to preserve `viewbox` in `_toSvgElement`. Will try this out.
