### ISSUE TITLE
The selected tab does not reposition itself to become fully visible on screen.

### ISSUE THREAD

**Issue by chandanamadu** [trimox/angular-mdc-web#1685]
### What are the steps to reproduce the bug?
1 .Go to this link
https://stackblitz.com/edit/angular-mdc-tabs?embed=1&file=app/app.component.html&view=editor
2. In Dynamic Tabs section, by clicking on ADD TAB button, add more than 10 tabs.
3. Click on the 3rd Tab.
4. Now visible area of the tab we can't see the selected tab. It has moved to left side.

**Comment by trimox** [comment]
Duplicated. I thought I had this resolved in v0.43.0, but it's still there. Investigating, let ya know.

**Comment by trimox** [comment]
@chandanamadu Resolved. PR incoming.

**Comment by trimox** [comment]
It's available now in v0.43.3

https://github.com/trimox/angular-mdc-web/releases

**Comment by chandanamadu** [comment]
@trimox  Thanks a lot. In  v0.43.3 it is working fine. 🥇
