### ISSUE TITLE
Enhanced select API problems

### ISSUE THREAD

**Issue by mistoll** [trimox/angular-mdc-web#1686]
version: 0.43.0
browser: firefox
os: ubuntu xenial

In enhanced mode the select component API does not work as expected. Use this template to reproduce:
```
<mdc-select #mySelect>
  <mdc-menu>
    <mdc-list>
      <mdc-list-item value="v1">First</mdc-list-item>
      <mdc-list-item value="v2">Second</mdc-list-item>
    </mdc-list>
  </mdc-menu>
</mdc-select>
<button (click)="mySelect.setSelectionByValue('v2')">Select value 2</button>
<button (click)="mySelect.setSelectedIndex(1)">Select index 1</button>
```
The button "Select value 2" does not work at all. The button "Select index 1" doesn not work after the other button was clicked. After a value was selected the buttons dont't work at all.

I expect both buttons to select the item "Second" no matter what happened before.

### More Information:

Tried ngModel for selecting, which didn't work. 

Tried an additional hidden input, but didn't work. From https://github.com/material-components/material-components-web/tree/master/packages/mdc-select:
> If you are using the enhanced select within an HTML form, you can include a hidden <input> element under the root mdc-select element, and it will be synchronized when the value is updated via user interaction or programmatically.

**Comment by trimox** [comment]
This is resolved, but dependent upon PR #1690 being merged first.

**Comment by trimox** [comment]
Published. Please let me know if I've missed anything.

**Comment by mistoll** [comment]
Works. Thanks for the quick solution.
