### ISSUE TITLE
Add the ability to turn off the singleSelection in Drawer

### ISSUE THREAD

**Issue by ofekashery** [trimox/angular-mdc-web#1692]

**Comment by trimox** [comment]
This has been a bit tricky to avoid a breaking change. Let ya know.

**Comment by trimox** [comment]
@ofekashery Got it working, without breaking changes. PR incoming

You'll simply make the decision for turning off `singleSelection` on the `mdc-list` as normal.

```html
<mdc-list [singleSelection]="false">
```
