### ISSUE TITLE
mdc-toolbar waterfall issue

### ISSUE THREAD

**Issue by pvamshi** [trimox/angular-mdc-web#17]
I have HTML like this : 

```HTML
<mdc-toolbar
  [flexible]="true"
  [fixed]="true"
  [waterfall]="true"
  [fixedLastrow]="false"
  [flexibleTitle]="true">
  <mdc-toolbar-row>
    <mdc-toolbar-section [alignStart]="true">
      <a href="#" class="material-icons mdc-toolbar__icon--menu">menu</a>
      <mdc-toolbar-title>Title</mdc-toolbar-title>
    </mdc-toolbar-section>
    <mdc-toolbar-section [alignEnd]="true">
      <a href="#" class="material-icons mdc-toolbar__icon" alt="Download">file_download</a>
      <a href="#" class="material-icons mdc-toolbar__icon" alt="Print page">print</a>
      <a href="#" class="material-icons mdc-toolbar__icon" alt="Bookmark page">bookmark</a>
    </mdc-toolbar-section>
  </mdc-toolbar-row>
</mdc-toolbar>
```
I am expecting it to behave like this : 
https://material-components-web.appspot.com/toolbar/waterfall-flexible-toolbar.html

But this is what happening. 

![](https://media.giphy.com/media/vFqxwUk9BopSo/giphy.gif)

I plan to heavily invest my time here. I will try to understand why this is happening. But just keeping you in loop.

**Comment by pvamshi** [comment]
We need to add a class to the main window below the toolbar to make it functional. 
```HTML
<main class="mdc-toolbar-fixed-adjust">
  <p class="demo-paragraph">
    A demo paragraph here.
  </p>
</main>
```
Is this handled in any other component or do we expect the end user to be aware of this  ?

**Comment by trimox** [comment]
Good catch! I need to describe the 'mdc-toolbar-fixed-adjust' in the documentation.

**Comment by trimox** [comment]
Decided to compose a `mdc-toolbar-fixed-adjust` directive. I'll have the directive and the documentation updated later today. 
Thanks again!
