### ISSUE TITLE
Animation for toolbar (icon-only button) and menu

### ISSUE THREAD

**Issue by Extarys** [trimox/angular-mdc-web#171]
I noticed that there is no round or icon-only button that can be used for the toolbar. Material apps have an button animation when you press the icon to display the drawer. It also would be useful for other toolbar icons to have an icon-only button. (Like a [fab](https://trimox.github.io/angular-mdc-web/#/fab-demo) without being a fab)

Also, does the [menu](https://trimox.github.io/angular-mdc-web/#/menu-demo)'s links (li) are supposed to be animated when you click/press them? I think it supposed to gradually become gray with a ripple where you pressed)

**Comment by trimox** [comment]
@Extarys All good points. 
For the toolbar comments, check out material-components-web's open issue [Make toolbar actions (icons) have state modifiers](https://github.com/material-components/material-components-web/issues/993). I believe that's close to what you've described.

So, regarding menu-item ripples. Ripples are not a referenced behavior of menus in Material Design guidelines; my opinion there is nothing wrong with adapting ripples to menu link selection for unique use cases. We could research adding an new property to `menu` allowing developers to enable ripples. Thoughts?

**Comment by Extarys** [comment]
didn't saw that one, good.

Not necessarily ripples but maybe a fade-in gray background as a feedback effect?

(Sorry for my short thoughts, just switch keyboard to Colemak)

**Comment by trimox** [comment]
@Extarys optional fade-in gray is available in next release by adding a `[mdc-surface]` directive to `mdc-menu-item`

**Comment by Extarys** [comment]
Awesome thanks for your help!
