### ISSUE TITLE
Wrong checkbox size in lists [Visual]

### ISSUE THREAD

**Issue by Extarys** [trimox/angular-mdc-web#172]
On [lists](https://trimox.github.io/angular-mdc-web/#/list-demo) the icon of the checkbox is higher than large, not a perfect square: 
![image](https://user-images.githubusercontent.com/11581433/30381715-3494f37e-986b-11e7-9e2b-898659bda1d3.png)

Original [checkbox](https://trimox.github.io/angular-mdc-web/#/checkbox-demo): 
![image](https://user-images.githubusercontent.com/11581433/30381737-4592f342-986b-11e7-89cb-494a1d1d8e7c.png)

Also, would it be possible to trigger the action (toggle, check the checkbox) on the whole list item also? Maybe as an option?

PS: Is it ok that I report all those things? I don't want to be a pain in the...

EDIT:
Both Firefox 55.0.2 x64 and Firefox Nightly 57.0a1 x64 on Linux Mint 18.2 (Fully up to date)

Chromium 60.0.3112.113 x64 _appears_ to be ok.

**Comment by trimox** [comment]
Hey @Extarys Definitely feel free to report issues or post questions. This appears to be a styling issue with Firefox and list height. I'll run a SauceLabs test tomorrow to be sure

**Comment by trimox** [comment]
Resolved this, PR soon.
