### ISSUE TITLE
Text Field: Reactive Forms control value not updated when auto filling using LastPass

### ISSUE THREAD

**Issue by ddaspit** [trimox/angular-mdc-web#1724]
### What Angular MDC version are you using?
0.43.2
### What browser(s) is this bug affecting?
Chrome 71
### What OS are you using?
Windows 10
### What are the steps to reproduce the bug?
This can be reproduced using the "Reactive Form" example in the [documentation](https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/text-field-demo/examples).
- Install LastPass extension.
- Setup the example page in LastPass to auto fill the "Username" field.
- Auto fill "Username" field using LastPass.
### What is the expected behavior?
The username value should be equal to whatever value was autofilled.
### What is the actual behavior?
The username value is `null`.
### Any other information you believe would be useful?
I investigated this issue to determine the cause. This seems to be occurring because LastPass fires a "change" event. The "change" event is handled by the `MdcTextField.onChange()` method. This method calls `setValue()` without setting the `isUserInput` parameter to `true`, so `_onChange()` is not called, which is the callback function for the Reactive Forms control.

This issue might also affect Chrome auto filling as well as other auto filling extensions.

**Comment by trimox** [comment]
@ddaspit Thanks for reporting, and the investigative work! 💎 

Working on a PR for this, and also resolving Chrome autofill background color overtaking the outlined box.

**Comment by ddaspit** [comment]
Thank you for the quick response.
