### ISSUE TITLE
disabled item in mdc-select element is selectable

### ISSUE THREAD

**Issue by mohammadrafigh** [trimox/angular-mdc-web#1727]
### What Angular MDC version are you using?
0.43.2
### What browser(s) is this bug affecting?
all
### What OS are you using?
Linux Ubuntu
### What are the steps to reproduce the bug?
just try to select e disabled item in mdc-select (not native one).
### What is the expected behavior?
the item shouldn't be selectable.
### What is the actual behavior?
the item is selectable.
### Any other information you believe would be useful?
you can see this behavior in examples too (Custom Enhanced example).

**Comment by trimox** [comment]
@mohammadrafigh Thanks again for reporting this! Taking a look

**Comment by trimox** [comment]
@mohammadrafigh Got it figured out, but first submitting PRs to improve event handling to make this easier to fix.

**Comment by trimox** [comment]
All set. PR incoming
