### ISSUE TITLE
disabled mdc-text-field allows typing when it's focused

### ISSUE THREAD

**Issue by mohammadrafigh** [trimox/angular-mdc-web#1728]
### What Angular MDC version are you using?
0.43.2
### What browser(s) is this bug affecting?
all
### What OS are you using?
Linux Ubuntu
### What are the steps to reproduce the bug?
1. try to disable a mdc-text-field when it's focused
2. you can still change the text inside it
### What is the expected behavior?
the field should loose the focus and prevents editing its content.
### What is the actual behavior?
the field remains focused and editable.

**Comment by trimox** [comment]
@mohammadrafigh Good catch! Taking care of this now.
