### ISSUE TITLE
Super awesome lists in material-components [Question]

### ISSUE THREAD

**Issue by Extarys** [trimox/angular-mdc-web#173]
Material-components-web have [very beautiful lists](https://material-components-web.appspot.com/list.html) compared to angular version.

I know this project is young, so I'm guessing right now you implement all components and eventually work on details like animations, etc so a simple update will make everything super awesome for everyone who's using this library? :D

**Comment by trimox** [comment]
You got it. The WIP theming component will help us extend the MDC styling.

**Comment by Extarys** [comment]
Gotcha ;) awesome.
