### ISSUE TITLE
Prefilled Select is set as dirty

### ISSUE THREAD

**Issue by einarstubhaug** [trimox/angular-mdc-web#1739]
### What Angular MDC version are you using?
0.43.2
### What browser(s) is this bug affecting?
Chrome
### What OS are you using?
Mac Mojave
### What are the steps to reproduce the bug?
https://stackblitz.com/edit/angular-zrmyyr?file=src%2Fapp%2Fapp.component.ts
### What is the expected behavior?
The form should not be considered dirty
### What is the actual behavior?
The mdc-select element has css-class ng-dirty
### Any other information you believe would be useful?
Earlier issue: https://github.com/trimox/angular-mdc-web/issues/733

**Comment by trimox** [comment]
@einarstubhaug Thanks for reporting this! Looking into this now.
