### ISSUE TITLE
default button type

### ISSUE THREAD

**Issue by rapropos** [trimox/angular-mdc-web#174]
This is another awkward one where I'm not sure if this is (a) intended behavior and/or (b) something that needs to be decided upstream, but mdc-buttons are inconsistent with vanilla HTML buttons when it comes to the default type. If no explicit `type` attribute is provided, ordinary HTML buttons are of type `submit`. mdc-buttons seem to default to type `button` instead, which causes confusion when porting pre-existing forms.

**Comment by trimox** [comment]
@rapropos Good catch! Default value on `type` should not be set. 

If you'd like to submit a PR to fix.
- [ ] Remove the `Input() type: string;` line
- [ ] Remove the `HostBinding('attr.type')`
- [ ] Update documentation
