### ISSUE TITLE
Enhanced mdc-select menu does not stay open on touch. 

### ISSUE THREAD

**Issue by Jordan-Amanda** [trimox/angular-mdc-web#1762]
**Describe the bug**
in the enhanced mdc-select menu does not handle touch taps. Like on android devices. it treats them like a double click so the mdc-menu only opens for fraction of a second then closes and does not remain open. 

**To Reproduce**
1. Go to 'https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/select-demo/examples'
2. Press 'F12' to open up chromes inspect menu. 
3. Click on 'Toggle device Toolbar' looks like: 
![image](https://user-images.githubusercontent.com/28954704/51569609-77f9d200-1e62-11e9-89f4-e107132aec2c.png)
this should make your cursor a touch dot instead of a mouse cursor. 
4. Scroll down to the 'Enhanced Select'
5. Click on the word 'Fruit*' in the select
5. See error 

**Expected behavior**
Option Menu should stay open and let the user select other options in the menu, without closing right away. 

**Screenshots**

**What Angular MDC version are you using?** 0.43.4

**What OS are you using?:** Android and chrome. 

**What browser(s) is this bug affecting?:** chrome and apps on android devices. 

**Additional context**

**Comment by trimox** [comment]
@Jordan-Amanda Thanks for reporting this! 

Also, found related issue upstream https://github.com/material-components/material-components-web/issues/4173

Will investigate and let ya know.

**Comment by trimox** [comment]
Planning to remove `touchstart` from select, at least until resolved upstream.
