### ISSUE TITLE
RTL in outlined textfield label doesn't look good

### ISSUE THREAD

**Issue by ofekashery** [trimox/angular-mdc-web#1763]
**Screenshots**
![image](https://user-images.githubusercontent.com/16443111/51612408-1309af00-1f2a-11e9-8790-8c9d208fac79.png)

**What Angular MDC version are you using?**
0.43.3

It seems that this RTL style missing

**Comment by trimox** [comment]
Closing. If it's still a problem, please re-open with code example.
