### ISSUE TITLE
dialog: afterClosed subscription not always in angular zone

### ISSUE THREAD

**Issue by kkla320** [trimox/angular-mdc-web#1764]
**Describe the bug**
When subscribing to the afterClosed observable from the DialogRef, changes done in the subscription are not in the angular zone. See this [example](https://stackblitz.com/edit/angular-mdc-dialog-ujc9c7) on StackBlitz.

**Describe the solution you'd like**

**To Reproduce**
1. Go to 'https://angular-mdc-dialog-ujc9c7.stackblitz.io/'
2. Wait a few seconds for the dialog to appear.
3. Press 'escape' to dismiss the dialog and wait a few seconds.
4. The component is updating properly.
5. Reload the page and repeat the steps 1 and 2
6. Now dismiss the dialog with a click outside, the enter button or with a click on the dialog button
7. The component is not updating properly.

**Expected behavior**
The subscription of the afterClosed event should always be inside the angular zone.

**What Angular MDC version are you using?**
v0.42.0

**What OS are you using?:**
WIndows 10 Enterprise Version 1803

**What browser(s) is this bug affecting?:**
Tested Chrome Version 71.0.3578.9

**Comment by trimox** [comment]
@kkla320 Nice catch. Thanks for the StackBlitz reproduction, and PR! 💎
