### ISSUE TITLE
mdc-select placeholder does not float with patchValue

### ISSUE THREAD

**Issue by daniloarcidiacono** [trimox/angular-mdc-web#1766]
**Describe the bug**
When `mdc-select` options are populated dynamically (for example, with data fetched from an external service), **and** the form value is updated with `patchValue`, the placeholder does not float.

**To Reproduce**
I've created a [Stackblitz](https://stackblitz.com/edit/angular-mdc-select-star-bug).
The steps to reproduce the behavior are included in the HTML.

**Expected behavior**
The placeholder should float when using `patchValue`.

**What Angular MDC version are you using?**
0.43.3

**Comment by trimox** [comment]
PR incoming. Added `ContentChild` to watch for changes, and floating label; if necessary.

**Comment by trimox** [comment]
Also, adding lazy loaded example to documentation.

**Comment by daniloarcidiacono** [comment]
Hello @trimox, 
I've tested the latest release (0.43.5) and this bug has been solved.
However, a more subtle problem still remains when using the outlined version of mdc-select.

![image](https://user-images.githubusercontent.com/17272323/51790487-57998280-2196-11e9-9728-5dbe8781479c.png)

If a placeholder is set, the label floats (after the data is lazy loaded) but it appears behind the mdc-select-outline. On the other hand, if no placeholder is set, the "*" sign should disappear instead of floating (as it already does when the user interacts with the component).

I've forked my original StackBlitz to show this [bug](https://stackblitz.com/edit/angular-mdc-select-star-bug-np2epu).

Thanks

**Comment by trimox** [comment]
@daniloarcidiacono Thanks! Taking a look, `outlined` boxes will need another layout check.

**Comment by daniloarcidiacono** [comment]
Hi @trimox, sorry for being pedantic here but the latest release 0.43.6 only solves the case when a placeholder is set. :(

**Comment by trimox** [comment]
@daniloarcidiacono No worries! Gotta admit, I haven't heard "pedantic" used in a looooong time 👍 

My testing used a placeholder, but I see what ya mean on the demo site. Let ya know!

**Comment by trimox** [comment]
@daniloarcidiacono What ya think? Reason it wasn't working was due to the label having no width. I added logic to also look for the required flag.

![sample](https://user-images.githubusercontent.com/11887843/51873936-01127c80-232d-11e9-893c-5314aebc830a.gif)

**Comment by daniloarcidiacono** [comment]
It looks good to me! 👍
