### ISSUE TITLE
text-field: dense does not shrink the height

### ISSUE THREAD

**Issue by rlarik** [trimox/angular-mdc-web#1775]
**Describe the bug**
Adding dense to a text-field shrinks the font-size but not the height of the field.

**To Reproduce**
1. Add a text-field
2. Add the dense option to it

> https://stackblitz.com/edit/angular-mdc-ewsdjt

**Expected behavior**
According to the documentation, dense should reduce font-size (works) and the height (does not work):
dense: boolean | Shrinks the font size and height of the input.

**What Angular MDC version are you using?**
0.43.4

**What OS are you using?:**
Windows

**What browser(s) is this bug affecting?:**
Tried Firefox and Chrome although the height is simply not changed.

**Comment by trimox** [comment]
Hey @rlarik I've been following a couple upstream issues regarding this.
reference: https://github.com/material-components/material-components-web/issues/4164
reference: https://github.com/material-components/material-components-web/issues/4142

We'll incorporate any changes once a revised density specification is made available in [material-components-web](https://github.com/material-components/material-components-web).
