### ISSUE TITLE
slider: Min and Max fail to set in view

### ISSUE THREAD

**Issue by asntcrz** [trimox/angular-mdc-web#1776]
**Describe the bug**
Properties max and min are not set into the slider. Value does set properly.

**To Reproduce**
1. add slider:
`<mdc-slider discrete [min]="[min]" [max]="[max]" [value]="[value]"></mdc-slider>`
2. set properties in controller:
```
max: number = 50;
min: number = 10;
value: number = 25;
```
3. render and observe how max is 100 and min 0, value is 25 though.

> We also have a [template on StackBlitz](https://stackblitz.com/edit/angular-mdc) which we encourage you to use to create a reproduction of the issue. The less time it takes for us to reproduce the issue, the less time it takes to verify and fix it!

**Expected behavior**
Adding properties of max or min should render the slider with those values.

**Screenshots**
https://stackblitz.com/edit/angular-mdc-lye9vb

**What Angular MDC version are you using?**
"@angular-mdc/web": "^0.43.5",

**What OS are you using?:**
Ubuntu, but also in stackblitz template

**What browser(s) is this bug affecting?:**
Chrome

**Comment by asntcrz** [comment]
Thanks for great job!

**Comment by trimox** [comment]
@asntcrz Thank you!! Thanks for reporting this! Tackling it next.

**Comment by trimox** [comment]
PR incoming. Will be released with v0.43.6.
