### ISSUE TITLE
Add value input to chips

### ISSUE THREAD

**Issue by micahwood** [trimox/angular-mdc-web#1788]
**Is your feature request related to a problem? Please describe.**
When working with filter or choice chips, there doesn't seem to be any way to assign a value to each chip, so when the change event is fired all you get is an autogenerated id and no easy way to determine what the value of the chip that was added or removed is.

**Describe the solution you'd like**
Create an `Input()` for `value` on `MdcChip` and emit that on `selectionChange` for both the chip and the chip set `change` event.

**Describe alternatives you've considered**
I tried looking through the source code to see if there was any way to assign a value to a chip currently but could not see anything.

**Comment by trimox** [comment]
@micahwood Thanks for the feature request. We'll add `value`, and default to `textContent` unless overridden by user.

**Comment by trimox** [comment]
@micahwood All set. Merging PR in a few, and it'll be made available in v0.44.0.

**Comment by trimox** [comment]
Adds `FormControl`, `ngModel` and `value` support.

* Add `value` property on `mdc-chip` and `mdc-chip-set`
* Improve `click` and `keydown` logic
* Refactored template bindings
* Fix filter chip checkmark animation
* Add custom chip examples

**Comment by micahwood** [comment]
Wow thanks for the super quick turnaround on that!
