### ISSUE TITLE
Support "default options" for form fields

### ISSUE THREAD

**Issue by kctang** [trimox/angular-mdc-web#1798]
Requesting for a feature similar to what [MAT_FORM_FIELD_DEFAULT_OPTIONS](https://material.angular.io/components/form-field/api#MatFormFieldDefaultOptions) provides in Angular Material.

Basically, a mechanism to inject default form field behaviors like outline, dense and fullwidth (and any other that make sense).

Why I think this is useful: In projects with multiple developers (or large codebase), we do not need to remind developers how to style form fields. Just leave it as default and let the application inject default behavior.

**Comment by trimox** [comment]
@kctang definitely a great feature request. Adding to the next milestone!
