### ISSUE TITLE
select: inconsistent invalid styling for required attribute and reactive form validator

### ISSUE THREAD

**Issue by mrp67** [trimox/angular-mdc-web#1812]
**Describe the bug**
Native select menus configured with Validators.required turn red immediately after clicking them. When configured with the required attribute, the select does not turn red until blurred. Seems like the bug is on the select configured with the reactive form since selects did not always turn red immediately.

**To Reproduce**
1. Go to the [Native Select - Leading Icon select example](https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/select-demo/examples) 
2. Click the select menu. Color will be the primary focused color and label will be still be floated (should it still be floated at this point? possibly a separate bug?)
3. Click once outside without selecting an option (should still be the primary color)
4. Click again and it should finally turn red/invalid

5. Go to the [Select with FormControl](https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/select-demo/examples) 
6. Click the select menu. Color will immediately turn red
7. Click once outside and label will be floated and select still red
8. Click again and label will no longer be floated, but color is still red/invalid

**Expected behavior**
Validity styling should be consistent between select configured with reactive form validity and select configured with required attribute. The correct behavior would be that of the select configured with the required attribute

**Screenshots**
Select with required attribute after clicking on it and clicking outside of it once (remains primary color):
![image](https://user-images.githubusercontent.com/10659955/52305136-61737080-2962-11e9-9613-288277120e71.png)

Select with reactive form control required immediately after clicking on it (turns red):
![image](https://user-images.githubusercontent.com/10659955/52305244-ab5c5680-2962-11e9-8e2d-9b712b473746.png)

**What Angular MDC version are you using?**
0.43.7

**What OS are you using?:**
MacOS Mojave

**What browser(s) is this bug affecting?:**
Chrome

**Comment by trimox** [comment]
@mrp67 Thanks for reporting this! 

Adding this to v0.44.1 milestone.

**Comment by trimox** [comment]
PR incoming
