### ISSUE TITLE
Click on a checkbox label with an id attribute does not change the value.

### ISSUE THREAD

**Issue by noudenaa** [trimox/angular-mdc-web#1818]
**Describe the bug**
Specifying an "id" attribute for a mdc-checkbox results in wrong label click behavior. Clicking the label shows a ripple effect on the checkbox, but does not change the value.

Reproduce:
See https://angular-mdc-fie2zw.stackblitz.io

```
  <mdc-form-field>
    <mdc-checkbox id="checkbox1"></mdc-checkbox>
    <label>Checkbox label</label>
  </mdc-form-field>
```

Results in:

```
<mdc-form-field class="mdc-form-field">
  <mdc-checkbox class="mdc-checkbox mdc-checkbox--upgraded mdc-ripple-upgraded mdc-ripple-upgraded--unbounded" id="checkbox1" ng-reflect-id="checkbox1" style="--mdc-ripple-fg-size:24px; --mdc-ripple-fg-scale:1.66667; --mdc-ripple-left:5px; --mdc-ripple-top:8px;">
  <input class="mdc-checkbox__native-control" type="checkbox" id="checkbox1-input" tabindex="0"> 
...
  </mdc-checkbox>
  <label for="mdc-checkbox-6-input">Checkbox label</label>
</mdc-form-field>
```

Where the generated label "for" attribute is different than the generated input "id" attribute.
When specifying no "id" attribute for the checkbox, the generated attribute values are equal and clicking the label changes the value. 

**Expected behavior**
Clicking the label should change the value of the checkbox.

**What Angular MDC version are you using?**
0.43.7

**What OS are you using?:**

**What browser(s) is this bug affecting?:**
All

**Additional context**
I think the radio button has the same behavior (with an "id" attribute, clicking the label doesn't select the item).

**Comment by trimox** [comment]
@noudenaa Thanks for reporting this, and sorry for the delay!

All set, PR incoming.

**Comment by noudenaa** [comment]
Thanks, this change also solves clicking the label for the radio and switch components when they have an "id" attribute!
