### ISSUE TITLE
Missing Favicon

### ISSUE THREAD

**Issue by MrGrigri** [trimox/angular-mdc-web#1819]
I'm not sure if this is the right repo for the website, but this is all I could find on that.

**Describe the bug**
The server responds with a 404 on chrome for the `favicon.png`.

**To Reproduce**
1. Go to the [home page](https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/home)
2. Notice there is no favicon

**Expected behavior**

There should be a favicon

**Screenshots**
![image](https://user-images.githubusercontent.com/4528551/52803163-b5571700-303e-11e9-80a7-98ec8dec022f.png)

![image](https://user-images.githubusercontent.com/4528551/52803384-30203200-303f-11e9-8e25-173aeb5cc2e2.png)

**Comment by trimox** [comment]
@MrGrigri Thanks! Next update will resolve.
