### ISSUE TITLE
mdc-select closes immediately

### ISSUE THREAD

**Issue by mohammadrafigh** [trimox/angular-mdc-web#1820]
**Describe the bug**
in "Enhanced Select" example the menu closes immediately. this also happens in my code.

**To Reproduce**
1. Go to https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/select-demo/examples
2. Click on Enhanced Select

**Expected behavior**
the menu should stay opened.

**Screenshots**
![peek 2019-02-15 22-54](https://user-images.githubusercontent.com/6737508/52879895-ab83ff80-3175-11e9-9567-d89db969f246.gif)

**What Angular MDC version are you using?**
0.43.7
**What OS are you using?:**
Ubuntu
**What browser(s) is this bug affecting?:**
Firefox

**Comment by mohammadrafigh** [comment]
I noticed that this happens mainly when I use the touchpad of my laptop.

**Comment by trimox** [comment]
Hey all, this was resolved upstream. Will be made available in next update.
https://github.com/material-components/material-components-web/commit/8286aa7321dc9fbd531ca4648e08fb141dc81d33
