### ISSUE TITLE
mdc-chip-set choice binding with ngModel

### ISSUE THREAD

**Issue by mohammadrafigh** [trimox/angular-mdc-web#1823]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
there is no way to bind mdc-chip-set choice selection to a model.

**Describe alternatives you've considered**
for now I can bind from view to model using selectionChange event. but there is no way to bind from model to view since "select" function just selects 1 chip and deselects others. also I think there should be a way to set a [value] for each chip this may help to bind from model to view.

**Additional context**
I'm using mdc-chip-set to implement a multi select component to use in place of multi select component in Angular Material 1.

**Comment by trimox** [comment]
@mohammadrafigh Value binding is now available in v0.44.0. Just released a few minutes ago 😄

**Comment by mohammadrafigh** [comment]
@trimox at first thanks for your great support. the ngModel is not applicable to multi select choices, actually multiselect choice is broken in examples too.

**Comment by trimox** [comment]
@mohammadrafigh Thanks!

Material Design specs https://material.io/design/components/chips.html#choice-chips refer to choice chips as meant for single selection. Are you referring to filter chips by chance? 

I'll add a filter chip variant example binding to an array to confirm multiple selection support is working.

**Comment by mohammadrafigh** [comment]
Oh ok. So that was my fault. Albeit I'm still able to use choice in the way
I said before. The choice UI is much more nice in my case.
