### ISSUE TITLE
Text Field Character Counter Breaks When Helper Text Element Is Passed Through ng-content

### ISSUE THREAD

**Issue by mrp67** [trimox/angular-mdc-web#1828]
**Describe the bug**
When creating a wrapper component around the text field and passing in the helper text element through ng-content, the text field fails to initialize the character counter. 
See StackBlitz example below for more details...

The text field's init function is called in ngAfterViewInit. At that point in the component's lifecycle, the transcluded content will not exist. Calling init in ngAfterContentInit or adding an additional check there should fix this issue.

**To Reproduce**
1. Go to [StackBlitz Example](https://stackblitz.com/edit/angular-mdc-rhss17)
2. Normal and transcluded examples should be visible in code panel (normalField and contentField)
3. In the console, there will be an error: ERROR TypeError: Cannot read property 'getDefaultFoundation' of undefined
4. Textfield labeled as Normal will have a character counter, but the one labeled as Content will not due to the error

**Expected behavior**
Both text fields should have a working character counter.

**What Angular MDC version are you using?**
0.44.0

**What OS are you using?:**
Mac OS

**What browser(s) is this bug affecting?:**
Chrome

**Comment by trimox** [comment]
@mrp67 Thanks for reporting this! Adding to the v0.44.1 milestone.
