### ISSUE TITLE
mdc-select emits selectionChange on initial value

### ISSUE THREAD

**Issue by mohammadrafigh** [trimox/angular-mdc-web#1829]
**Describe the bug**
mdc-select now prevents calling ng-dirty for initial value but it still emits selectionChange.

**To Reproduce**
1. Create a mdc-select component
2. Bind it to a model using [(ngModel)] where the model has an initial value
3. Set a log for selectionChange
4. You can see it's emitting on initialization

**Expected behavior**
 I think mdc-select shouldn't emit selectionChange for initial value.

**What Angular MDC version are you using?**
0.44

**What OS are you using?:**
Ubuntu

**What browser(s) is this bug affecting?:**
Firefox and maybe others

**Comment by mohammadrafigh** [comment]
also it's called before the value reflects to ngModel (I think it's not an intended behavior too).

**Comment by trimox** [comment]
@mohammadrafigh Thanks for reporting this!

I'm finishing up testing, and PR will be available soon.

**Comment by mohammadrafigh** [comment]
@trimox thanks for your efforts but it's not fixed yet... I get 3 calls for selectionChange at initialization step.

**Comment by mohammadrafigh** [comment]
It's fixed in the recent version (5.1.1) thank you
