### ISSUE TITLE
Top Nav Bar appears everytime I scroll up 

### ISSUE THREAD

**Issue by vguleaev** [trimox/angular-mdc-web#1831]
**Describe the bug**
Is it possible to disable app bar instantly appears when you start scroll up. I want it to be shown only at the top fixed. Is it possible?

**To Reproduce**
1. Go to https://angular-mdc-app-bar.stackblitz.io
2. Remove "fixed" from mdc-top-app-bar 
3. Scroll down to very end. Then do sroll up just a little. Not enough to get to the top of the page.
4. See app bar instantly appears.

**Expected behavior**
A possibility to disable this feature. Doesnt appear on scroll up. Unsless you go to the top.

**What Angular MDC version are you using?**
Latest
**What OS are you using?:**
Win 10
**What browser(s) is this bug affecting?:**
Chrome

**Comment by vguleaev** [comment]
No updates? Is it impossible to just get FIXED top navbar without that feature?

**Comment by trimox** [comment]
Yep, reviewing this tomorrow.

**Comment by trimox** [comment]
Looked into this for ya, and feel it's best not to be an edge case here. I'm leery of _future_ breaking changes with `top-app-bar`; the adapters are confusing enough. Feel free to file feature request [upstream](https://github.com/material-components/material-components-web).
