### ISSUE TITLE
Default "checked value" does not work with multiple instances of mdc-radio-group

### ISSUE THREAD

**Issue by kctang** [trimox/angular-mdc-web#1834]
Given this template with two mdc-radio-group:

```
<div>
    <!--first group-->
    <mdc-radio-group>
        <mdc-form-field>
            <!--BUG: will not check if second group is rendered-->
            <mdc-radio [value]="'1'" [checked]="true"></mdc-radio>
            <label>a1</label>
        </mdc-form-field>
        <mdc-form-field>
            <mdc-radio [value]="'2'"></mdc-radio>
            <label>a2</label>
        </mdc-form-field>
    </mdc-radio-group>
    <!--second group-->
    <mdc-radio-group>
        <mdc-form-field>
            <mdc-radio [value]="'1'"></mdc-radio>
            <label>b1</label>
        </mdc-form-field>
        <mdc-form-field>
            <mdc-radio [value]="'2'" [checked]="true"></mdc-radio>
            <label>b2</label>
        </mdc-form-field>
    </mdc-radio-group>
</div>
```

`a1` in the first group is not checked on render. If I remove the second group entirely, then `a1` will be checked on render.

Additional observations:
- Only the last rendered mdc-radio-group's default value will be checked. So, if I have 3 groups, only the last group's value will be checked.
- Once rendered, the groups work as intended (e.g. separate groups).
- Similar behavior when binding with reactive form using `<mdc-radio-group [formControlName]="myField">` (which is my actual use case).

Is this a bug or i'm using `mdc-radio-group` incorrectly?

**Comment by luisquicidev** [comment]
any ideas for the fix? i'm facing this issue on an ionic app and only the last group of a multiple group receive the default value, the other groups don't receive any value.

**Comment by trimox** [comment]
Hey @kctang @luisquicidev Sorry for the delay, I've duplicated internally. I think we need to clear the name from the host node. Working on pushing PR for later today.

**Comment by trimox** [comment]
@kctang @luisquicidev I was right. Turns out `name` is not propagating down to `mdc-radio`. Here's a quick workaround until the next release.

Provide a name to each `mdc-radio`

```html
  <!--first group-->
  <mdc-radio-group>
    <mdc-form-field>
      <!--BUG: will not check if second group is rendered-->
      <mdc-radio name="radio-group-1" [value]="'1'" [checked]="true"></mdc-radio>
      <label>a1</label>
    </mdc-form-field>
    <mdc-form-field>
      <mdc-radio name="radio-group-1" [value]="'2'"></mdc-radio>
      <label>a2</label>
    </mdc-form-field>
  </mdc-radio-group>

  <!--second group-->
  <mdc-radio-group>
    <mdc-form-field>
      <mdc-radio name="radio-group-2" [value]="'1'"></mdc-radio>
      <label>b1</label>
    </mdc-form-field>
    <mdc-form-field>
      <mdc-radio name="radio-group-2" [value]="'2'" [checked]="true"></mdc-radio>
      <label>b2</label>
    </mdc-form-field>
  </mdc-radio-group>
```

**Comment by trimox** [comment]
PR incoming!
