### ISSUE TITLE
mdc-select placeholder overlaps mdc-select-item

### ISSUE THREAD

**Issue by mohammadrafigh** [trimox/angular-mdc-web#1838]
**Describe the bug**
the placeholder of mdc-select overlaps mdc-select-item when the items are rendered using *ngFor.

**To Reproduce**
1. Just make an mdc-select with a mdc-select-item which has an *ngFor directive.
2. Click on an item
3. Loose the mdc-select focus
4. See the placeholder overlaps the item

https://stackblitz.com/edit/angular-mdc-xrwdvr

**Expected behavior**
the placeholder should stay on top of the mdc-select.

**What Angular MDC version are you using?**
0.44
**What OS are you using?:**
Ubuntu
**What browser(s) is this bug affecting?:**
Firefox, Chromium and Opera

**Comment by noskiboots** [comment]
I am experiencing the same issue.

**Comment by trimox** [comment]
@mohammadrafigh @noskiboots Thank you for the StackBlitz! See if I can get this resolved for the 1.x release.

**Comment by trimox** [comment]
I've narrowed this down, and working on a fix. For a quick workaround, add a value to each `mdc-list-item`.

```html
<mdc-select placeholder="choose a fruit" outlined>
  <mdc-menu>
    <mdc-list>
      <mdc-list-item *ngFor="let fruit of fruits" [value]="fruit">{{fruit}}</mdc-list-item>
    </mdc-list>
  </mdc-menu>
</mdc-select>
```

**Comment by mohammadrafigh** [comment]
@trimox thanks for the workaround. but it doesn't work when the value is an object.

**Comment by trimox** [comment]
@mohammadrafigh Yep, pushing some pending `select` fixes today, and can re-focus on handling objects.

**Comment by mohammadrafigh** [comment]
any progress? or any suggestions where should I look into it?
