### ISSUE TITLE
Menu does not work when anchored to a card's action button.

### ISSUE THREAD

**Issue by kctang** [trimox/angular-mdc-web#1839]
Menu does not work when anchored to a card's action button.

If gives this error: `anchorElement.getBoundingClientRect is not a function error`.

You can see the error in this [demo](https://stackblitz.com/edit/angular-mdc-menu-bug?file=src%2Fapp%2Fapp.component.html).

Any workaround to use menu in card's action buttons would be appreciated if a fix cannot be available soon.

Thanks!

**Comment by trimox** [comment]
@kctang Sorry for the delay. Unfortunately, the `material-components-web` implementation is missing this functionality at the moment.

Here is an example for the current implementation,
```html
<div mdcMenuSurfaceAnchor #demoAnchor>
  <button mdcIconButton mdcCardAction="icon" icon="more_vert"
    (click)="demo.open = !demo.open"></button>
  <mdc-menu #demo [anchorElement]="demoAnchor">
    <mdc-list>
      <mdc-list-item>Apple</mdc-list-item>
      <mdc-list-item>Banana</mdc-list-item>
    </mdc-list>
  </mdc-menu>
</div>
```

Please reference upstream issue, 
https://github.com/material-components/material-components-web/issues/4072

**Comment by trimox** [comment]
Adding an example to our documentation page for `mdc-menu`.
