### ISSUE TITLE
mdc-switch keyboard trap

### ISSUE THREAD

**Issue by MrGrigri** [trimox/angular-mdc-web#1846]
**Describe the bug**
`shift + tab` on a keyboard does not go to previous focusable item from an `mdc-switch` component.

**To Reproduce**
1. Go to my [StackBlitz example](https://stackblitz.com/edit/angular-mdc-abyw5g)
2. Follow the instructions at the example.

**Expected behavior**
When focused on the `mdc-switch`, pressing the `shift + tab` on the keyboard should go back in the focus order.

**What Angular MDC version are you using?**
Version 0.44.0

**What OS are you using?:**
Windows 10

**What browser(s) is this bug affecting?:**
Chrome (Version 72.0.3626.121 (Official Build) (64-bit))

**Comment by MrGrigri** [comment]
I believe this bug is happening because you have a `tabindex=0` on the `mdc-switch` component. Once focus is on that component, you direct the focus to the actual `<input/>` element. So if a `shift + tab` is pressed, it just loops back to the native `<input/>`.

**Comment by trimox** [comment]
@MrGrigri Thanks for the investigative work! Pushing this today for ya.

**Comment by MrGrigri** [comment]
Thanks @trimox!
