### ISSUE TITLE
Bottomsheet is not opened

### ISSUE THREAD

**Issue by realgsong** [trimox/angular-mdc-web#1847]
**Describe the bug**
When opening bottomsheet, screen is dimmed with backdrop but bottomsheet is not displayed.

**To Reproduce**
I have no idea to reproduce this bug but it occurs occasionally.

1. Open bottomsheet
2. Whole screen is dimmed

**Expected behavior**
Bottomesheet is displayed correctly.

**What Angular MDC version are you using?**
@angular-mdc/web 0.44.0

**What OS are you using?:**
Android 8.0

**What browser(s) is this bug affecting?:**
Chrome 72.0.3626.121

I'll add more info when I meet this error again. Please let me know if you need any debugging information or logs.

**Comment by trimox** [comment]
Hey @realgsong, there is no bottomsheet component yet?

**Comment by realgsong** [comment]
oops. sorry for wrong reporting. this supposed to be placed in @angular/material. Closing. Thank you @trimox
