### ISSUE TITLE
MDCMenu does not work when target in tsconfig.json is set to 'es6'

### ISSUE THREAD

**Issue by rlanga** [trimox/angular-mdc-web#1848]
In my project's tsconfig.json file, I changed the 'target' property from es5 to es6 to get compatibility while using sets in my code. However, an adverse effect of changing this setting is that when I tried to implement the MDCMenu element, it throws an error saying `ERROR TypeError: Cannot read property 'nativeElement' of undefined` once the page loads and when I click on the button to open the menu component. Secondly nothing happens when I click on the button, no menu pops up and the same error is added to the console output.

1: Open the tsconfig.json file located at the root of the Angular project (at the same directory level as the 'src' folder and 'angular.json') and change the `compilerOptions.target` option from `es5` to `es6`
2. Implement a simple MDCMenu element in any Angular component. I was following the [Selection Group Menu example](https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/menu-demo/examples]) from the angular-mdc-web documentation site.
3. Load up the project and open the page containing the implemented MDCMenu element
4. Open the browser's developer panel and go to the console panel
5. A console error should appear as soon as the page has loaded 

**Expected behavior**
A button should load on the page and when clicked, a menu should pop up displaying a list of menu items.

**What Angular MDC version are you using?**
0.44.0

**What OS are you using?:**
Ubuntu 16.04.1

**What browser(s) is this bug affecting?:**
Tested on Chrome 73.0.3683.86 and Firefox 66.0.1

**Comment by trimox** [comment]
@rlanga Thanks for reporting this.

I believe this due in part to https://github.com/angular/angular/issues/27267

Have you encountered this behavior with any other components? I'll investigate a workaround.

**Comment by mohammadrafigh** [comment]
@trimox I think it's fixed and working with ng8.

**Comment by trimox** [comment]
@mohammadrafigh That's great news! Will try to confirm this weekend before closing.

**Comment by trimox** [comment]
Closing.
