### ISSUE TITLE
undefined bound model in textfield

### ISSUE THREAD

**Issue by rapropos** [trimox/angular-mdc-web#187]
Apologies for creating yet again another annoying issue without really understanding where or how to address it. When a textfield is bound via `[(ngModel)]` to an undefined value, things don't go so well.

```
<mdc-textfield label="label" [(ngModel)]="binding"></mdc-textfield>
binding: string; // no initializer on controller property
```

results in the label being unpopped and overwritten with the unwanted text string "undefined", as seen here:

<img src="http://imgur.com/zNgQ8agl.png" />

Binding uninitialized `FormControl`s does not seem to exhibit this problem. If the bound property is initialized to something, the label at least pops above the field, so I'm guessing this is some sort of disagreement amongst the various implementation bits as to whether various falsy values like `null` or `undefined` constitute "a value being set" or not.

**Comment by trimox** [comment]
On it. Writing test coverage for Text Field and ran into it as well.
