### ISSUE TITLE
text-field doesn't work properly possibly with paper elements and/or angular/material

### ISSUE THREAD

**Issue by sayinserdar** [trimox/angular-mdc-web#1880]
Describe the bug
If I try to use any component other than text field it works just fine but if I want to use text-field component. The styling is not correct. It appears in the HTML file and necessary styling is also available in the console but the displayed component is not styled, I guessed that it was overwritten by another SCSS file. Removed all the components scss files, didn't help. I also tried to isolate the component with excluding modules which I was using. I tried to reinstall all the packages.(https://stackblitz.com/edit/angular-mdc?file=src%2Fapp%2Fmaterial.module.ts) I changed this example's package.json with mine and it works on stackblitz but not mine. Here is my package.json

It's been almost 5 days and I'm about to lose my mind. Thanks in advance :/ 
```
{
  "name": "bw-admin",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "heroku-postbuild": "npm install -g angular-cli"
  },
  "private": true,
  "dependencies": {
    "@angular-mdc/web": "1.0.3",
    "@angular/animations": "^7.0.4",
    "@angular/cdk": "^7.3.4",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/material": "^7.3.4",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "@material/chips": "^1.0.1",
    "@material/textfield": "1.1.1",
    "@material/top-app-bar": "^1.0.1",
    "@ngrx/effects": "^7.3.0",
    "@ngrx/store": "^7.3.0",
    "@ngrx/store-devtools": "7.4.0",
    "@polymer/app-layout": "3.0.2",
    "@polymer/iron-flex-layout": "3.0.1",
    "@polymer/iron-form": "3.0.1",
    "@polymer/iron-icon": "^3.0.1",
    "@polymer/iron-iconset-svg": "^3.0.1",
    "@polymer/iron-input": "3.0.1",
    "@polymer/iron-label": "3.0.1",
    "@polymer/iron-list": "3.0.2",
    "@polymer/iron-swipeable-container": "3.0.1",
    "@polymer/paper-button": "3.0.1",
    "@polymer/paper-card": "^3.0.1",
    "@polymer/paper-checkbox": "3.1.0",
    "@polymer/paper-dialog": "3.0.1",
    "@polymer/paper-dropdown-menu": "3.0.1",
    "@polymer/paper-fab": "^3.0.1",
    "@polymer/paper-icon-button": "^3.0.2",
    "@polymer/paper-input": "3.0.2",
    "@polymer/paper-item": "^3.0.1",
    "@polymer/paper-listbox": "^3.0.1",
    "@polymer/paper-menu-button": "^3.0.1",
    "@polymer/paper-spinner": "3.0.2",
    "@polymer/paper-tabs": "^3.0.1",
    "@polymer/paper-toolbar": "3.0.1",
    "@polymer/paper-tooltip": "3.0.1",
    "@polymer/polymer": "^3.1.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "web-animations-js": "^2.3.1",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.3",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@ngrx/schematics": "7.4.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
}

```

Expected behavior
The styling  according to docs

Screenshots
<img width="423" alt="Screen Shot 2019-04-27 at 19 56 48" src="https://user-images.githubusercontent.com/26919126/56852689-04ff6c00-6927-11e9-98bf-f43884a4ca13.png">

What Angular MDC version are you using?
 "1.0.3"

What OS are you using?:
MacOS Mojave Version 10.14

What browser(s) is this bug affecting?:
Google Chrome Version 75.0.3770.8 (Official Build) 
Firefox Quantum 66.0.3 (64-bit)
Opera Version:58.0.3135.132

Additional context
I also tried to run the same project in a different machine which is also MacbookPro but the result is the same.

**Comment by trimox** [comment]
Hey @sayinserdar, if you have a repo I wouldn't mind reviewing. Can't say I've heard of problems with other libraries.

**Comment by sayinserdar** [comment]
Aaah thanks for your reply. After serious excavation, we have finally found the problem which is not related to any package whatsoever. Apparently, the previous developer has changed the configuration in angular.json. After importing the styling package in the correct path everything has solved.
