### ISSUE TITLE
Black hover background on listitems with checkbox

### ISSUE THREAD

**Issue by Christian-E** [trimox/angular-mdc-web#1881]
**Describe the bug**
When hovering over a list item with a checkbox, the background of the list item gets black. This happens since we updated from 0.43.7 to 1.0.3.
When clicking on the list item or checkbox the background flickers weirdly.

**To Reproduce**
This can be reproduced on the examples page (https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/list-demo/examples) using these examples:
- List with Leading Checkbox
- List with Trailing Checkbox

The same thing happens using this list:
<mdc-list twoLine>

  <mdc-list-item>

    <mdc-list-item-text secondaryText="Secondary text">Single-line item</mdc-list-item-text>
    <mdc-chip-set mdcListItemMeta>
      <span>
        <button mdcIconButton>
          <mdc-icon>more_vert</mdc-icon>
        </button>
      </span>
    </mdc-chip-set>
  </mdc-list-item>
</mdc-list>

**Screenshots**
![image](https://user-images.githubusercontent.com/5549272/56946021-52e3c200-6b29-11e9-8438-f21263da9703.png)

**What Angular MDC version are you using?**
1.0.3

**What browser(s) is this bug affecting?:**
Tested in chrome

**Comment by trimox** [comment]
@Christian-E Thanks for reporting this. We're tracking an existing issue upstream.
reference: https://github.com/material-components/material-components-web/issues/4629

Possible workaround, https://github.com/material-components/material-components-web/issues/4629#issuecomment-487366408
