### ISSUE TITLE
Component Request: Toggle Button

### ISSUE THREAD

**Issue by zunamo** [trimox/angular-mdc-web#1888]
I was wondering if the 'toggle button'is being planned for development. I could not find its status anywhere. This would be useful component with many use cases (e.g. toggling views).

https://material.io/design/components/buttons.html#toggle-button

**Comment by zunamo** [comment]
For the future, should I ask these type of questions here or on the material-components page?

**Comment by trimox** [comment]
Hey @zunamo, I found a feature request upstream, https://github.com/material-components/material-components-web/issues/12

You could bump the issue, hopefully it's on the roadmap!

**Comment by zunamo** [comment]
Great, will check it out!
