### ISSUE TITLE
Collapse 

### ISSUE THREAD

**Issue by phutaneVinayak** [trimox/angular-mdc-web#1894]
**Is your feature request related to a problem? Please describe.**
Lib is missing with most important Collapse feature 

**Describe the solution you'd like**

**Describe alternatives you've considered**
we can do with List or with a card I don't know just idea came up in mind

**Additional context**
https://material.angular.io/components/expansion/examples

**Comment by trimox** [comment]
Closing. Please file this feature request upstream, https://github.com/material-components/material-components-web. If implemented, we can incorporate here.
