### ISSUE TITLE
Inconsistancy in mdc-select api

### ISSUE THREAD

**Issue by mohammadrafigh** [trimox/angular-mdc-web#1900]
**Describe the bug**
before v1.0.3 getSelectedValue()/setSelectedValue() returns and sets value with "any" type which is a correct value for mdc-select according to documentation. but in v1.0.3 these functions work with an "string" value while the "value" in mdc-select could be in "any" type. so I cannot set the value by an object anymore.

**Expected behavior**
Value should be in type "any" (like before) and the functions working with "value" should accept the type "any" instead of string.

**What Angular MDC version are you using?**
1.0.3
**What OS are you using?:**
All
**What browser(s) is this bug affecting?:**
All

**Comment by trimox** [comment]
Thanks for reporting this! On it.
