### ISSUE TITLE
mdc-helper-text doesn't show for mdc-select

### ISSUE THREAD

**Issue by BrianThorne** [trimox/angular-mdc-web#1930]
**Describe the bug**
mdc-helper-text doesn't show for mdc-select

**To Reproduce**
Check the last demo for mdc-select

**Expected behavior**
"Selection is required" should be showing below the control

**Screenshots**
![image](https://user-images.githubusercontent.com/52115473/59969868-fc0ecd80-9558-11e9-97ab-b257864445a8.png)

**What Angular MDC version are you using?**
1.0.5

**What browser(s) is this bug affecting?:**
Chrome

**Comment by trimox** [comment]
@BrianThorne Thanks for bringing this to my attention. Adding to next milestone
