### ISSUE TITLE
mdc-icon doesn't display when used as mdcListItemMeta in an mdc-list

### ISSUE THREAD

**Issue by BrianThorne** [trimox/angular-mdc-web#1941]
**Describe the bug**
This is when using Font awesome.

If I don't decorate with mdcListItemMeta, the icon shows in the list, but it's of course not positioned correctly.

See the screenshot. First two lines uses this html, and the icon is displayed:
[mdc-icon fontSet="fa" fontIcon="fa-trash-alt"][/mdc-icon]

Last two lines uses this html, and the icon is not displayed:
[mdc-icon mdcListItemMeta fontSet="fa" fontIcon="fa-trash-alt"][/mdc-icon]

**Screenshots**
![image](https://user-images.githubusercontent.com/52115473/60332629-8c08a900-9997-11e9-81f9-a70da89842a8.png)

**What Angular MDC version are you using?**
2.0.1

**Comment by BrianThorne** [comment]
Update: I was able to solve it using mdcIconButton as the mdcListItemMeta:
[button mdcIconButton mdcListItemMeta]
  [mdc-icon fontSet="fa" fontIcon="fa-trash-alt"][/mdc-icon]
[/button]

Result:
![image](https://user-images.githubusercontent.com/52115473/60344125-1cee7d00-99b6-11e9-9b2e-608a0df29a19.png)

**Comment by trimox** [comment]
Closing. Thanks for reporting back!
