### ISSUE TITLE
How do you change theme colors in typescript ?

### ISSUE THREAD

**Issue by jprules321** [trimox/angular-mdc-web#1942]
How do you change theme colors in typescript ? Do you have anything implemented for that yet?

**Comment by vekunz** [comment]
I don't think that there is a native material solution for this, but you can change the css variables that are used in background:
```
document.documentElement.style.setProperty('--mdc-theme-primary', '#123456');
document.documentElement.style.setProperty('--mdc-theme-primary', '#234567');
```
But this will only work in Chrome, Firefox and partially in Edge.
Source: https://davidwalsh.name/css-variables-javascript
