### ISSUE TITLE
Add inputmode to TextField

### ISSUE THREAD

**Issue by luisquicidev** [trimox/angular-mdc-web#1951]
I trying to force a numeric keyboard to some text inputs.
In Brazil we have some fields that needs a mask and we have to force the users to input only digits and the "tel" type for the input is not the best approach to do this. Adding the "inputmode = numeric" solve the question on a normal "input text". If i can do this in the TextField component, it will be amazing!

**Comment by trimox** [comment]
@luisquicidev I hear ya. 

Does the ***Numeric with NgModel*** example accomplish this for ya?

https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/text-field-demo/examples

```html
<mdc-text-field type="number"
  name="demoweight"
  label="Weight"
  ngModel
  #demoWeightModel="ngModel"
  required>
</mdc-text-field>
```

**Comment by luisquicidev** [comment]
@trimox this example works fine if i have a numeric-only input. But the input has a mask that write some non-numeric chars (like "." and "-"). In this case, the numeric keyboard will open in the mobile device but the additional chars of the mask will not be write. When the non-numeric chars will be inserted by the mask function, the input reject and not let the rest of number write in the input.
For "numeric" inputs with masks or other situations, the best approach is to set the inputmode. With the inputmode the mobile device will be recognize which keyboard will open.
My request for the inputmode attribute is for that situations. 
To accept non-numeric chars today, we have to set the type to "tel", but the tel keyboard don't have only numeric keys.
I created a directive for angular to force the inputmode on TextField (the directive modifies the DOM and insert the inputmode on the input inside the TextField component). It works, but an "native" attribute is more elegant. =D
PS: The input looks like "000.000.000-00". is an example. The user have to write only the digits.
PS: I'm using ionic 4 with your mdc library and it's so great! Thanks a lot for that.
