### ISSUE TITLE
data-table\component.ts is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#1959]
If you encounter this error it's an upstream issue, and will be resolved in next MDC release.
https://github.com/material-components/material-components-web/issues/4987

#### Workaround
Remove `*.ts` files from folder `node_modules\@material\data-table`

**Comment by Bitmanity** [comment]
Can you please elaborate the workaround
**Remove *.ts files from folder node_modules\@material\data-table**

**Comment by trimox** [comment]
Sure. Long and short, the `material-components-web` team accidentally published the Typescript `*.ts` files with the `data-table` component. Applications should use the already transpiled `*.js`.

Until the material teams next release, a quick workaround for downstream applications is removing the erroneous `*.ts` files from `@material/data-table`.

```bash
cd <path>/<app-name>/node_modules/@material/data-table

# List files (filter by *.ts)
ls *.ts -n

-rwxrwxrwx 1 0 0 5454 Aug 18 11:58 adapter.d.ts
-rwxrwxrwx 1 0 0 5261 Aug 18 11:58 adapter.ts
-rwxrwxrwx 1 0 0 2427 Aug 18 11:58 component.d.ts
-rwxrwxrwx 1 0 0 7406 Aug 18 11:58 component.ts
-rwxrwxrwx 1 0 0 1725 Aug 18 11:58 constants.d.ts
-rwxrwxrwx 1 0 0 2034 Aug 18 11:58 constants.ts
-rwxrwxrwx 1 0 0 2742 Aug 18 11:58 foundation.d.ts
-rwxrwxrwx 1 0 0 6604 Aug 18 11:58 foundation.ts
-rwxrwxrwx 1 0 0 1265 Aug 18 11:58 index.d.ts
-rwxrwxrwx 1 0 0 1266 Aug 18 11:58 index.ts
-rwxrwxrwx 1 0 0 1260 Aug 18 11:58 types.d.ts
-rwxrwxrwx 1 0 0 1255 Aug 18 11:58 types.ts

# remove *.ts from @material/data-table (with prompt for each)
rm -i *.ts
```

Hope this helps
-trimox

**Comment by maddy2894** [comment]
This is a major issue for ivy compilation in Angular 8, hope the team releases the new version soon.

**Comment by trimox** [comment]
@maddy2894 Thanks for reporting on Ivy. Be sure to watch issue #1982, Angular Ivy support is coming.
