### ISSUE TITLE
Automate CI deployment of documentation and demos

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#1965]
- [x] Generate GitHub token
- [ ] Compose travis-ci script and test

reference original discussion - https://github.com/trimox/angular-mdc-web/pull/1963#issuecomment-524987000

**Comment by TryHardDood** [comment]
Can't build the documentation and the demos until #1959 is fixed.

Also I would recommend using netlify.com to host and build the documentation and demos.

I already set up a demo just to see if it's capable of building and hosting it. ([Here](https://angular-mdc-web-tryharddood.netlify.com/))
