### ISSUE TITLE
mdc-select + mdc-helper-text: the HTML structure is not quite right.

### ISSUE THREAD

**Issue by ibelenski** [trimox/angular-mdc-web#1968]
According to the specifications, unlike the [text field helper text](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield/helper-text):

```
<div class="mdc-text-field">
...
</div>
<div class="mdc-text-field-helper-line">
  <div id="username-helper-text" class="mdc-text-field-helper-text" aria-hidden="true">
    This will be displayed on your public profile
  </div>
</div>
```
the [select helper text](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select/helper-text) HTML structure isn't supposed to include a container:

```
<div class="mdc-select">
...
</div>
<p id="username-helper-text" class="mdc-select-helper-text" aria-hidden="true">
  This will be displayed on your public profile
</p>
```

So using the `mdc-helper-text` component with an `mdc-select` doesn't quite work as expected.

**Comment by trimox** [comment]
@ibelenski Thanks for reporting, and investigative work. PR incoming adding `mdc-select-helper-text`.
