### ISSUE TITLE
Using the 'focus-trap' library in Drawer and Dialog

### ISSUE THREAD

**Issue by cary-smith** [trimox/angular-mdc-web#1981]
**Is your feature request related to a problem? Please describe.**
We have run into a problem with the use of `focus-trap` to push/recall focus when opening/closing a drawer or dialog. We develop non-angular-dependent web components for use across multiple technologies within our company. One of these is a pop-up based autocomplete that temporarily appends a listing to the bottom of the `<body>` so it can be placed anywhere on the page via positioning. 

While the user is interacting with the listing, focus remains on the input. If the user selects an entry, moves to another input, or clicks another location then the listing should auto-close. If they click one of the items in the listing (since it is actually appended to the body), `focus-trap` captures the event at the document level (not via bubbling...but via capture) forcing the listing to prematurely close due to focus change _before_ the event can be managed by the component while bubbling. Sadly we cannot use target-based event handling because the list entries can be a template of the developers choosing.

**Describe the solution you'd like**
To be honest, I have no issue with the concept in play here ...just the use of 'capture' since it precedes bubbling.

**Describe alternatives you've considered**
Either telling our developers not to use angular-mdc-web or trying to code around this issue in case someone uses the drawer or dialog from here which seems brittle. I would prefer to just ask 
 developers to upgrade to the latest angular-mdc-web.

**Additional context**
Excellent work! We have many developers using your components at this time.

**Comment by trimox** [comment]
@cary-smith 

Couple questions,
1. Is the pop-up described an `mdc-dialog`, or one of the non-angular components?

2. Could you provide a screen capture or [StackBlitz](https://stackblitz.com/edit/angular-mdc)?

I'll investigate if migrating to `@angular/cdk/a11y/focus-trap` provides flexibility for such a use case.

> Additional context
> Excellent work! We have many developers using your components at this time.

Much appreciated, that's great to hear! 😃

**Comment by cary-smith** [comment]
@trimox - Here's a super-basic example: https://stackblitz.com/edit/angular-mdc-dcd1bu

Notice the selectOption() never fires because the focus changes to `My Button` again.

Focusing the input will open the dialog, losing focus on the input will close it. We have to handle multiple interactions (like arrow keys etc) without losing focus. Our component is set up to capture the bubbling event and stop it to avoid focus changes. Unfortunately the focus-trap library's use of 'capture' overrides this and would/will have to be worked around.

Personally I think the use of 'capture' really should be in the developer space and not the library space (unless configurable) ...but that's just an opinion. Hopefully this clarifies the problem at hand. 

Any help is definitely be appreciated!

**Comment by trimox** [comment]
@cary-smith Thanks for the StackBlitz.

The following (2) PR's do away with `focus-trap` library, replacing it with configurable focus management.

Dialog - https://github.com/trimox/angular-mdc-web/pull/1984 (merged)

Drawer - https://github.com/trimox/angular-mdc-web/pull/1987 (pending merge)

**Comment by trimox** [comment]
@cary-smith Just released v3.2.0 with configurable focus management. Thanks again for your time to explain the business need.

Closing, published changes.
