### ISSUE TITLE
Prepare for Angular 9 Ivy

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#1982]
Outline of work to be done once Angular 9 final is made available, and Ivy is the new default.

#### Packages
- [ ] Remove `index.ts` in package folders
- [ ] Rename `public-api.ts` to `index.ts` in package folders
- [ ] Add `"enableIvy": true` to `angularCompilerOptions` to each `tsconfig-build.json`
- [ ] Update `tsconfig` files array to compile from `index.ts` instead of `public-api.ts`

#### Documentation and demos
- [ ] Add `"enableIvy": true` to `angularCompilerOptions` in `demos/tsconfig`
- [ ] TBD

#### Tests
- [ ] Add `tslint` rule for classes that inherit constructors via dependency injection from undecorated base class directives. This breaks dependency injection with Ivy.
- [ ] TBD

#### Build
- [ ]  TBD

**Comment by vekunz** [comment]
I'm not sure if this is an Ivy related issue or a general Angular 9 problem.  I tried to update our app to Angular 9 Ivy an got this error with the MdcRipple in the browser console:
```
Uncaught Error: Directives cannot inherit Components
    at ɵɵInheritDefinitionFeature (core.js:17420)
    at core.js:17
    at Array.forEach (<anonymous>)
    at Object.toString (core.js:17)
    at noSideEffects (core.js:17)
    at Module.ɵɵdefineComponent (core.js:17)
    at Module../node_modules/@angular-mdc/web/__ivy_ngcc__/esm2015/ripple.js (ripple.js:315)
    at __webpack_require__ (bootstrap:79)
    at Module../node_modules/@angular-mdc/web/__ivy_ngcc__/esm2015/button.js (button.js:1)
    at __webpack_require__ (bootstrap:79)
```

the code behind `Module../node_modules/@angular-mdc/web/__ivy_ngcc__/esm2015/ripple.js (ripple.js:315)` is
```
MdcRippleComponent.decorators = [
    { type: Component, args: [{
                selector: 'mdc-ripple, [mdc-ripple]',
                template: '<ng-content></ng-content>',
                providers: [MdcRipple],
                changeDetection: ChangeDetectionStrategy.OnPush
            },] },
];
```

**Comment by mattdsteele** [comment]
I can reproduce the same `Directives cannot inherit Components` error with MDC Web and an Angular 9 + Ivy codebase.

**Comment by rapropos** [comment]
@vekunz, @mattdsteele 

Please see if PR #2017 addresses your concerns

**Comment by mattdsteele** [comment]
It certainly looks like it should; is there a way you could publish a beta version to NPM so we could test it without pulling down and building the module?

**Comment by rapropos** [comment]
> is there a way you could publish a beta version to NPM so we could test it without pulling down and building the module?

I don't think I have the ability to do that. It would be neat if the project was structured so that we could just use the "rapropos/angular-mdc-web#ivyfood" syntax to use a fork in our `package.json`, but IIRC that's not possible either. So here's a step-by-step guide that should work:

First, [install nvm](https://github.com/nvm-sh/nvm#install--update-script) (if you're on Windows, there's [an equivalent](https://github.com/coreybutler/nvm-windows)). Then:

```
$ cd /usr/local/src
$ nvm use lts/dubnium
$ git clone https://github.com/rapropos/angular-mdc-web
$ cd angular-mdc-web
$ git checkout ivyfood
$ npm i -g yarn
$ yarn install
$ yarn run build:release
$ cd /path/to/project
$ rm -rf node_modules/@angular-mdc/web
$ cp -a /usr/local/src/angular-mdc-web/dist/releases/web node_modules/@angular-mdc/
$ ng build
```
...at least that's more or less what I do locally.

**Comment by trimox** [comment]
Thanks again @rapropos. Changes published under canary npm tag. 

`npm i @angular-mdc/web@canary` 

`yarn add @angular-mdc/web@canary`

**Comment by mattdsteele** [comment]
@trimox @rapropos Gave this a shot and it looks to be working great!

**Comment by johngrimsey** [comment]
Same here guys thanks!
