### ISSUE TITLE
Can't deselect an item in the selection group menu

### ISSUE THREAD

**Issue by TryHardDood** [trimox/angular-mdc-web#1997]
**Describe the bug**
Can't deselect a selected item in the selection group menu.

**To Reproduce**
1. Go to https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/menu-demo/examples
2. Click on 'Show Selection Group Menu'
3. Select anything.
4. Now try to deselect.

**Expected behavior**
To select an item and to deselect it.
Also it would be a nice touch if I don't have to reopen the menu every time I check something.

**What Angular MDC version are you using?**
v3.2.0

**What browser(s) is this bug affecting?:**
I only tried with the latest Google Chrome.

**Comment by trimox** [comment]
@TryHardDood Thanks for reporting this. 

Problems seems to be in `getSelectedSiblingOfItemAtIndex(index: number)`; always returning `-1`.
https://github.com/trimox/angular-mdc-web/blob/master/packages/menu/menu.ts#L108

 Let ya know..

**Comment by trimox** [comment]
Got it. PR incoming.

> Also it would be a nice touch if I don't have to reopen the menu every time I check something.

I'll have to submit separate PR for surface closing.
