### ISSUE TITLE
Theming components

### ISSUE THREAD

**Issue by pvamshi** [trimox/angular-mdc-web#20]
I am trying to theme the components but no idea how to do it. 
I tried the instructions given at the theming page and it did not work. 
Got this issue: 
https://stackoverflow.com/questions/44670730/theming-material-design-components-for-web-in-angular-2

anyone knows how to fix it  ?

**Comment by trimox** [comment]
@pvamshi, I've not used angular-cli much but your follow up [answer on stackoverflow](https://stackoverflow.com/a/44676391) is on par with how our demo-app themes. I'll try to compose the "Theme" how-to example page this week.

**Comment by pvamshi** [comment]
Yeah. I am also getting rid of angular-cli . So cool now .

**Comment by trimox** [comment]
I've begun composition of a theming guide. Look for PR soon..

**Comment by trimox** [comment]
@pvamshi, if you still need to import themes with Angular CLI. Check out the new [v0.2.0](https://github.com/trimox/angular-mdc-web/releases/tag/v0.2.0) release.

Closing w/commit https://github.com/trimox/angular-mdc-web/commit/ba521d6407e99fccced96ffdaee56d482e8c8e12
