### ISSUE TITLE
Error in documentation, public or private needed.

### ISSUE THREAD

**Issue by BlackTango** [trimox/angular-mdc-web#2007]
At this url : https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/dialog-demo/usage
in the section :  Sharing data with the Dialog component
there is an error in this code: 
`import { Component, Inject } from '@angular/core';
import {
  MdcDialogRef,
  MDC_DIALOG_DATA
} from '@angular-mdc/web';

@Component({
  // ...
})
export class YourDialog {
  constructor(
    public dialogRef: MdcDialogRef<YourDialog>,
    @Inject(MDC_DIALOG_DATA) data: DialogData) {
    userName: string = data.name;
  }
}`
This line of code need an access modifiers: 

` @Inject(MDC_DIALOG_DATA) public data: DialogData`

How can i contribute in the documentation?

**Comment by trimox** [comment]
@BlackTango Thanks for offering to resolve. Here's a couple guides to get started. If you have any questions, please feel free to ask.

Developer: https://github.com/trimox/angular-mdc-web/blob/master/docs/developer.md

Contributing guide: https://github.com/trimox/angular-mdc-web/blob/master/CONTRIBUTING.md#-submit-a-pull-request
