### ISSUE TITLE
Menu can get stuck in closed state

### ISSUE THREAD

**Issue by ddaspit** [trimox/angular-mdc-web#2009]
**Describe the bug**
It is possible for a menu to get in to a bad state where you can no longer open the menu. I have encountered two scenarios where this can happen. Both of them involve the an incorrectly registered click listener (registered by the `MdcMenuSurfaceBase._registerWindowClickListener()` function), which closes the menu immediately when trying to open it. Both scenarios occur when rapidly opening and closing the menu.

**To Reproduce**

Scenario 1
1. Quickly open and close the menu.
2. The menu is now in the closed state.
3. `MDCMenuSurfaceAdapter.notifyClose()` is called when the close animation completes.
4. `MDCMenuSurfaceAdapter.notifyOpen()` is called when the open animation completes and registers the window click listener.
5. Opening the menu does not work, because the window click listener is registered.

Scenario 2
1. Quickly open, close, and open the menu.
2. The menu is now in the open state.
3. `MDCMenuSurfaceAdapter.notifyClose()` is called when the close animation completes.
4. `MDCMenuSurfaceAdapter.notifyOpen()` is called twice when each of the open animations complete. Both calls register a window click listener.
5. Close the menu.
6. `MDCMenuSurfaceAdapter.notifyClose()` is called when the close animation completes and unregisters one of the window click listeners.
7. Opening the menu does not work, because the remaining window click listener is registered.

Here is a [StackBlitz](https://stackblitz.com/edit/angular-mdc-menu-stuck-closed) that reproduces both scenarios. Click on the "OUT-OF-SYNC" button to reproduce scenario 1 and the "MULTIPLE LISTENERS" button to reproduce scenario 2.

**Expected behavior**
The menu should open.

**What Angular MDC version are you using?**
3.2.1

**What OS are you using?:**
Windows 10, Ubuntu 16.04

**What browser(s) is this bug affecting?:**
Chrome 76, Firefox 69

**Additional context**
Although the reproduction sets the `MdcMenu.open` property directly, I can reproduce this by clicking. I'm not sure why, but it does seem to happen more easily on Linux.

**Comment by ddaspit** [comment]
I think that issue #1945 is the same as this issue.

**Comment by trimox** [comment]
Closed as part of #2034
