### ISSUE TITLE
Turning off AOT / BuildOptimizer breaks some components / directives when using ng build --prod

### ISSUE THREAD

**Issue by dgoudie** [trimox/angular-mdc-web#2012]
**Describe the bug**
Turning off AOT / BuildOptimizer breaks some components / directives when using ng build --prod. Causes "Cannot read property 'nativeElement' of undefined"

**To Reproduce**
1. Generate new angular project
4. Turn off buildOptimizer and aot inside angular.json > architect > build >configurations > production
2. Follow instructions to add angular-mdc/web
3. attempt to add this code to your app.component.html (after importing the required modules)
```html
<mdc-text-field autocomplete="tel" type="tel" label="Phone number">
  <mdc-icon mdcTextFieldIcon leading>phone</mdc-icon>
</mdc-text-field>
```
4. ng build --prod
5. serve the produced content and observe the error

**Expected behavior**
Build without AOT still works

**Screenshots**
working when running locally (ng serve)
![non-prod-working](https://user-images.githubusercontent.com/34222208/66494046-a6651f00-ea7c-11e9-84f3-aaea90c26ae8.PNG)

broken when built using ng build --prod
![prod-broken](https://user-images.githubusercontent.com/34222208/66494064-b1b84a80-ea7c-11e9-91fe-c1b636e4cf33.PNG)

**What Angular MDC version are you using?**
3.2.1

**What OS are you using?:**
Windows 10

**What browser(s) is this bug affecting?:**
Only browsers using es2015, IE11 unaffected

**Comment by trimox** [comment]
Closing. Resolved as part of the v5.x upgrade.
