### ISSUE TITLE
Mdc-slider's mixins doesn't work

### ISSUE THREAD

**Issue by lsalazarm99** [trimox/angular-mdc-web#2014]
**Describe the bug**
Mdc-slider's mixins have no problem compiling, but their result ended up doing nothing. According to the documentation found [here](https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/slider-demo/sass), I just need to use those mixins.

**To Reproduce**
1. Place a <mdc-slider> in the template file,
2. Import "@import '@angular-mdc/theme/scss/slider/mixins';" in the style file and apply one mixin, let's say, "@include mdc-slider-color-accessible(red);" to the mdc-slider.
3. Compile.
4. Mdc-slider is still the secondary color. It should be red.

[StackBlitz](https://stackblitz.com/edit/angular-mdc-ukvidq?file=src%2Fapp%2Fapp.component.scss)

**Expected behavior**
The mdc-slider changed its color.

**What Angular MDC version are you using?**
3.2.1

**What OS are you using?:**
Windows 10

**What browser(s) is this bug affecting?:**
I'm just trying in Chrome.

I noticed this in the compiled CSS (where .progress-bar is the mdc-slider):

`.progress-bar:not(.mdc-slider--disabled) .mdc-slider__track {
  background-color: red;
}
.progress-bar:not(.mdc-slider--disabled) .mdc-slider__track-container {
  background-color: rgba(255, 0, 0, 0.26);
}
.progress-bar:not(.mdc-slider--disabled) .mdc-slider__track-marker::after,
.progress-bar:not(.mdc-slider--disabled) .mdc-slider__track-marker-container::after {
  background-color: red;
}
.progress-bar:not(.mdc-slider--disabled) .mdc-slider__thumb {
  fill: red;
  stroke: red;
}
.progress-bar:not(.mdc-slider--disabled) .mdc-slider__focus-ring {
  background-color: red;
}
.progress-bar:not(.mdc-slider--disabled) .mdc-slider__pin {
  background-color: red;
}
.progress-bar:not(.mdc-slider--disabled) .mdc-slider__pin {
  color: white;
  /* @alternate */
  color: var(--mdc-theme-text-primary-on-dark, white);
}`

SCSS is doing its work. But for some reason, mdc-slider doesn't care about those compiled styles.

**Comment by trimox** [comment]
Please try again with v5.x. We can re-open if needed.
