### ISSUE TITLE
Error when start "ng build --prod"

### ISSUE THREAD

**Issue by iokononyuk** [trimox/angular-mdc-web#2027]
When I do production build project I get error:

ERROR in Illegal state: Could not load the summary for directive Dir in myproject/node_modules/@angular-mdc/web/node_modules/@angular/cdk/bidi/typings/index.d.ts.

How I can fix this?

**Comment by trimox** [comment]
Closing. Please re-test with v5.0, we can reopen if needed. Thanks.
