### ISSUE TITLE
mdc-menu inside mdc-list - cutting menu items

### ISSUE THREAD

**Issue by Anasalkhalil** [trimox/angular-mdc-web#2029]
Hi all,
I have Mdc-list and I have many list-items inside every list-item i have Menu Surface but when i try to open it i see it with wrong z-index because mdc-list-item have fixed height and overflow: hidden

here is the example
https://stackblitz.com/edit/angular-mdc-hafmkf

What Angular MDC version are you using?
 3.2.1
 3.2.1

What OS are you using?:
Windows 10

What browser(s) is this bug affecting?:
Chrome, FireFox

**Comment by TryHardDood** [comment]
Hi!
Just use [**hoistToBody**](https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/menu-surface-demo/api) on `mdc-menu-surface`

See here: [stackblitz.com](https://stackblitz.com/edit/angular-mdc-zm11a8)
