### ISSUE TITLE
Architecture overview

### ISSUE THREAD

**Issue by pvamshi** [trimox/angular-mdc-web#21]
This is not an issue actually. I want to understand how we are getting MDC styles into your app. I believe its done in webpack . But I am not able to get it working. 

I tried to add tabs. But I could not figure out how MDC components are added. 

When I add tabs I get the view like this : 

![image](https://user-images.githubusercontent.com/1425006/27424616-2e475ec6-5725-11e7-81f6-ffd9850aa39c.png)
There is style for button but not styles for classes `mdc-tab` , what am I missing.

**Comment by pvamshi** [comment]
I could find it . 
We are doing this in component.ts 
```ts
const MDC_TOOLBAR_STYLES = require('@material/toolbar/mdc-toolbar.scss');

styles: [String(MDC_TOOLBAR_STYLES)],

```

I could get it working after adding there .

**Comment by trimox** [comment]
@pvamshi, LGTM 👍
