### ISSUE TITLE
[textfield]: Cannot read property `nativeElement` of undefined

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#2113]

**Comment by antidote2** [comment]
I'm very interested in v5.0.4 release, since I've migrated my app to angular-mdc v5, but the forms are not rendered due to this bug, so I cannot release.

**Comment by trimox** [comment]
@antidote2 Sorry to hear that! v5.0.4 was published earlier today, hopefully it resolved. If your app uses `mdc-radio` I plan to publish v5.0.5 in a bit to resolve another Ivy engine bug..

**Comment by antidote2** [comment]
Thank you! You released faster than I could write my comment. The forms work well now. Like the new sass approach: it's cleaner.

Beste Grüße
Anatoli

________________________________
