### ISSUE TITLE
No provider for MdcIconRegistry.

### ISSUE THREAD

**Issue by westdabestdb** [trimox/angular-mdc-web#2123]
**To Reproduce**
Install Angular 9 then create a fresh Angular project. Install angular-mdc-web and try using the icon module.

**Expected behavior**
```
core.js:5873 ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[MdcIcon -> MdcIconRegistry]: 
  StaticInjectorError(Platform: core)[MdcIcon -> MdcIconRegistry]: 
    NullInjectorError: No provider for MdcIconRegistry!
NullInjectorError: StaticInjectorError(AppModule)[MdcIcon -> MdcIconRegistry]: 
  StaticInjectorError(Platform: core)[MdcIcon -> MdcIconRegistry]: 
    NullInjectorError: No provider for MdcIconRegistry!
    at NullInjector.get (core.js:1050)
    at resolveToken (core.js:17559)
    at tryResolveToken (core.js:17485)
    at StaticInjector.get (core.js:17300)
    at resolveToken (core.js:17559)
    at tryResolveToken (core.js:17485)
    at StaticInjector.get (core.js:17300)
    at resolveNgModuleDep (core.js:31600)
    at NgModuleRef_.get (core.js:32573)
    at resolveDep (core.js:33132)
    at resolvePromise (zone-evergreen.js:793)
    at resolvePromise (zone-evergreen.js:752)
    at zone-evergreen.js:854
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:40877)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)
defaultErrorLogger @ core.js:5873
handleError @ core.js:5926
next @ core.js:41822
schedulerFn @ core.js:36512
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:36474
(anonymous) @ core.js:40939
invoke @ zone-evergreen.js:365
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:40735
onHandleError @ core.js:40936
handleError @ zone-evergreen.js:369
runGuarded @ zone-evergreen.js:137
api.microtaskDrainDone @ zone-evergreen.js:671
drainMicroTaskQueue @ zone-evergreen.js:577
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:553
scheduleTask @ zone-evergreen.js:389
onScheduleTask @ zone-evergreen.js:273
scheduleTask @ zone-evergreen.js:379
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:841
then @ zone-evergreen.js:967
appInitializer @ router.js:9832
runInitializers @ core.js:39963
(anonymous) @ core.js:41829
_callAndReportToErrorHandler @ core.js:41994
(anonymous) @ core.js:41823
invoke @ zone-evergreen.js:365
onInvoke @ core.js:40899
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:124
run @ core.js:40674
bootstrapModuleFactory @ core.js:41798
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.ts:12
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
```
**What Angular MDC version are you using?**
```5.0.5```

**Comment by trimox** [comment]
Hi @westdabestdb please provide a code snippet preferably the `constructor`. I'll take a look..

Example
https://github.com/trimox/angular-mdc-web/blob/0c78279200fb03dfea2c2b24e711b48ed4679278/demos/src/app/components/icon/icon.ts#L71

**Comment by westdabestdb** [comment]
Unfortunately I don't use anything extra. It's just the default installation of this library, then when I try try the first demo on [https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/drawer-demo/examples](https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/drawer-demo/examples), this produces the error I mentioned above.

**Comment by westdabestdb** [comment]
I feel like the issue is about the icon module. Any component that uses icons is now giving this error.

**Comment by trimox** [comment]
Gotcha. 

I'll assume you referenced the getting started guide [here](http://localhost:4200/#/getting-started), so to import what's necessary for your use case the `./app/material.module.ts` should contain the following at a minimum. 

`import {MdcDrawerModule, MdcIconModule, MdcListModule, MdcTypographyModule} from '@angular-mdc/web';`

`MdcIconModule` is the class referenced above, so we want to ensure that is imported. Is it?

**Comment by westdabestdb** [comment]
It is, actually I can create a repo quickly so you may want to take a look at it?

**Comment by trimox** [comment]
Sure! Glad to help.

**Comment by westdabestdb** [comment]
[Here](https://github.com/westdabestdb/mdc-test) it is. Thank you, will be waiting!

**Comment by trimox** [comment]
Cloned, duplicated and resolved :smile:

Open `./tsconfig.json`. Change `enableIvy` to `true` OR remove the line entirely since Ivy is default view engine with Angular 9.

```
"enableIvy": true,
```

**Comment by westdabestdb** [comment]
Damn it lol. Thank you! 😬

**Comment by trimox** [comment]
Not a problem, glad it's working. I'll include a note on getting started guide regarding Ivy support.
