### ISSUE TITLE
Support for prefix and suffix text in mdc-text-field.

### ISSUE THREAD

**Issue by konraddrum** [trimox/angular-mdc-web#2124]
It seems strange not to have this useful feature.

https://material.io/components/text-fields/

Here's the example from [Angular Material](https://material.angular.io/components/input/examples).

**Comment by trimox** [comment]
Hi @konraddrum prefix and suffix features are in the MDC pipeline. Soon as it's made available we'll implement.

Recent discussion on spec implementation,
https://github.com/material-components/material-components-web/issues/5326#issuecomment-565164317

**Comment by asyncLiz** [comment]
https://github.com/material-components/material-components-web/issues/1892 is the tracking issue for prefix/suffix in MDC 😊

**Comment by trimox** [comment]
@asyncLiz Much appreciated!
