### ISSUE TITLE
mdc/typography doesn't set new font styles for 5.0.5

### ISSUE THREAD

**Issue by PabloG6** [trimox/angular-mdc-web#2129]
When trying to customize the typography or change the font, changing the variables as seen in the example doesn't seem to work.

**Code**
`use '@material/typography/mdc-typography';`
`use '@material/typography';`

`$mdc-typography-styles-headline1: (
  font-family: unquote("Raleway"),
  font-size: 97
);`

`$mdc-typography-styles-headline2: (
  font-family: unquote("Raleway"),
  font-size: 61
);`

These don't change the aforementioned typing styles to font-family, Raleway.

**Comment by trimox** [comment]
Hi @PabloG6 thanks for reporting this. A fix was merged in MDC upstream repo yesterday, I'll see how best to incorporate the change. Let ya know.

reference https://github.com/material-components/material-components-web/pull/5643

**Comment by trimox** [comment]
@PabloG6 Preparing to publish v5.1.0 with upstream fix.

**Comment by trimox** [comment]
@PabloG6 After upgrading to v5.1.0, use MDC guide for overriding styles.

https://github.com/material-components/material-components-web/tree/master/packages/mdc-typography#overriding-styles

**Comment by trimox** [comment]
Closed by #2134
