### ISSUE TITLE
Lazy Loaded Select Doesn't Set Value

### ISSUE THREAD

**Issue by mrp67** [trimox/angular-mdc-web#2141]
**Describe the bug**
When list items are lazy loaded, when clicking on a value, the select menu appears to still be empty.

**To Reproduce**
1. Go to the Lazy Load section of the Mdc Select section of the demo.
2. Click on the "load" button
3. Select a value
4. No value will be populated and select menu will remain empty

**Expected behavior**
Clicking on a value should populate the select menu and set the form value, just like the non-lazy loaded ones.

**Screenshots**
![image](https://user-images.githubusercontent.com/10659955/75554816-0dbe4400-5a09-11ea-8ec0-931f23034dba.png)

**What Angular MDC version are you using?**
This is in the demo which should be using the current latest version. I am also having the same issue on 5.0.5

**Comment by mrp67** [comment]
It seems like the form control value might be getting set, but the select always appears as empty

**Comment by mrp67** [comment]
I spun up the demo locally with a debug value below the select: `{{ lazySelect.value | json }}`
It seems that the correct value is set on the form, but the appearance of the select is not updated
![image](https://user-images.githubusercontent.com/10659955/75560455-2e8b9700-5a13-11ea-86ce-6ec01318afc9.png)

**Comment by mrp67** [comment]
I'm not entirely sure if this is how the issue should be fixed, but I was able to fix it by modifying the select's `layout` function. I'm basically doing what's happening in ngAfterViewInit in the 
```if (this._initialized) { ... }```

### Before (not working):
```
  private layout(): void {
    if (this._initialized) {
      this._selectBuilder();

      if (this._outlined) {
        this._foundation.layout();
      }
    }
  }
```

### After (working):
```private layout(): void {
    if (this._initialized) {
      this._asyncBuildFoundation().then(() => {
        this._selectBuilder();
      });

      if (this._outlined) {
        this._foundation.layout();
      }
    }
  }
```

**Comment by AlwaysAbhl001** [comment]
@trimox Any update on this ?

**Comment by trimox** [comment]
@AlwaysAbhl001 Resolving as part of #2125. Noticed demo was broken during testing.
