### ISSUE TITLE
Constructor in example of FormDialog belongs to ConfirmationDialog

### ISSUE THREAD

**Issue by SleevefishYoo** [trimox/angular-mdc-web#2143]
**Describe the bug**
In the sample, the constructor in the Form Dialog's dialog-form.ts belongs to Confirmation dialog.

**To Reproduce**
check the sample code for Form Dialog:
Link: [angular-mdc-web/demos/src/app/components/dialog/dialog.ts
:L354](https://github.com/trimox/angular-mdc-web/blob/fe306e0b2320e1a0dee131ef132949bd583f8835/demos/src/app/components/dialog/dialog.ts#L354)
> `constructor(public dialogRef: MdcDialogRef<DialogConfirmation>,
    @Inject(MDC_DIALOG_DATA) public data: DialogData) { }`

**Expected behavior**
`constructor(public dialogRef: MdcDialogRef<DialogForm>) { }
`
**What Angular MDC version are you using?**
N/A
**What OS are you using?:**
N/A
**What browser(s) is this bug affecting?:**
N/A
**Additional context**
This is probably not the best place to put it but I encountered more errors following your document to create a form dialog. Namely, I am getting 
`src/app/signup-dialog/dialog-form.html:7:17 - error NG8002: Can't bind to 'formGroup' since it isn't a known property of 'form'.` 
I am still new into web development so I am sorry for not providing a clearer explanation of the problem. Bravo for your work.

Edit: Added link to said line

**Comment by trimox** [comment]
@SleevefishYoo Thanks for letting me know. I'll fix dialog doc in a few. 

> src/app/signup-dialog/dialog-form.html:7:17 - error NG8002: Can't bind to 'formGroup' since it isn't a known property of 'form'.

You may need to import `CommonModule` in a shared or root module.

```
import {CommonModule} from '@angular/common';

@NgModule({
  imports: [
    CommonModule,
   ...
  ],
```
