### ISSUE TITLE
[tab-bar] align property breaks mdc-tab-bar

### ISSUE THREAD

**Issue by KaranKapoorIon** [trimox/angular-mdc-web#2179]
**Describe the bug**
Setting the align property on an mdc-tab-bar throws an exception which causes the control to not render.

**To Reproduce**

```
<mdc-tab-bar fixed align="center">
      <mdc-tab-scroller>
          <mdc-tab label="Tab 1"></mdc-tab>
          <mdc-tab label="Tab 2"></mdc-tab>
      </mdc-tab-scroller>
</mdc-tab-bar>
```

tab-bar.js - Exception is thrown because this.tabScroller is undefined

```
set align(value) {
    this._align = value || 'start';
    this.tabScroller.align = this.align;
}
```

**Expected behavior**
The tab bar should render with the tabs centered.

**What Angular MDC version are you using?** 5.1.1

**What OS are you using?:** Windows Server 2012

**What browser(s) is this bug affecting?:** Chrome

**Comment by KaranKapoorIon** [comment]
Re-setup everything and it seems to be working now.

**Comment by KaranKapoorIon** [comment]
@trimox I downloaded your 'angular-mdc' example (online version wanted working for me), tried to replicate it locally, but failed. As I've mentioned in the description. this.tabScroller seems to be null when trying to set align. Would you happen to know what I'm doing wrong here?

**Comment by KaranKapoorIon** [comment]
@trimox Found the issue. It happens when enableIvy is set to true under tsconfig.json

**Comment by trimox** [comment]
@KaranKapoorIon Thanks for reporting this. If you could retry, but this time install the canary tag for upcoming v6.0.0 release. 

```
yarn add @angular-mdc/web@canary
# or
npm i @angular-mdc/web@canary
```

**Comment by KaranKapoorIon** [comment]
@trimox Just tried it. The issue still persists.

**Comment by trimox** [comment]
@KaranKapoorIon Thank you for testing v6 canary with this. I'll try to duplicate.

**Comment by trimox** [comment]
Duplicated.
