### ISSUE TITLE
[text-field] Overriding density hides label

### ISSUE THREAD

**Issue by KaranKapoorIon** [trimox/angular-mdc-web#2185]
**Describe the bug**
Overriding the density on (default) mdc-text-field hides the label.

**To Reproduce**
```
<mdc-text-field label="Username"></mdc-text-field>
```

```
.mdc-text-field {
    @include text-field.density(-4);
}
```

**Expected behavior**
The label should be visible.

**What Angular MDC version are you using?** 5.1.1 (tested on canary as well)

**What OS are you using?:** Windows Server 2012

**What browser(s) is this bug affecting?:** Chrome

**Comment by trimox** [comment]
Hi @KaranKapoorIon Filled textfields will hide the floating label at certain densities. This behavior can be overridden by setting `$text-field.minimum-height-for-filled-label: 40px`

**Comment by trimox** [comment]
Closing.
