### ISSUE TITLE
@use in .scss files is not working

### ISSUE THREAD

**Issue by RikEskes** [trimox/angular-mdc-web#2189]
**Describe the bug**
Following the getting started guide, and also whilst using the template from StackBlitz, it seems that implementing @use in scss files to include the styling from the @material library is not working at it should. 

**To Reproduce**
1. Go to 'https://stackblitz.com/edit/angular-mdc-kwwzgt'
    https://stackblitz.com/edit/angular-mdc-agnnan
2. Look at the styling of both the button and the checkbox.
3. Go to 'https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/button-demo/api' or 'https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/button-demo/api'
4. Compare their styling to the styling in the Stackblitz demo.

**Expected behavior**
The styling for the button and the checkbox should be the same as shown in the demo from the corresponding components.

**What Angular MDC version are you using?**
6.0.0-canary.2 - Stackblitz project
5.1.0 - Local project

**What OS are you using?:**
MacOS Catalina 10.15.4
Windows 10

**What browser(s) is this bug affecting?:**
Safari 13.1
Google Chrome 80.0.3987.162
Firefox 74.0

**Extra info**
I asked this question in a bit of a broader sense on StackOverflow as well, you can follow it here:
https://stackoverflow.com/questions/60995662/why-is-use-in-my-scss-files-not-working-in-my-angular-9-1-0-project

**Comment by krzcho** [comment]
from the guide:

`@use "@angular-mdc/theme/material";`

points to @angular-mdc/theme/material.scss

there is no @material/theme.scss but @material/theme/mdc-theme.scss so my guess is that the correct import should look like below:

```
@use '@material/theme/mdc-theme' with (
  $mdc-theme-primary: #9E9E9E,
  $mdc-theme-secondary: #FFF3E0,
  $mdc-theme-background: #fff,
);
```

**Comment by krzcho** [comment]
compilation goes on but I still got error:

```
@use '@material/theme/mdc-theme' with (
  $mdc-theme-primary: #9E9E9E,
  $mdc-theme-secondary: #FFF3E0,
  $mdc-theme-background: #fff,
);
@use '@material/typography/mdc-typography';
@use "@angular-mdc/theme/material";
```

gives me

```
SassError: Undefined mixin.
  ╷
4 │   @include mixins.extended-fluid;
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@angular-mdc\theme\extend\mdc-fab.scss 4:3  @use
  node_modules\@angular-mdc\theme\material.scss 2:1        @use
  C:\...\src\styles.scss 14:1                                               root stylesheet
```

**Comment by RikEskes** [comment]
Glad to see you got it working for your project! However, my material-components-web is already on version 5.1.0. So that does not seem to be the culprit.

**Comment by RikEskes** [comment]
So I solved this issue by installing the necessary sass packages in the following way:

    npm install sass node-sass --save-dev

I believe my issue lies in that node-sass was installed as dependency instead of devDependency, and also that the sass library was missing from my project.

**Comment by mujirushi** [comment]
Here is the link to the sass-loader ticket, of which I think is related. There is a workaround for now with the webpack config.
https://github.com/webpack-contrib/sass-loader/issues/804

**Comment by RikEskes** [comment]
I have finally been able to solve this issue.

- I upgraded to Angular version 10.0.8 by using the ng update tool as documented [here](https://angular.io/cli/update)
- I removed node-sass as a dev dependency from my project
