### ISSUE TITLE
[text-field]: Should toggle `mdc-text-field--label-floating`

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#2206]
Missing class modifier found by @asyncLiz [here](https://github.com/trimox/angular-mdc-web/pull/2197#issuecomment-614196619)

Sync with earlier upstream change, https://github.com/material-components/material-components-web/pull/5727

**Comment by trimox** [comment]
Hey @asyncLiz Investigating earlier comment for missing `--label-floating`. I do see `mdc-text-field--label-floating` toggled using Chrome at least. Any further insight?

### Sample no focus:
![image](https://user-images.githubusercontent.com/11887843/79404862-dd9f1600-7f60-11ea-8a3a-10e37bdd8e0d.png)

### Sample with focus:
![image](https://user-images.githubusercontent.com/11887843/79404968-25be3880-7f61-11ea-9f32-c9173a23a872.png)

![image](https://user-images.githubusercontent.com/11887843/79405069-6a49d400-7f61-11ea-899d-3370672f390b.png)

Chrome styles tab with focused styles,

![image](https://user-images.githubusercontent.com/11887843/79405197-b85ed780-7f61-11ea-990d-db865a6dde3a.png)

**Comment by asyncLiz** [comment]
My bad! Working with too many partner teams, I forgot that Angular uses the foundation, which will toggle the class for you. You shouldn't need it in your template unless you had to worry about server-side rendering.

**Comment by trimox** [comment]
@asyncLiz No worries!
