### ISSUE TITLE
[text-field] When required is set an asterisk (*) is added to the label even if there is no label

### ISSUE THREAD

**Issue by tinybigideas** [trimox/angular-mdc-web#2216]
**Describe the bug**
If required is set for the component it adds an asterisk (*) to the label even if there is no label. If you are using an external label, this looks very odd.

**To Reproduce**
1. `<mdc-text-field outlined required></mdc-text-field>`
2. See error

**Expected behavior**
I would expect it to check if there is a label. If so, append asterisk (*) as per spec. If there is no label, don't append.

**Screenshots**

![image](https://user-images.githubusercontent.com/2805752/79536006-e124c100-8076-11ea-9103-6e901192e5af.png)

(Looks bad when an external label is used without a floating label)

**What Angular MDC version are you using?**
5.1.1

**Comment by tinybigideas** [comment]
Closing, looks like to ab MDC issue, will defer to: https://github.com/material-components/material-components-web/issues/1363

**Comment by trimox** [comment]
Reopening. @tinybigideas Thanks for reporting on this. There was a time I had this working, will review..

**Comment by trimox** [comment]
Got it.

https://github.com/trimox/angular-mdc-web/blob/master/packages/notched-outline/notched-outline.html#L3
