### ISSUE TITLE
Need access to ElementRef in the fab button component 

### ISSUE THREAD

**Issue by Davis-Jeffery** [trimox/angular-mdc-web#224]
You currently have the ElementRef of the component set as a private variable called _root in the MdcFabComponent constructor. If you made that variable public I would be able to use it to manipulate that button in the DOM in my own typescript file.  If there is another way to access the element other then doing a query selector please let me know what I am missing. 
```
constructor(
    private _renderer: Renderer2,
    private _root: ElementReRef,
    private _ripple: MdcRipple) {
    this._ripple.init();
  }
```

**Comment by Davis-Jeffery** [comment]
I found a way to bypass the component and get the element ref. This works for now but it still would be nice to have access to it through the actual component.

`@ViewChild('fab',{read:ElementRef}) private mdcFab;`

**Comment by trimox** [comment]
@Davis-Jeffery Yep, this could be very useful.

**Comment by trimox** [comment]
Look for PR soon as `Snackbar` PR is merged. I'll review other components as well, since `ElementRef` should be made available library wide.

**Comment by Davis-Jeffery** [comment]
I completely agree. Thank you. You guys are doing awesome.
