### ISSUE TITLE
menu and FormControls

### ISSUE THREAD

**Issue by rapropos** [trimox/angular-mdc-web#240]
I wonder if it might be possible to somehow create some sort of alternative wrapping API for a menu toggle / menu combination that could be bound directly via either `[(ngModel)]` or to a `FormControl` without the need for having a dedicated opening method, `@ViewChild` to the menu, and a `(select)` handler in the controller?

**Comment by trimox** [comment]
@rapropos Definitely.
If `@Input` property (below) is added, you could bind using `[(ngModel)]` or `FormControl`. 
```ts
@Input('open') open_: boolean;
```
Is this what ya need?

**Comment by rapropos** [comment]
I am thinking of something that would be a drop-in replacement for `<select>`, that would incorporate all the toggling as well.

**Comment by trimox** [comment]
Just completed some significant infrastructure changes. Reviewing this request and will let ya know.

**Comment by trimox** [comment]
Hey @rapropos 
Just released MDC v0.5.4 and the MDC Select component. Does this include the functionality you're looking for?

**Comment by rapropos** [comment]
I'm not seeing a section on it in the demo app, but I'll try to figure out how to use it from the source.

**Comment by trimox** [comment]
Awesome to hear 👍 

Yeah, the scrollbar is related to upstream issue: https://github.com/material-components/material-components-web/issues/1387. I also mentioned a concern regarding the change prior to the MDC release; https://github.com/material-components/material-components-web/issues/1247, but it may have been overlooked.

Are you using `@angular-mdc/theme` for your application Sass import? I introduced a temporary fix until resolved upstream. https://github.com/trimox/angular-mdc-web/tree/master/src/theme/extend/mdc-menu
If the temporary fix is not working, please let me know.
-trimox

**Comment by rapropos** [comment]
My `@angular-mdc/theme` was still on 0.0.3. After upgrading it to 0.0.4, I no longer see the scroll bar. Thanks for taking the time to implement this; I find it much easier to work with than dealing with the menu manually.
