### ISSUE TITLE
Other classes get overridden

### ISSUE THREAD

**Issue by pvamshi** [trimox/angular-mdc-web#25]
Not sure if this is intended behavior . 
```HTML
<mdc-toolbar 
      [flexible]="true" 
      [fixed]="true" 
      [waterfall]="true" 
      [fixedLastrow]="true" 
      [flexibleTitle]="true" 
      class="abcdef">
```

I have additional classname `abcdef` which gets overridden as we are setting class name instead of adding class to the element. 
```ts
  @HostBinding('class') className: string = 'mdc-toolbar';

```

I can try to give a PR if its a bug.

**Comment by trimox** [comment]
@pvamshi, nice catch. Funny, I discovered this issue while working on the mdc-card this morning. I'll have a PR up for all the components today including the new Card component.

**Comment by pvamshi** [comment]
Didn't wanted to create another issue, so pinging here. Can we have a gitter to communicate ? or is it too much ..

**Comment by trimox** [comment]
Not a problem. I'll add a badge to the README.md this evening.

https://gitter.im/angular-mdc/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by trimox** [comment]
@pvamshi, would you be able to update your npm bundle to v0.1.16? I'd like to ensure this resolves the reported issue. If it does, I'll do a large PR tonight to fix the remaining components.
PR https://github.com/trimox/angular-mdc-web/pull/28

**Comment by pvamshi** [comment]
Yes its working with that change.
