### ISSUE TITLE
supporting text does not show on horizontal cards

### ISSUE THREAD

**Issue by rapropos** [trimox/angular-mdc-web#266]
```
<mdc-card>
<mdc-card-horizontal>
<mdc-card-supporting-text>in oblivion</mdc-card-supporting-text>
</mdc-card-horizontal>
</mdc-card>
```

Taking the `<mdc-card-horizontal>` out, the supporting text appears. Strangely, I couldn't even find the element in the DOM in the horizontal case. If there is some reason that this *can't* work, then I would suggest at least putting a note in the documentation telling people not to try.

**Comment by trimox** [comment]
@rapropos Yeah, `mdc-card-horizontal` selector is a bit too strict on content acceptance. Working on a PR..
