### ISSUE TITLE
mdc-icon and multiple fontIcons

### ISSUE THREAD

**Issue by rapropos** [trimox/angular-mdc-web#280]
### What Angular MDC version are you using?
0.5.3

### What browser(s) is this bug affecting?
Chromium for certain

### What OS are you using?
Debian stretch

### What are the steps to reproduce the bug?
Attempt to use a size modifier on a FontAwesome `<mdc-icon>` such as `<mdc-icon fontSet="fa" fontIcon="fa-2x fa-map">`

### What is the expected behavior?
A larger-sized map icon.

### What is the actual behavior?
Nothing is displayed inside the `<mdc-icon>`.

### Any other information you believe would be useful?
Inverting the order of the classes has no effect.
Multiple `fontIcon`s each with one class doesn't work either.
Binding to an array such as `[fontIcon]="['fa-map', 'fa-2x']"` doesn't work either.

**Comment by trimox** [comment]
Thanks for the detailed report! I'm looking into this today.

**Comment by trimox** [comment]
@rapropos Good news. I've added support for multiple `fontIcon` classes. PR in a few minutes. 
If you require a workaround till v0.5.4 is released.
```html
<mdc-icon fontSet="fa" fontIcon="fa-map" class="fa-2x"></mdc-icon>
```

PR adds support for things like
```html
<mdc-icon fontSet="fa" fontIcon="fa-map fa-2x"></mdc-icon>
```
