### ISSUE TITLE
mdc-tab-bar-scroller__indicator misplaced

### ISSUE THREAD

**Issue by Eski** [trimox/angular-mdc-web#281]
Hi, 
I start using angular-mdc lately and i notice an issue in **mdc-tab-bar-scroller**.
The **mdc-tab-bar-scroller__indicator** is not positioned correctly because the width of the **mdc-tab** change after Roboto has been applied. If you resize the page the **mdc-tab-bar-scroller__indicator** will set correctly.

Here a screenshot:
<img src="https://img15.hostingpics.net/pics/634251tabbug.jpg"/>

You can see the width of **mdc-tab-bar-scroller__indicator** is longer then the **mdc-tab**

By the way, you have an error in **tab-bar-scroller** component, you called the class "mdc-tab-bar-scoller" instead of "mdc-tab-bar-scroller", you forgot the R.

I'm using version 0.5.3

**Comment by trimox** [comment]
@Eski Thanks for reporting the spelling issue. PR available

I'm looking into the tab-bar-scroller issue as well. Let ya know in a bit.

**Comment by Eski** [comment]
There's also an issue in the toolbar component. If i have a fixed toolbar with two **mdc-toolbar__row**, the margin-top who was associated to the body is incorrect.

**Comment by trimox** [comment]
@Eski I'm testing the original issue regarding tab indicator positioning, and not able yet to duplicate. Which OS and browser are you using? I'll re-test in SauceLabs using your setup.

**Comment by Eski** [comment]
I'am using Win10, Chrome version  62.0.3202.62. I created a new angular project with your angular-mdc-web v0.5.3.
I loaded Roboto font and material icons in index.html, created a **mdc-toolbar** with two **mdc-toolbar-row**, in the second row i have a **mdc-tab-bar-scroller** with 4 tabs.

You have to open the inspector and disable cache in the network tab or to set a delay with fast 3g to make the Roboto font render after the initialization of the components. then you will notice the wrong position of the tab indicator when you select another tab, specially the last one.

**Comment by trimox** [comment]
Ah, Toolbar was the missing ingredient :smile
Duplicated it this time, working on a PR.

**Comment by Eski** [comment]
Good to hear it :)

It would be great also if you could add a property for **mdc-toolbar** component to disable the adding of margin-top to the body and then in the **setStyleForFixedAdjustElement** function just check the state of this property like this for example : 

```
@Input() adjustBodyMargin: boolean = false;
setStyleForFixedAdjustElement: (property: string, value: string) => {
     if (isBrowser() && this.fixed && this.adjustBodyMargin) {
              this._renderer.setStyle(document.body, property, value);
     }
}
```

**Comment by trimox** [comment]
Good idea. I'll add this.

**Comment by trimox** [comment]
PR for `adjustBodyMargin` #298

**Comment by trimox** [comment]
I'll re-test the original issue for scrollbar indicator alignment today using the latest version.

**Comment by trimox** [comment]
Issue remains with `transformValue` on the indicator line. Problem is upstream with no pending PR. I'll create an issue and submit PR.

**Comment by trimox** [comment]
Resolving this in pull request #369

**Comment by trimox** [comment]
All set. Once merged, I'll close the issue.
