### ISSUE TITLE
Layout Grid IE11

### ISSUE THREAD

**Issue by Eski** [trimox/angular-mdc-web#291]
Hi, 

I notice a bug in the **mdc-layout-grid** with IE11. The mdc-layout-grid__cell's overlays in each other.
I don't know if it's an issue with material-components-web version 0.22.1 css classes or not.

Here it's : 
<img src="https://img4.hostingpics.net/pics/490007gridbug.jpg">

**Comment by trimox** [comment]
@Eski if you could paste in a code sample and I'll let ya know if its upstream in MDC.

**Comment by Eski** [comment]
It's just a div with mdc-layout-grid class with 3 cell's in a mdc-card component.

`<mdc-card class="mdc-card--white">
    <mdc-card-primary>
      <div class="mdc-layout-grid">
        <div class="mdc-layout-grid__inner">
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
            <p>Perferendis voluptates voluptas deserunt et provident voluptatum! Eaque id, temporibus consequuntur iure, culpa provident cum, facilis expedita harum voluptatibus laboriosam eum consequatur!</p>
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit</p>
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
            <p>Culpa provident cum, facilis expedita harum voluptatibus laboriosam eum consequatur!</p>
          </div>
        </div>
      </div>
    </mdc-card-primary>
</mdc-card>`

**Comment by trimox** [comment]
@Eski Definitely a problem upstream in MDC Sass. Chrome and Firefox look great with sample code provided.
Good old IE 11 😉

**Comment by Eski** [comment]
I ended up using FlexLayout but I hope it will be fixed.

**Comment by trimox** [comment]
Glad to hear! FlexLayout is great alternative. 

Closing - should be fixed upstream.
