### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError with conditional card button

### ISSUE THREAD

**Issue by rapropos** [trimox/angular-mdc-web#293]
### What Angular MDC version are you using?
0.5.3

### What browser(s) is this bug affecting?
Chromium for certain

### What OS are you using?
Debian stretch

### What are the steps to reproduce the bug?
The most minimal reproduction I have achieved so far is as follows (put a `triggered` boolean in the controller):

```
<button mdc-button (click)="triggered = !triggered">trigger</button>

<mdc-card *ngIf="triggered">
  <div *ngIf="true">
    <button mdc-card-button>
      trouble button
    </button>
  </div>
</mdc-card>
```
Clicking the `trigger` button should trigger the exception.

### What is the expected behavior?
No exceptions thrown.

### What is the actual behavior?
```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: ''. Current value: 'mdc-button--compact'.
    at viewDebugError (core.es5.js:8434)
    at expressionChangedAfterItHasBeenCheckedError (core.es5.js:8412)
    at checkBindingNoChanges (core.es5.js:8576)
...
    at checkNoChangesView (core.es5.js:12251)
```

I can provide the rest of the stacktrace if needed.

### Any other information you believe would be useful?
The second-level `<div>`, despite its structural `ngIf` condition being always `true`, seems to be relevant. Removing the seemingly meaningless `*ngIf="true"` on the inner `<div>` causes the exception to no longer be thrown.

Manually setting the `compact` property on the trouble button also makes the problem go away, so I suspect it has something to do with how the default setting for that property is managed.

**Comment by trimox** [comment]
PR incoming
