### ISSUE TITLE
Why better than material2?

### ISSUE THREAD

**Issue by devlfm** [trimox/angular-mdc-web#295]
Hi,

Is there possible to innumerate why developers should adopt this instead of material2? What are the strengths and weakness? maybe a compare table on the readme

Thank you!

**Comment by Eski** [comment]
Hi, 
First of all, you have all the classes of material-design-components witch has more classes than material2.
You have also the implementation of the 3 types of Drawer, i prefer it more than the sidenav component of material2.

Personalty, i tried both but angular-mdc-web (which is an implementation of material-design-components) fell more cleaner (the font sizes, letter-spacing, paddings, etc ...)

**Comment by trimox** [comment]
Hey @devlfm 

Good questions. I've waited to respond and would love to hear from the community. 
My personal opinion, engineers should pick the right tool for the job..
-trimox

**Comment by T8xi** [comment]
Hey,
I believe it gives us developers much more freedom than material2. Material2 lacks of some compoments and classes as @Eski said. If you like a slick design and need a fast yet unflexible progress, material2 is your choice.
Personally, i didn't like the fact how the drawer works in material2. I couldn't get used to wrap my whole content into a drawer-context. I thing a drawer should be no more than a sidenav and so should be somewhat independet of the main content.
In `@angular-mdc/web` I liked alot how easy you could define a button somewhere in your application, that opens a temporary drawer.

So to cut the long story short.... `@angular-mdc/web` simply fits my needs better

**Comment by Eski** [comment]
in my opinion, if this library had autocomplete and date picker, this will be a full library who can compete with material2.

**Comment by trimox** [comment]
@Eski 
Stay tuned. I'm extending our component library by adding features not yet available in upstream material-components-web.

First up
* Mini variant drawer: #158
* Auto-complete (search component): https://material.io/guidelines/patterns/search.html#search-in-app-search
* Date Picker: #392
* Expansion panels: https://material.io/guidelines/components/expansion-panels.html

**Comment by trimox** [comment]
Thanks for everyone's input!

Closing out.
