### ISSUE TITLE
export MaterialModule missing in @angular-mdc/web

### ISSUE THREAD

**Issue by T8xi** [trimox/angular-mdc-web#309]
### What Angular MDC version are you using?
0.5.4
### What browser(s) is this bug affecting?
none
### What OS are you using?
win10 pro
### What are the steps to reproduce the bug?
Update dependency from 0.5.1 to 0.5.4
### What is the expected behavior?
The import statement '`import {MaterialModule} from "@angular-mdc/web"`' should import the MaterialModule as described in the "how to get started" readings.
### What is the actual behavior?
[ts] Module `.../@angular-mdc/web/index` has no exported member 'MaterialModule'. 
### Any other information you believe would be useful?
If the change is intended, "docs/getting-started.md" needs to be updated.
Otherwise the missing global MaterialModule needs to be added to the public_api.

This issue is reproducable by doing an update from 0.5.1 to 0.5.4. It is also reproducable by doing a fresh "npm install" on my project

**Comment by trimox** [comment]
@T8xi Thanks for reporting. So, `MaterialModule` is depreciated however it's intended to be available. I'll look into and hopefully release an update today.

**Comment by trimox** [comment]
PR merged. Soon as v0.5.5 is published the `MaterialModule` will work again.

**Comment by trimox** [comment]
@T8xi v0.5.5 released.
`npm i @angular-mdc/web@latest`

**Comment by T8xi** [comment]
@trimox thank you!
