### ISSUE TITLE
mdc-textfield placeholder

### ISSUE THREAD

**Issue by Eski** [trimox/angular-mdc-web#311]
Hi, 
I notice that the placeholder doesn't work in the mdc-textfield. It would be nice if i could disable label and show placeholder instead.

**Comment by trimox** [comment]
Hey @Eski Following up, do you just want to hide the floating label if input has a value?

**Comment by Eski** [comment]
I just want to hide the floating label and have placeholder instead even if input is empty, like a search field for example.

**Comment by trimox** [comment]
@Eski so this is one way to accomplish this.
```html
<mdc-textfield label="Search" [fullwidth]="true"></mdc-textfield>
```

**Comment by Eski** [comment]
Thx, this will do the trick.

**Comment by trimox** [comment]
Good to hear 👍 

Closing out.
