### ISSUE TITLE
Mdc-Select can not pre select

### ISSUE THREAD

**Issue by pvamshi** [trimox/angular-mdc-web#319]
### What Angular MDC version are you using?
0.5.4
### What browser(s) is this bug affecting?
Firefox
### What are the steps to reproduce the bug?
Component : 
```ts
  public selectedStatus = 'Active';
```
HTML 
```pug
mdc-select( #activestatus label="All Status" [(ngModel)]="selectedStatus" 
     '(change)'="setFilter('statusType', $event.value)")
  mdc-select-item(value="All Status") All Status
  mdc-select-item(value="Active" ) Active
  mdc-select-item(value="Deactivated") Deactivated
```

### What is the expected behavior?
Active to be selected 
### What is the actual behavior?
![](https://screenshots.firefoxusercontent.com/images/6b2276d4-67fe-41f6-9673-e2b0d6731cd4.png)

### Any other information you believe would be useful?
Also, there is no way to preselect an item

**Comment by trimox** [comment]
@pvamshi Thanks for reporting. On it.

**Comment by trimox** [comment]
PR will be available today.

**Comment by trimox** [comment]
Still working on it. Added features to `mdc-select-item` such as focus(), set unique id if not provided and a `selected: boolean`.

**Comment by trimox** [comment]
PR was merged.
