### ISSUE TITLE
Ripple: Set primary/secondary color

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#322]
Assign modifier classes that can be used for styling ripple surfaces using the configured theme's primary and secondary colors.

Reference: https://github.com/material-components/material-components-web/blob/a983c01676e7b2a9b4aa743f722588ecb2019e4f/packages/mdc-ripple/README.md#the-mdc-ripple-surface-class

- [x] Add `primary` property
- [x] Add `secondary` property
- [x] Update documentation
- [x] Include unit test

**Comment by devlfm** [comment]
Hi @trimox ,

Do you think it's possible also to set the size of the Ripple? it's too big on checkbox's/toogles.. maybe a condensed size?

**Comment by trimox** [comment]
@devlfm Are you looking for ripple size similar to the `disabledRipple` checkbox example?

https://trimox.github.io/angular-mdc-web/#/checkbox-demo

**Comment by devlfm** [comment]
On size yes! but on that sample it stays visible until gets focus out somewhere.. Is that intentional?

**Comment by trimox** [comment]
@devlfm I didn't forget. Next release has smaller ripples ;)

![checkbox](https://user-images.githubusercontent.com/11887843/35920991-6ccc22fe-0be7-11e8-890c-c420788fd2cf.gif)

**Comment by devlfm** [comment]
Thank you! that awesome :1st_place_medal:
