### ISSUE TITLE
Does not work with Angular Universal (Server Rendering)

### ISSUE THREAD

**Issue by trehyu** [trimox/angular-mdc-web#33]
Currently this doesn't work with server-rendering turned on, as you get this error:

> ReferenceError: window is not defined

It looks like there's a few directives (ripple, menu, and maybe others?) that use window without checking first if it exists - which is a problem since 'window' does not exist on the server side.

Would it be possible to modify those files so that it could work with [Angular Universal](https://github.com/angular/universal#universal-gotchas)?

**Comment by trimox** [comment]
@trehyu, just submitted a PR for adding universal support. I've added checks to our `window` or `document` references so they degrade gracefully. If you have time could you give the PR a test drive? If not, I can provision a quick universal app to test.

**Comment by trimox** [comment]
@trehyu, sorry meant to include a link to the PR 😄 
Pull Request: https://github.com/trimox/angular-mdc-web/issues/34

**Comment by trehyu** [comment]
Just tried out the pull request and it works perfectly!  Thank you so much, that was fast.  :smile:

**Comment by trimox** [comment]
@trehyu, not a problem! Thank you for requesting this feature and performing testing.

**Comment by JeetChaudhari** [comment]
@trimox This issue still occurs in the current build for few components.
