### ISSUE TITLE
Mdc Dialog

### ISSUE THREAD

**Issue by Eski** [trimox/angular-mdc-web#370]
Hi, 

I want to implement Dialog in my component without creating a separate component for the dialog. I just want to deal with dialog like a template in my component but i struggle with this error : **Error: No provider for MdcDialogRef.**

It will be nice if you could update the documentation for this type of approach.

Thx

**Comment by trimox** [comment]
@Eski Yep, can do. I'll either make `MdcDialogRef` an optional constructor argument, or abstract out the component to use without a service.

**Comment by trimox** [comment]
Closing. PR #383 merged.
