### ISSUE TITLE
MdcSelect do not get reset when value is blank or cleared

### ISSUE THREAD

**Issue by pvamshi** [trimox/angular-mdc-web#371]
### What Angular MDC version are you using?
0.5.6
### What are the steps to reproduce the bug?
Controller code 
```ts
  @ViewChild(MdcSelect) foodSelector: MdcSelect;
```
```ts
this.foodSelector.clearSelection();
```

HTML 

```html
  <mdc-select label="Favorite foo" name="food">
      <mdc-select-item value="v1"> Val 1 </mdc-select-item>
      <mdc-select-item value="v2"> Val 2 </mdc-select-item>
      <mdc-select-item value="v3"> Val 3 </mdc-select-item>
  </mdc-select>
```

### What is the expected behavior?
![image](https://user-images.githubusercontent.com/1425006/32656733-249077fe-c639-11e7-8e6a-5b4bd4bfde44.png)

The form selection should get reset . 

### What is the actual behavior?
![image](https://user-images.githubusercontent.com/1425006/32656752-37c1f4ec-c639-11e7-8210-3e650144ef60.png)

This behavior is the same with ```ngModel``` or ```formControlName```

**Comment by trimox** [comment]
Closing. Thanks for reporting. PR is merged.

**Comment by 3lhagvaasuren** [comment]
that still doesnt work man
