### ISSUE TITLE
Angular v4 with Angular-mdc/web v0.6

### ISSUE THREAD

**Issue by Eski** [trimox/angular-mdc-web#390]
Hi, 

I like to use angular-mdc v0.6 with angular v4 instead of v5 but i notice this error when i want to build my application : 
`ERROR in Metadata version mismatch for module C:/Users/Brahim/www/test/test-mdc/node_modules/@angular-mdc/web/index.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/Brahim/www/test/test-mdc/src/app/app.module.ts, resolving symbol AppModule in C:/Users/Brahim/www/test/test-mdc/src/app/app.module.ts`

I don't know if this version (0.6) work with old version of angular or i should use angular v5.

**Comment by pvamshi** [comment]
I too got this error, so I moved to A5 .

**Comment by trimox** [comment]
@Eski You'll need to use Angular v5. I noticed our documentation was missing a section on dependency requirements, and added them today.

Closing: docs updated.
