### ISSUE TITLE
Date Picker Component Request

### ISSUE THREAD

**Issue by rurziceanu** [trimox/angular-mdc-web#392]
Spec reference: https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers
It would be great if this library would have a datepiker component

**Comment by trimox** [comment]
Stay tuned. I'm extending our component library by adding features not yet available in upstream `material-components-web`.

First up
* Mini variant drawer - https://github.com/trimox/angular-mdc-web/issues/158
* Auto-complete (search component)
* Date Picker: https://github.com/trimox/angular-mdc-web/issues/392
* Expansion panels: https://material.io/guidelines/components/expansion-panels.html

**Comment by rurziceanu** [comment]
That is a great news
Especially that material-components-web guys don't plan to release these components soon

**Comment by cpru2** [comment]
as a corollary to this would love a date time picker component if possible

**Comment by trimox** [comment]
@cpru2 Agree. I'm composing engineering documents for the following.
reference: https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers
reference: https://material.io/guidelines/components/pickers.html#pickers-time-pickers

Minor update for this thread. 
`mdc-data-table` and `mdc-expansion` components are couple weeks out. Should free up time for the Date/Time component design.

**Comment by cpru2** [comment]
bumping this — if anyone knows of any supported component libraries that have a datetimepicker, would greatly appreciate a temporary solution.

**Comment by trimox** [comment]
Closing for now. Focusing on component refactoring and enhancements.
