### ISSUE TITLE
Angular CLI - postcss-custom-properties warnings

### ISSUE THREAD

**Issue by RaduGrama** [trimox/angular-mdc-web#394]
Any suggestion on how to get around this? I am simply following the instructions to get a sample project setup and this warning shows up multiple times:

```
WARNING in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.sass
(Emitted value instead of an instance of Error) postcss-custom-properties: /Users/X/Projects/Y/src/styles.sass:886:3: Custom property ignored: not scoped to the top-level :root element (.mdc-checkbox { ... --mdc-ripple-fg-translate-start: ... })
NonErrorEmittedError: (Emitted value instead of an instance of Error) postcss-custom-properties: /Users/X/Projects/Y/src/styles.sass:886:3: Custom property ignored: not scoped to the top-level :root element (.mdc-checkbox { ... --mdc-ripple-fg-translate-start: ... })
    at Object.emitWarning (/Users/X/Projects/Y/node_modules/webpack/lib/NormalModule.js:117:16)
    at /Users/X/Projects/Y/node_modules/postcss-loader/index.js:131:24
    at Array.forEach (native)
    at /Users/X/Projects/Y/node_modules/postcss-loader/index.js:130:31
 @ ./src/styles.sass 4:14-187
 @ multi ./src/styles.sass
```

**Comment by RaduGrama** [comment]
Looks like this was already discussed in #376

**Comment by trimox** [comment]
Hey @RaduGrama 
Yep, same warning messages. I've not seen much traction yet on the earlier issues filed from Angular CLI issue board. 

I'll leave the issue open to research any potential solution on our end.
-trimox

**Comment by trimox** [comment]
@RaduGrama and @Eski 

Found a hackable solution.

As there is no "official" way to provide Angular CLI a `postcss-custom-properties` config - yet.

Open `index.js` from your projects `node_modules\postcss-custom-properties\dist` folder
Find this line:
`warnings: options.warnings === undefined ? true : options.warnings,`

We're going to change warnings property from `true` to `false`.
`warnings: options.warnings === undefined ? false : options.warnings,`

Save and run `ng serve`
![image](https://user-images.githubusercontent.com/11887843/33078072-9a79fe40-ce9f-11e7-9717-dd5c545657b5.png)

**Comment by RaduGrama** [comment]
That fixes it. Thank you! I'll have to keep an eye on when that package updates and the warnings reappear, but that's better than missing on real warnings and/or errors due to the flood of postcss-custom-properties warnings.

**Comment by Eski** [comment]
That will do it for the moment but i hope that will get a fix soon.

**Comment by MrGrigri** [comment]
Here is what I have done in my project. That is until there's a fix. I have created a node post-install script that will replace the 'true' with a 'false'.

### package.json

```javascript
{
  ...
  "scripts": {
    ...,
    "postinstall": "node ./scripts/postcss-custom-properties.js"
  }
  ...
}
```

### postcss-custom-properties.js

```javascript
let fs = require('fs');

function changeFile(file, currLine, newLine) {
  if (!fs.existsSync(file)) return;
  let data = fs.readFileSync(file, 'utf8');
  let result = data.replace(currLine, newLine);

  fs.writeFile(file, result, err => {
    if (err) console.log(err);
  });
}

let package = './node_modules/postcss-custom-properties/dist/index.js';
let searchFileForString = 'warnings: options.warnings === undefined ? true : options.warnings,';
let replaceFileWithString = 'warnings: options.warnings === undefined ? false : options.warnings,';

changeFile(package, searchFileForString, replaceFileWithString);
```

**Comment by trimox** [comment]
Closing. `angular-cli` removed `postcss-custom-properties` recently.

reference: https://github.com/angular/angular-cli/commit/4827bd188b221a1097d7983b779e51a35e35291c

**Comment by judearasu** [comment]
Upgrade to latest angular cli and you won't find these warnings

**Comment by Nexeuz** [comment]
@judearasu  I have this angular/cli version and I still see this warning.

```
Angular CLI: 6.0.3
Node: 8.9.4
OS: darwin x64
Angular: 6.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cdk                      6.0.1
@angular/cli                      6.0.3
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.0.2
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
```
