### ISSUE TITLE
Prefilled text field label is not floated

### ISSUE THREAD

**Issue by pvamshi** [trimox/angular-mdc-web#410]
### What Angular MDC version are you using?
0.6.1
### What are the steps to reproduce the bug?
```html
<mdc-text-field  type="text" label="some label" formControlName="formcontrolname" >
</mdc-text-field>
```

Let the form control have a value preset 

### What is the expected behavior?
Label should be floated above the text field
![image](https://user-images.githubusercontent.com/1425006/33161811-f53dab62-d04b-11e7-92f8-6bab4b74331f.png)

### What is the actual behavior?
![image](https://user-images.githubusercontent.com/1425006/33161785-c728b050-d04b-11e7-8a44-5333fb83f0df.png)

**Comment by trimox** [comment]
Closing, fix merged. Thanks for reporting!
