### ISSUE TITLE
Mdc-select is not selected while using formControlName 

### ISSUE THREAD

**Issue by pvamshi** [trimox/angular-mdc-web#411]
### What Angular MDC version are you using?
0.6.1

### What are the steps to reproduce the bug?
```typescript

  demoForm: FormGroup;
  constructor(private fb: FormBuilder) {
    this.demoForm = fb.group({ food: ['fruit-3'] });

  }

```

```html
 <form [formGroup]="demoForm">
      <mdc-select #select placeholder="Favorite food" formControlName="food" name="food" [disabled]="isDisabled" [closeOnScroll]="closeOnScroll"
        (change)="handleChange($event)">
      <mdc-select-item *ngFor="let food of foods" [value]="food.value" [disabled]="food.disabled">
        {{food.description}}
      </mdc-select-item>
      </mdc-select>
    </form>
```
### What is the expected behavior?
Correct value should be selected 
![image](https://user-images.githubusercontent.com/1425006/33162041-6d60939c-d04d-11e7-9c0e-a6d1aac36cfe.png)

### What is the actual behavior?

![image](https://user-images.githubusercontent.com/1425006/33162051-8265841e-d04d-11e7-99ec-be91bd3ff1e2.png)

**Comment by trimox** [comment]
PR is almost ready.

**Comment by pvamshi** [comment]
Thanks for the hardwork :+1:

**Comment by trimox** [comment]
Reopening a clean PR to finish.

**Comment by trimox** [comment]
All set. I'm pushing the last of the commits for 0.6.2 inclusion.
