### ISSUE TITLE
bundle size is too big

### ISSUE THREAD

**Issue by metasong** [trimox/angular-mdc-web#416]
when used with angular cli, the prod build would include the material.es5.js(580.67k), which inclued all subcomponents, no mater what subcommponent modules you are really used.

it's too large!

we need to make the below code really meaningful:

@NgModule({
    imports: [
        MdcCoreModule, // required
        MdcFabModule,
        MdcMenuModule,
        MdcIconModule,
        MdcButtonModule,
        MdcCardModule
    ],
...

**Comment by trimox** [comment]
@metasong Thanks for reporting. My initial guess is it may be a problem with the latest Rollup version. Let ya know.

**Comment by trimox** [comment]
Wasn't an issue with latest rollup. PR incoming

**Comment by metasong** [comment]
@trimox thanks for your quick reaction!
waiting for your good reault!

**Comment by trimox** [comment]
Looking better? 😄 

![image](https://user-images.githubusercontent.com/11887843/33356367-17aa2418-d48a-11e7-8f86-3ed72eec8375.png)

Roughly 90% completed..Not much longer

**Comment by trimox** [comment]
@metasong Sneak peak of the upcoming build results + package layouts. Cleaning up PR and testing..

![packages](https://user-images.githubusercontent.com/11887843/33356790-87edaf2c-d48c-11e7-9f4f-156ffb06064c.gif)

**Comment by trimox** [comment]
PR is all set. Testing is looking good with CLI.

**Comment by metasong** [comment]
cool!
need to remove MdcCoreModule after upgrad to 0.6.2
