### ISSUE TITLE
Chips Component Request

### ISSUE THREAD

**Issue by jimbarrett33** [trimox/angular-mdc-web#421]
Is there a plan to implement a Chips component according to the MD spec.

It would be a great addition.

[https://material.io/guidelines/components/chips.html](https://material.io/guidelines/components/chips.html)

Thanks.

**Comment by trimox** [comment]
Hey @jimbarrett33 Unfortunately, MDC Chips Component has no due date in the [material-components-web - Milestone tracker](https://github.com/material-components/material-components-web/milestone/3). We're implementing some of the missing features as we can by extending the Angular MDC library with new component properties + features, and theme options.

I'll add Chips component to our feature requests; it'll be a fun component to design.

Below are the pending component feature requests _(in no order)_:
* Mini variant drawer - #158
* Expansion panels - https://material.io/guidelines/components/expansion-panels.htmlAuto-complete *
* Search Component - https://material.io/guidelines/patterns/search.html
* Date Picker: #392

**Comment by devlfm** [comment]
About search and chips and others, I'm thinking you could use [covalent](https://teradata.github.io/covalent/#/components/chips) as external components, that way you could stay focused on this..

**Comment by trimox** [comment]
@devlfm Agreed. Your suggestion is the best route atm. It's also one of the greatest benefits of component based programming, pick and choose what you need from individual libraries 😃

**Comment by devlfm** [comment]
@trimox the only down is that covalent is using @angular/material :( maybe a port would be better

**Comment by jimbarrett33** [comment]
@devlfm @trimox Thanks for the suggestions. Covalent seems to be a solid lib. Regarding the dependency on angular/material, the main thing I would be worried about is bundle size. I tested an Angular Cli app with the  Covalent Chip component and I did an AoT build. Is seems OK but it does add some bits. The fact that the Covalent release schedule is dependent on angular/material is another slight concern.

**Comment by trimox** [comment]
Good news. The `material-components-web` team began design on a chip component. 
reference: https://github.com/material-components/material-components-web/tree/experimental/chip

We'll incorporate the component once it's made available.

Closing request.
