### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by TeodorKolev** [trimox/angular-mdc-web#437]
### What Angular MDC version are you using?
angular-mdc/web: ^0.6.1
angular-mdc/theme: 0.0.8
### What browser(s) is this bug affecting?
all
### What OS are you using?
Ubuntu 17.04
### What are the steps to reproduce the bug?
just install on angular-cli
### What is the actual behavior?
ERROR in src/app/app.module.ts(16,3): error TS2305: Module .../node_modules/'@'angular-mdc/web/mdc has no exported member 'MdcCoreModule'. 
### Any other information you believe would be useful?
This is code from MdcCoreModule 
export * from './typings/index';

I believe it is not proper

**Comment by trimox** [comment]
Hey @TeodorKolev 
`MdcCoreModule` was removed in v0.6.2, so your installed package may have been updated. 
To view installed version: `npm view @angular-mdc/web version`

If you need v0.6.1: `npm i @angular-mdc/web@0.6.1 --save-dev`
