### ISSUE TITLE
Scrolling Temp drawer ripple problem

### ISSUE THREAD

**Issue by TeodorKolev** [trimox/angular-mdc-web#440]
### What Angular MDC version are you using?
0.6.2
### What browser(s) is this bug affecting?
all
### What OS are you using?
Ubuntu 17.04
### What are the steps to reproduce the bug?
Go to mobile view and start scroll temp drawer.
### What is the expected behavior?
Items background should be restored on mouseup 
### What is the actual behavior?
background stays and all touched items becomes grey, or whatever color is set

**Comment by trimox** [comment]
Yeah, problem is upstream in `material-components-web`. Before I implement a workaround, lemme see if   the MDC team is working on it.

**Comment by trimox** [comment]
I stumbled on the bug. Working on a fix

**Comment by trimox** [comment]
Resolved in #457

**Comment by TeodorKolev** [comment]
@trimox When we be able to see the fix?

**Comment by trimox** [comment]
@TeodorKolev Testing is going well, planning an update in a couple hours.

**Comment by trimox** [comment]
Reopening. Issue originating from `mdc-list-item`.

**Comment by TeodorKolev** [comment]
@trimox thank you

**Comment by trimox** [comment]
@TeodorKolev No prob. Updating to latest `material-components-web` today, and it'll be the next issue I resolve.

**Comment by trimox** [comment]
Good news. Upstream just opened a PR to resolve. https://github.com/material-components/material-components-web/pull/1800

**Comment by TeodorKolev** [comment]
Is it fixed already, should I install a new version or something?

**Comment by trimox** [comment]
Waiting for https://github.com/material-components/material-components-web/pull/1800 to be merged into `material-components-web` master branch. I plan to incorporate the change quickly.
