### ISSUE TITLE
Snackbar does not fade in when used in fetch

### ISSUE THREAD

**Issue by TonySpegel** [trimox/angular-mdc-web#474]
### What Angular MDC version are you using?
0.5.4
### What browser(s) is this bug affecting?
Chrome, FF (and others probably too)
### What are the steps to reproduce the bug?
Basic config
```
private snackBarOptions = {
    align: 'start',
    multiline: false,
    dismissOnAction: true,
    focusAction: true,
    actionOnBottom: false,
};

constructor(
    public snackBar: MdcSnackbar,
) { } 

``` 
called on click - this works every time
```
public showSnackbar() {
    this.snackBar.show(':)', 'Ok', this.snackBarOptions);
}
```
called in an error-handler - this **does not work**
```
public async fetchWeekLectures(calendarWeekNumber: number) {
    try {
        const response = await fetch(`../assets/json/${calendarWeekNumber}.json`);
        const responseJson = await response.json();

        return responseJson;
    } catch (errorMessage) {
        this.snackBar.show('errorMessage', 'Ok', this.snackBarOptions);
    }
} 
```
The fetched resource could be anything, i just called it with something which doesn't exist

### What is the expected behavior?
The snackbar fades in a smooth way
### What is the actual behavior?
The snackbar kind of jumps into the view and just fades out smoothly. When used without the start-alignment it jumps from the right side right into the center of flickers.

### Any other information you believe would be useful?
I believe that this isn't necessarily an issue with your library but well I don't know how to fix that in this context.

Whole code [here](https://gist.github.com/TonySpegel/93efe63472aa514a0f8a5606545fcb1b)
Thank you for your help

**Comment by trimox** [comment]
@TonySpegel Thanks for reporting. I've duplicated the issue using an internal application here, but I've not been able to duplicate using our demo-app. Just need to determine where the issue is originating from.

Are you using `FlexLayout`? If so, what version?

**Comment by TonySpegel** [comment]
@trimox  No I do not use FlexLayout (is that a utility css lib?). But I believe because I'm throwing an error in an asynchronous function or more because of the 'await'? Only throwing an error using 'throw false' inside my try block works fine. But using await in this scenario seems to to cause problems. 

Maybe we should file an issue at the original mdc web repo? But I somehow think it won't be heard there..

I could give you my repo if that helps?

**Comment by trimox** [comment]
I was able to resolve the issue in an internal app today. I refactored the app's `linear-progress` decision logic on whether to open or close a progress; it is all self-contained in an asynchronous function awaiting data. Does your project execute a similar method on it's presentation layer with the issue?

**Comment by TonySpegel** [comment]
It does not execute more than I've shown you yet. I've planned to use it to display if an asynchronous request has failed - or any other error has occurred. Despite that I've wanted to show it when a user stars an object in my app.

Is this something which can be avoided to happen?

**Comment by trimox** [comment]
@TonySpegel I've created a StackBlitz example for this issue.
https://stackblitz.com/edit/angular-mdc-snackbar-jkg9sh?file=app%2Fapp.component.ts

So, I really only noticed the reported issue if the snackbar was called from the `constructor`. If the snackbar was called from `AfterViewInit`, it fades in as expected.

Do you want to take a look and if so fork the example?

**Comment by trimox** [comment]
Think we got this one licked in the last update. Please let me know if not..

https://stackblitz.com/edit/angular-mdc-snackbar-jkg9sh?file=app%2Fapp.component.html
