### ISSUE TITLE
enum declarations member initializer must be constant expression

### ISSUE THREAD

**Issue by pvamshi** [trimox/angular-mdc-web#48]
I started a new project with @ angular/cli . 
Followed the getting started guide . 

`npm i --save @angular-mdc/web` 

Included Module in `app.module.ts` and started the application and getting this error  : 
```
ERROR in /home/vamshi/code/ngrx-crud-test/node_modules/@angular-mdc/web/menu/menu.component.d.ts (4,16): In ambient enum declarations member initializer must be constant expression.
/home/vamshi/code/ngrx-crud-test/node_modules/@angular-mdc/web/menu/menu.component.d.ts (5,17): In ambient enum declarations member initializer must be constant expression.
/home/vamshi/code/ngrx-crud-test/node_modules/@angular-mdc/web/menu/menu.component.d.ts (6,19): In ambient enum declarations member initializer must be constant expression.
/home/vamshi/code/ngrx-crud-test/node_modules/@angular-mdc/web/menu/menu.component.d.ts (7,20): In ambient enum declarations member initializer must be constant expression.

```

Not sure if I am doing something wrong.

**Comment by pvamshi** [comment]
Looks like typescript enums cant have strings. 
I removed the error by changing it to : 

```ts
export declare namespace MDC_OPEN_FROM {
    export const TOP_LEFT = "mdc-simple-menu--open-from-top-left";
    export const TOP_RIGHT = "mdc-simple-menu--open-from-top-right"
    export const BOTTOM_LEFT = "mdc-simple-menu--open-from-bottom-left";
    export const BOTTOM_RIGHT = "mdc-simple-menu--open-from-bottom-right";
}
```

**Comment by trimox** [comment]
@pvamshi, thanks for keeping up with the project! v0.2.1 was released today; including a refactor to our Menu `openFrom` code. We'll leave the issue open until we confirm it works with CLI.

Reference commit https://github.com/trimox/angular-mdc-web/commit/066294c579e517a1a0e66b5fe4832ea5f80156dc

**Comment by trimox** [comment]
Closing. Resolved ES5 package issue in `material.es5.js` and `material.es5.min.js`
Reference resolved issue https://github.com/trimox/angular-mdc-web/issues/67
