### ISSUE TITLE
Integration with mgechev/angular-seed

### ISSUE THREAD

**Issue by light9** [trimox/angular-mdc-web#504]
Thanks for awesome job!
Can you please help to integrate angular-mdc-web to [mgechev/angular-seed](https://github.com/mgechev/angular-seed)?
### What Angular MDC version are you using?
Master
### What browser(s) is this bug affecting?
Chrome
### What OS are you using?
Win 10
### What are the steps to reproduce the bug?
[https://github.com/mgechev/angular-seed/wiki/Add-external-dependency](Add-external-dependency)
### What is the expected behavior?
Usage of the best angular material ui library
### What is the actual behavior?
Module load failed
### Any other information you believe would be useful?
Looks like the same UMD module architecture and integration method as with  [https://github.com/mgechev/angular-seed/wiki/Integration-with-AngularMaterial2](Integration-with-AngularMaterial2), but it fails too.

**Comment by trimox** [comment]
@light9 Appreciated! Will take a look and let ya know.

**Comment by trimox** [comment]
Welp, maybe a little further.

First, insert as 1st line of `app.component.scss`
```scss
@import "@angular-mdc/theme/material";
```

Second, add import of `MdcButtonModule` to `shared.module.ts`
```ts
import { MdcButtonModule } from '@angular-mdc/web';

@NgModule({
  imports: [CommonModule, RouterModule, MdcButtonModule],
...
```

Insert this in `project.config.ts`
```ts
    this.addPackageBundles({
       name:'@angular-mdc/web',
       path:'node_modules/@angular-mdc/web/bundles/mdc.umd.js',
       packageMeta:{
         defaultExtension: 'js'
       },
     });
```

Unfortunately, a `SyntaxError: Unexpected token <` is presented.

**Comment by light9** [comment]
@trimox , I have the same error: 
> Unexpected token < is presented.

I guess it can help us: [Add external dependency](https://github.com/mgechev/angular-seed/wiki/Add-external-dependency) 

> Let's say you have a package your-package which has a your-package/index.d.ts importing and re-exporting some types, which are actually defined in your-package/dist/lib/index.js. Then import abc from 'your-package' must be resolved to import abc from 'your-package/dist/lib/index.js'. In such a case, using the main key is required. Otherwise, you get strange syntax errors when using gulp serve.dev (and only in dev mode!) in the JS console because node_modules/your-package is fetched resulting in the server returning index.html, which obviously doesn't parse as JS.

I tryed a lot of ways (including loading by separate component), but unfortunatelly index.d.ts in angular-mdc-web structure is not exist. Thanks a lot!

**Comment by trimox** [comment]
It might be an issue with the UMD bundling. Working on it.

**Comment by trimox** [comment]
Apologies for the delay, but PR #403 should resolve this. Will jump back and see confirm.

**Comment by trimox** [comment]
Let's retry with today's v0.31.1 release.

**Comment by trimox** [comment]
@light9 Got this working. Will write up instructions today..

**Comment by trimox** [comment]
#### Add this to`project.config.ts`
```ts
    const additionalPackages: ExtendPackages[] = [
      {
        name: '@angular-mdc/web',
        path: 'node_modules/@angular-mdc/web/bundles/web.umd.js',
        packageMeta: {
          defaultExtension: 'js'
        }
      }
    ];
    this.addPackagesBundles(additionalPackages);
```

#### Insert at top `app.component.scss`
```scss
@import "@angular-mdc/theme/material";
```

#### Set `ViewEncapsulation.None` on `AppComponent`
```ts
/**
 * This class represents the main application component.
 */
@Component({
  moduleId: module.id,
  selector: 'sd-app',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class AppComponent {
  constructor() {
    console.log('Environment config', Config);
  }
}
```

#### Import `MdcButtonModule` in `about.module.ts`
```ts
import { MdcButtonModule } from '@angular-mdc/web';

@NgModule({
  imports: [CommonModule, AboutRoutingModule, MdcButtonModule],
...
```

#### Add a button to `about.component.html`
```html
<button mdc-button [raised]="true">Angular MDC Button - Hello</button>
```

### Finish
Run `npm start -- --scss`

![image](https://user-images.githubusercontent.com/11887843/37245891-007f6018-246d-11e8-8932-627960a8b695.png)

**Comment by trimox** [comment]
Closing.
