### ISSUE TITLE
How to set state of Icon Toggle and Radio Button programmatically

### ISSUE THREAD

**Issue by TonySpegel** [trimox/angular-mdc-web#508]
### What Angular MDC version are you using?
0.5.4
### What browser(s) is this bug affecting?
All
### What are the steps to reproduce the bug?
I have two seperated issues
#### First one
I've two sets/groups of radio-buttons and the depending on which button has been clicked in the first group, I'd like to reset the second group and set the first button in this group ('all') to checked.
![rb](https://user-images.githubusercontent.com/1145514/34645689-85549dde-f354-11e7-85a2-86f7ac0b0eb6.jpg)

I basically tried to do this [checked]="rbFloorAll" by setting my template variable rbFloorAll

```
<!-- Buildings -->
<div (click)="switchAvailableFloors($event)" class="form__radio">
    <!-- Couple of these as shown in the image above -->
    <mdc-form-field>
        <label>all</label>
            <mdc-radio value="all" name="radioBuildings" [checked]="true"></mdc-radio>
    </mdc-form-field>
</div>

<!-- Floors -->
<div class="form__radio">
    <label>Floors</label>
    <div class="form__radio__wrapper">
        <mdc-form-field>
            <label>all</label>
            <mdc-radio
                id="floor-all"
                value="all"
                name="radioFloors"
                [checked]="rbFloorAll"
            >
            </mdc-radio>
        </mdc-form-field>
    </div>
</div>

@Component({
    selector: 'filter-menu',
    templateUrl: './filter-menu.component.html',
    styleUrls: ['./filter-menu.component.scss']
})
export class FilterMenuComponent {
    public rbFloorAll: true;

    /**
     * Switches the available floors depending
     * on the users selected building.
     *
     * Building | Floors
     *    1     | all           1   2   3
     *    2     | all               2   3
     *    3     | all   -1  0   1   2   3
     *    4     | all   -1  0   1   2   3
     *    5     | all   -1  0   1   2   3
     *
     * @param radioButtonBuilding
     */
    public switchAvailableFloors(radioButtonBuilding) {
        const buildingNumber = radioButtonBuilding.target.value;
        const radioGroupFloors = document.querySelector('#variable-floors');
        const radioButtonFloorAll: any = document.querySelector('#floor-all');

        // Both methods won't work:

        // 1.
        // Template-variable
        this.rbFloorAll = true;

        // 2.
        radioButtonFloorAll.checked = true;`

        // Other not relevant code
    }
}
```
#### The second one
I'd like to set the state of an Icon-Toggle depending on the value of a key in an object. I store these objects in an array and iterate over them in my template. If my property is true, I'd like to set the corresponding start-fav-icon toggle to be checked. I know that there's a toggle-Method but how do I uses this in a template?

![icon-toggle](https://user-images.githubusercontent.com/1145514/34645809-573fcaec-f357-11e7-80ba-33082c710339.png)
This wold be the desired result if index 0 would be true.
Sth. like [toggleState] in templates would be usefule.

Thank you for your help :)

**Comment by trimox** [comment]
@TonySpegel Sorry for the delay, just returning this week. Will review and get back with you today.

**Comment by TonySpegel** [comment]
@trimox Don't worry. I really appreciate your work. I wouldn't be able to use MDC at all without it.

**Comment by trimox** [comment]
@TonySpegel Thanks!

Let's start with `icon-toggle` first. Two paths for maintaining icon state are via `NgModel` and the `toggle(bool)` method atm. If we add a `checked: boolean` property, it'd allow you to control icon state via a binding. 

Btw, love the card design!

**Comment by trimox** [comment]
@TonySpegel PR for `on: boolean` in `icon-toggle` just merged https://github.com/trimox/angular-mdc-web/pull/555

**Comment by trimox** [comment]
@TonySpegel  did #812 resolve this for ya?

**Comment by trimox** [comment]
Closing. We can re-open if needed.
