### ISSUE TITLE
Question: What is the best practice for adding a background image to the toolbar with waterfall=true and fixedLastRow=true, which will fade out behind the last row as the window scrolls up?

### ISSUE THREAD

**Issue by marcusrichards** [trimox/angular-mdc-web#510]
### What Angular MDC version are you using?
`"@angular-mdc/web": "^0.6.6",
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14",
    "material-components-web": "^0.27.0"`
### What browser(s) is this bug affecting?
Chrome
### What OS are you using?
Windows 10
### What are the steps to reproduce the bug?
` <mdc-toolbar [flexible]="isFlexible" [fixed]="isFixed" [waterfall]="isWaterfall" [fixedLastrow]="isFixedLastRow"
    style="flex-shrink: 0" mdc-elevation=3>
      <mdc-toolbar-row>
          <mdc-toolbar-section [alignStart]="true">
              <a href="#/toolbar-demo" mdc-toolbar-menu-icon material-icon>menu</a>
              <mdc-toolbar-title>Applied Machine Learning</mdc-toolbar-title>
          </mdc-toolbar-section>
      </mdc-toolbar-row>
      <mdc-toolbar-row>
          <mdc-toolbar-section [alignEnd]="true">
              <a href="#/toolbar-demo" mdc-toolbar-icon material-icon>file_download</a>
              <a href="#/toolbar-demo" mdc-toolbar-icon material-icon>print</a>
              <a href="#/toolbar-demo" mdc-toolbar-icon material-icon>bookmark</a>
          </mdc-toolbar-section>
      </mdc-toolbar-row>
  </mdc-toolbar>`

### What is the expected behavior?
Would like to add a fading background image to the toolbar.
### What is the actual behavior?
Behaving as expected but would like to implement as demo: **Waterfall Toolbar Fix Last Row** in [https://material-components-web.appspot.com/toolbar/index.html](https://material-components-web.appspot.com/toolbar/index.html)
### Any other information you believe would be useful?
Framework is behaving really nicely, thanks. Couple of minor things - I had to put your sass compiler warning message workaround for root. And followed advice of your refactoring of the build, to get material-icon to work I added import {
  ... MdcMaterialIconModule
} from '@angular-mdc/web'; 
This wasn't in demo app as you were using Core.

No other problems - this is a great project 👍

**Comment by trimox** [comment]
@blaketastic2 Great question.

I created an example on StackBlitz for you. Let me know if you have any additional questions.
https://stackblitz.com/edit/angular-mdc-toolbar

You'll want to view `app/app.component.html` and `styles.scss` specifically.

**Comment by trimox** [comment]
@marcusrichards Great question.

I created an example on StackBlitz for you. Let me know if you have any additional questions.
https://stackblitz.com/edit/angular-mdc-toolbar

You'll want to view `app/app.component.html` and `styles.scss` specifically.

**Comment by marcusrichards** [comment]
Great - thanks 👍 That does the job! 

Actually naming the class .mdc-toolbar__row it seems to get applied automatically to the first row by the selector.

Slightly annoying is that unless the window is narrow the title does not quite scroll up to align top with the menu icon on the left. This is the same behaviour in the material components web example. I tried playing around with lineheight and margins - the image aligns top but the text aligns bottom with some offset. Not a big deal but it means you can't really use the title on the same line as the icons!! Not pretty, don't know if it is worth raising with material web.

![waterfallscroll](https://user-images.githubusercontent.com/34490856/34720942-a3f0b364-f538-11e7-8b23-c6a4a53b2f4b.PNG)

**Comment by trimox** [comment]
Not a problem! Glad to help. Will file separate issue with material team.

**Comment by trimox** [comment]
@marcusrichards Just an update. I resolved the `mdc-toolbar-title` alignment issue for flexible Toolbar in v0.7.5 today. 
https://github.com/trimox/angular-mdc-web/blob/master/CHANGELOG.md
