### ISSUE TITLE
AngularFlex required ?

### ISSUE THREAD

**Issue by rubenCodeforges** [trimox/angular-mdc-web#524]
Looks like AngularFlexLayout is required , if not provided the layout will be broken , see demo-drawer

**Comment by trimox** [comment]
Hi @rubenCodeforges 
`@angular/flex-layout` is not a requirement to use the library. Can you elaborate a bit on what is broken?

Checkout the StackBlitz project below for a Drawer that does not include `@angular/flex-layout`.
https://stackblitz.com/edit/angular-mdc-drawer

**Comment by trimox** [comment]
Closing.

**Comment by rubenCodeforges** [comment]
@trimox because in the drawer example you are using this `import {ObservableMedia} from '@angular/flex-layout';` 

```
constructor(public media: ObservableMedia) {
    }
```

**Comment by rubenCodeforges** [comment]
I just saw that your demo app is using it `https://github.com/trimox/angular-mdc-web/blob/master/src/demo-app/navigation/app-toolbar.ts`
