### ISSUE TITLE
Toolbar title cannot be read fully on mobile

### ISSUE THREAD

**Issue by touficbatache** [trimox/angular-mdc-web#56]
Hey,
When I visited your demo site, I only saw "Angular ..." as title in the toolbar. If you want it to show fully, add `mdc-toolbar__section--shrink-to-fit` as a class to the section that contains the github icon. Take a look at [this](https://github.com/material-components/material-components-web/blob/master/packages/mdc-toolbar/README.md#sections)
Hope it helps

**Comment by trimox** [comment]
@touficbatache, thanks! Looks much cleaner. 
Incase anyone else encounters this in the future..
```
    <mdc-toolbar-section [alignEnd]="true" [shrinkToFit]="true">
```

**Comment by trimox** [comment]
@touficbatache, wondering if you have any suggestions to make the Toolbar demo more dynamic. Switching between the different checkbox options, doesn't seem to fire off recalculations on the Toolbar if (fixed, waterfall and flexible are checked). Debugging the MDC Toolbar code, it may not be performing recalculations. 
Any thoughts?
