### ISSUE TITLE
Is Angular MDC web have "Layout Grid" ?

### ISSUE THREAD

**Issue by ljcucc** [trimox/angular-mdc-web#576]
I would like to use a component call **layout grid** which is inside MDC web.
but how could I using this component with **Angular MDC web**? or this component is not available on **Angular MDC web**

https://material.io/components/web/catalog/layout-grid/

Thanks!

**Comment by trimox** [comment]
Yep! `layout-grid` is included with the `@angular-mdc/theme` dependency. You can start using it as documented by the material team.
```html
<div class="mdc-layout-grid">
  <div class="mdc-layout-grid__inner">
    <div class="mdc-layout-grid__cell"></div>
    <div class="mdc-layout-grid__cell"></div>
    <div class="mdc-layout-grid__cell"></div>
  </div>
</div>
```

**Comment by anupanup2001** [comment]
> Yep! `layout-grid` is included with the `@angular-mdc/theme` dependency. You can start using it as documented by the material team.
> 
> ```
> <div class="mdc-layout-grid">
>   <div class="mdc-layout-grid__inner">
>     <div class="mdc-layout-grid__cell"></div>
>     <div class="mdc-layout-grid__cell"></div>
>     <div class="mdc-layout-grid__cell"></div>
>   </div>
> </div>
> ```

The theme demo link from Readme.md file points nowhere. https://trimox.github.io/angular-mdc-web/#/theme-demo It would be good to have a demo for this. Also if this is mentioned in the Getting started, it would be very useful!

**Comment by trimox** [comment]
Thanks for reporting this! Will assign a new issue for theme documentation.
