### ISSUE TITLE
Add Data table component

### ISSUE THREAD

**Issue by SerkanSipahi** [trimox/angular-mdc-web#587]
hi there,
first of all, thank you for your awesome work :)

Question:
Is there a data table component for `trimox/angular-mdc-web` like that `https://material.angular.io/components/table/overview` ?

**Comment by trimox** [comment]
Funny timing. Was experimenting with a data table component based off the Cdk and `material-components-web` over the weekend :)

Definitely going to happen

**Comment by trimox** [comment]
Closing for now. Focusing on component refactoring and enhancements.

**Comment by petplan-Pat** [comment]
any hopes of bringing this back into the road map?
