### ISSUE TITLE
'mdc-select' should not trigger 'change' event when default value is set

### ISSUE THREAD

**Issue by pvamshi** [trimox/angular-mdc-web#591]
### What Angular MDC version are you using?
0.7.3
### What are the steps to reproduce the bug?
```html
<mdc-select #select placeholder="Favorite food" [(ngModel)]="selectedValue" name="food"
 [disabled]="isDisabled" (change)="handleChange($event)">
  <mdc-select-item *ngFor="let food of foods" [value]="food.value" [disabled]="food.disabled">
    {{food.description}}
  </mdc-select-item>
</mdc-select>
```
```ts
 selectedValue: string = 'pizza-1';

  foodControl = new FormControl();

  foods = [
    { value: 'steak-0', description: 'Steak' },
    { value: 'pizza-1', description: 'Pizza' },
    { value: 'tacos-2', description: 'Tacos is disabled', disabled: true },
    { value: 'fruit-3', description: 'Fruit' },
  ];

  handleChange(event: { index: number, value: any }) {
    console.log("selection changed , value: "+  event.value);
    this.eventIndex = event.index;
    this.eventValue = event.value;
  }
```

### What is the expected behavior?
Since the user did not change any value by selecting from the dropdown, change event should not be triggered
### What is the actual behavior?
change is event is triggered. 

### Any other information you believe would be useful?
In my case,  when I select something from dropdown, I navigate to different page by changing the url param.  I set the value in dropdown from router params . 
Now this leads to infinite loop. 
I can prevent this by comparing selected value and original value . But thought this is not right behavior. Let me know if its expected behavior .

**Comment by trimox** [comment]
Agree, behavior is incorrect.

**Comment by trimox** [comment]
@pvamshi please reference PR https://github.com/trimox/angular-mdc-web/pull/600.

Adds `selectionChange` event, firing only if selected item has been chosen by the user.
