### ISSUE TITLE
Make 'mdc-select' style backward compatible

### ISSUE THREAD

**Issue by pvamshi** [trimox/angular-mdc-web#623]
With new styling to 'mdc-select' we are displaying the placeholder. In few instances we do not want to show placeholder for select . We should probably add a config property to turn on/off the placeholder.

**Comment by trimox** [comment]
Researching clean approach to hiding placeholder. Will post pics.

**Comment by trimox** [comment]
### Floating label on
![image](https://user-images.githubusercontent.com/11887843/36415607-86d46190-15f4-11e8-8d3b-467670b4841e.png)

### Floating label off
![image](https://user-images.githubusercontent.com/11887843/36415625-915eda14-15f4-11e8-84ef-7f82a888c2ea.png)
