### ISSUE TITLE
List items with *ngFor stay highlighted when clicked

### ISSUE THREAD

**Issue by JPtenBerge** [trimox/angular-mdc-web#637]
### What Angular MDC version are you using?
0.7.5.

### What browser(s) is this bug affecting?
All browsers on my machine. Currently running Chrome 63, Edge 16 and Firefox 57.

### What OS are you using?
Windows 10.

### What are the steps to reproduce the bug?
[I've reproduced it on StackBlitz](https://stackblitz.com/edit/angular-mdc-list-pv8d6y). It's a pretty straight-forward `<mdc-list>` with `<mdc-list-item>`'s bound with an `*ngFor`.

### What is the expected behavior?
When I click item #&#xfeff;1, that item is highlighted. When I then click item #&#xfeff;3, that item should be highlighted and the highlight on item #&#xfeff;1 should be removed.

### What is the actual behavior?
Highlights are never removed. Only when the `*ngFor` notices a change in data and the list gets rerendered, the highlight disappear. 

### Any other information you believe would be useful?
None.

// Edit: Yes, I do. For whatever reason, if I place an `*ngIf` on the `<mdc-list>`, it behaves as expected. `<mdc-list *ngIf="items.length > 0">`. I've updated my StackBlitz example with this.

**Comment by trimox** [comment]
Thanks for the StackBlitz reproduction! Pretty sure I see the problem. Let ya know.
