### ISSUE TITLE
mdc-menu is not positioned over mdc-tab

### ISSUE THREAD

**Issue by JPtenBerge** [trimox/angular-mdc-web#638]
### What Angular MDC version are you using?
0.7.5.

### What browser(s) is this bug affecting?
All browsers on my machine. Currently running Chrome 63, Edge 16 and Firefox 57.

### What OS are you using?
Windows 10.

### What are the steps to reproduce the bug?
[I've reproduced it in StacakBlitz](https://stackblitz.com/edit/angular-mdc-list-nbczww). I have an `<mdc-toolbar>` with two rows, In the first row on the top right I have a pullout menu (`<mdc-menu>`). In the second row I have an `<mdc-tab-bar>` with two `<mdc-tab>`'s in it.

### What is the expected behavior?
That the pullout menu is always placed on top of the tab bar.

### What is the actual behavior?
It's the other way around. The tab bar is placed over the pullout menu, causing the first item not to be selectable. The text of the first menu item is also malformed a bit if the screen is small enough and the tab bar wide enough.

### Any other information you believe would be useful?
I've attached a screenshot of me hovering over the first menuitem. You can see that the second tab is lighting up:
![screenshot](https://user-images.githubusercontent.com/3285470/36049911-c5e1bc6a-0de4-11e8-9a3c-797fd2611b8e.png)

Also, I solved it for now using
```css
.mdc-toolbar__section {
	z-index: initial;
}
```

But I'm not yet familiar enough with MDC to know what consequences this will have.

**Comment by trimox** [comment]
Thanks for reporting this.
I'll have to submit a PR upstream to resolve, but we can extend MDC Sass to fix it in the short-term.
