### ISSUE TITLE
'mdc-select' doesn't set the value for formGroup/formControl

### ISSUE THREAD

**Issue by pvamshi** [trimox/angular-mdc-web#640]
In the demo page for mdc-select, the value is not updated when the select option is selected . Its the same for formGroup 
https://stackblitz.com/edit/angular-mdc?embed=1&file=app/select-demo.html

**Comment by trimox** [comment]
Thanks for reporting this. I've fixed internally and testing.

**Comment by pvamshi** [comment]
Thankyou . Sorry for the trouble ..

**Comment by trimox** [comment]
No trouble :)

Embarrassed I didn't catch it!
