### ISSUE TITLE
Integration with AngularClass/angular-starter

### ISSUE THREAD

**Issue by AKlaus** [trimox/angular-mdc-web#67]
Unfortunately, I wasn't able to integrate _angular-mdc-web_ with [AngularClass/angular-starter](https://github.com/AngularClass/angular-starter) due to the following issue:

```
File to import not found or unreadable: @material/animation/variables.
Parent style sheet: C:/Dev/WebUI/node_modules/@material/button/mdc-button.scss
```

Process Monitor showed me that WebPack is looking for the file in wrong folders - either `\node_modules\@material\button\@material\animation\` or `@material\animation\variables` of the project root, when the actual location is `\node_modules\@material\animation\`.

BTW, I had to add the `~` to the `@import '~material-components-web/material-components-web';`  and all the `@material` references in the `material-components-web.scss` (e.g. `@import "~@material/animation/mdc-animation";`), so it gets checked under the `node_modules` folder.

Perhaps, it's not an issue of _angular-mdc-web_, but if you could give me some ideas on fixing the problem, it would be very appreciated.

**Comment by trimox** [comment]
@AKlaus, interesting. Tell ya what, I'll clone the repo and let you know what I find later today.

**Comment by trimox** [comment]
I'm pretty sure it's a missing config option in the [AngularClass/angular-starter](https://github.com/AngularClass/angular-starter) repo's Webpack file. I should have a definitive answer for you in a bit..

Something similar to our demo-app's [webpack.dev.js](angular-mdc-web/config/webpack/webpack.dev.js) may help..
`
loader: 'sass-loader
  options: {
    includePaths: ['node_modules', 'node_modules/@material/*']
  }
`

**Comment by trimox** [comment]
@AKlaus, got it :)

**Step 1**: Install glob in angular-starter 
Console: `npm i glob`

**Step 2**: Edit `angular-starter/config/webpack.dev.js`
Replace these lines
`
          test: /\.scss$/,
          use: ['style-loader', 'css-loader', 'sass-loader'],
          include: [helpers.root('src', 'styles')],
`

With these lines
`
          use: [
            'style-loader',
            'css-loader', {
              loader: 'sass-loader',
              options: {
                includePaths: ['../node_modules', '../node_modules/@material/*']
                  .map((d) => path.join(__dirname, d))
                  .map((g) => glob.sync(g))
                  .reduce((a, c) => a.concat(c), [])
              }
            },
          ]
`

**Step 3**: Create a `/src/app/styles/mdc.scss` file.
Add one line that imports the MDC styles.
```css
@import "material-components-web/material-components-web";
```

**Step 3**: Import Angular MDC and mdc.scss into `app.module.ts`
```ts
import { MaterialModule } from '@angular-mdc/web';
import '../styles/mdc.scss';
```

**Screengrab of MDC Button and Checkbox running in** [AngularClass/angular-starter](https://github.com/AngularClass/angular-starter)

![image](https://user-images.githubusercontent.com/11887843/28871734-e6664974-7753-11e7-9242-8a19bc8b8873.png)

**Comment by AKlaus** [comment]
Thank you for the solution! 
I would like to extend your answer for completeness sake.

The [angular-starter](https://github.com/AngularClass/angular-starter) comes with a bunch `config/webpack.***.js` configurations, the answer above is fine for the `dev` and `test` files:
```
{
  test: /\.scss$/,
  use: ['style-loader',
           'css-loader',
           {
             loader: 'sass-loader',
             options: {
               /*
                * Handle Material Components styles
                */
                includePaths: ['../node_modules', '../node_modules/@material/*']
                      .map((d) => path.join(__dirname, d))
                      .map((g) => glob.sync(g))
                      .reduce((a, c) => a.concat(c), [])
             }
           }
         ],
  include: [helpers.root('src', 'styles')]
}
```
However, the `prod` configuration would be slightly different due to using `extract-text-webpack-plugin`:
```
{
  test: /\.scss$/,
  loader: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [{ loader: 'css-loader' },
          { loader: 'sass-loader',
            options: {
                /*
                * Handle Material Components styles
                */
                includePaths: ['../node_modules', '../node_modules/@material/*']
                  .map((d) => path.join(__dirname, d))
                  .map((g) => glob.sync(g))
                  .reduce((a, c) => a.concat(c), [])
              }
          }
          ],
  }),
  include: [helpers.root('src', 'styles')]
},
```

**Comment by geoHeil** [comment]
@AKlaus  thangs for pointing me to this thread.

Running `npm run build:prod` fails for me with
```
ERROR in main.b58e227a12a0273c4236.bundle.js from UglifyJs
Unexpected token: name (EventRegistry) [main.b58e227a12a0273c4236.bundle.js:73889,6]
```

**Comment by trimox** [comment]
@geoHeil Hey, please check the Angular MDC version installed. If it's not v0.2.6, please run the following 
`npm i @angular-mdc/web@latest` 

If you encounter the same message on v0.2.6, please let me know. I'll take care of this asap.

**Comment by trimox** [comment]
I see the problem, working on resolution..

**Comment by trimox** [comment]
Got it guys. ES5 support seems to be working 100%, along with UMD and ES2015.

`npm i @angular-mdc/web@latest`

It should install v0.2.7

**Comment by geoHeil** [comment]
@trimox thanks. Can confirm that it works now.

**Comment by joradom** [comment]
hello, same problem with an angular 4 project generate with angular-cli. please any workaround?

**Comment by trimox** [comment]
@joradom Sure, I'll create a new issue for investigating angular-cli generation issues.

**Comment by sandangel** [comment]
can be solve with angular-cli config:
under style: [
  style.scss
]
add stylePreprocessorOptions: {
  includePaths: [
    "../node_modules"
  ]
}

**Comment by AKlaus** [comment]
## Bug
@trimox, my sincere apology, but I'm reporting a follow-up issue on the `AngularClass/angular-starter + MDC-Web` integration.
The described above solution worked well at the time, but since a new version of [MDC](https://github.com/material-components) was released, it generates the following compilation error:
```
ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js?{"includePaths":["C:/Users/AKlaus/Downloads/1/node_modules","C:/Users/AKlaus/Downloads/1/~/@material/animation","C:/Users/AKlaus/Downloads/1/~/@material/auto-init","C:/Users/AKlaus/Downloads/1/~/@material/base","C:/Users/AKlaus/Downloads/1/~/@material/button","C:/Users/AKlaus/Downloads/1/~/@material/card","C:/Users/AKlaus/Downloads/1/~/@material/checkbox","C:/Users/AKlaus/Downloads/1/~/@material/dialog","C:/Users/AKlaus/Downloads/1/~/@material/drawer","C:/Users/AKlaus/Downloads/1/~/@material/elevation","C:/Users/AKlaus/Downloads/1/~/@material/fab","C:/Users/AKlaus/Downloads/1/~/@material/form-field","C:/Users/AKlaus/Downloads/1/~/@material/grid-list","C:/Users/AKlaus/Downloads/1/~/@material/icon-toggle","C:/Users/AKlaus/Downloads/1/~/@material/layout-grid","C:/Users/AKlaus/Downloads/1/~/@material/linear-progress","C:/Users/AKlaus/Downloads/1/~/@material/list","C:/Users/AKlaus/Downloads/1/~/@material/menu","C:/Users/AKlaus/Downloads/1/~/@material/radio","C:/Users/AKlaus/Downloads/1/~/@material/ripple","C:/Users/AKlaus/Downloads/1/~/@material/rtl","C:/Users/AKlaus/Downloads/1/~/@material/select","C:/Users/AKlaus/Downloads/1/~/@material/selection-control","C:/Users/AKlaus/Downloads/1/~/@material/slider","C:/Users/AKlaus/Downloads/1/~/@material/snackbar","C:/Users/AKlaus/Downloads/1/~/@material/switch","C:/Users/AKlaus/Downloads/1/~/@material/tabs","C:/Users/AKlaus/Downloads/1/~/@material/textfield","C:/Users/AKlaus/Downloads/1/~/@material/theme","C:/Users/AKlaus/Downloads/1/~/@material/toolbar","C:/Users/AKlaus/Downloads/1/~/@material/typography"]}!./src/styles/styles.scss
Module build failed:
undefined
          ^
      Invalid style specified! Choose one of primary, accent, background, text-primary-on-primary, text-secondary-on-primary, text-hint-on-primary, text-disabled-on-primary, text-icon-on-primary, text-primary-on-accent, text-secondary-on-accent, text-hint-on-accent, text-disabled-on-accent, text-icon-on-accent, text-primary-on-background, text-secondary-on-background, text-hint-on-background, text-disabled-on-background, text-icon-on-background, text-primary-on-light, text-secondary-on-light, text-hint-on-light, text-disabled-on-light, text-icon-on-light, text-primary-on-dark, text-secondary-on-dark, text-hint-on-dark, text-disabled-on-dark, text-icon-on-dark
      in C:\Users\AKlaus\Downloads\1\node_modules\@material\theme\_mixins.scss (line 26, column 12)
 @ ./src/styles/styles.scss 4:14-134
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts
```

## Steps to reproduce

1. Have a clean `AngularClass/angular-starter`
1. Install  [MDC-Wev](https://github.com/material-components/material-components-web)
1. Build

**Comment by trimox** [comment]
@AKlaus Unfortunately, I cannot recommend MDC v0.18 at this time. A related issue is open on the MDC site [issue 1165](https://github.com/material-components/material-components-web/issues/1165), and hopefully this gets taken care of soon. 

Just a heads up. Angular MDC installs a compatible MDC dependency automatically.
```
  "dependencies": {
    "material-components-web": "0.17.0"
  }
```
Let's try to remediate the issue you're encountering...
1. Remove the `node_modules` folder
2. Delete `package-lock.json` file.
3. Edit your `package.json`, and remove `material-components-web` if found. 
4. Open console : `npm i`

Hope this helps!

**Comment by AKlaus** [comment]
@trimox, unfortunately, these steps won't help as the root cause is coming from components under the `@material` folder and the `material-components-web` package doesn't refer to particular version and lists versions with the `^` prefix, which brings the "wrong" version.

**Comment by trimox** [comment]
@AKlaus Yikes, this is a mess. Here's another related issue for v0.18 and conflicting dependencies.
reference : [#1134](https://github.com/material-components/material-components-web/issues/1134)

We need stricter control over our dependencies. 
Gimme a bit, need to think on this. 🤔

**Comment by trimox** [comment]
Created issue (feature request): #94 
To ensure compatibility going forward, an optional package for MDC's CSS will be made available (e.g. `@angular-mdc/web-sass`)

**Comment by trimox** [comment]
Closing. MDC v0.19.0 resolves versioning problems.

**Comment by AKlaus** [comment]
Can confirm, it's working now.
Thank you @trimox, for your help!
