### ISSUE TITLE
Add Expansion panels

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#686]
Expansion panels contain creation flows and allow lightweight editing of an element.

spec reference: https://material.io/guidelines/components/expansion-panels.html

**Comment by evaletolab** [comment]
Hello, 
how to proceed to implement a new component? Is there a bootstrap code, or should I start with one existant on the ./lib that seems "similar"  ?

**Comment by trimox** [comment]
Hey @evaletolab 

Start with `material-components-web` authoring components reference.
https://github.com/material-components/material-components-web/blob/master/docs/authoring-components.md

If you have any questions please feel free to ask.
-trimox

**Comment by evaletolab** [comment]
@trimox , I'm wondering how to deal with the implementation available from material2. Regarding source code for [expender](https://github.com/angular/material2/blob/master/src/lib/expansion/expansion-module.ts) it sounds like the component mainly (or only) depends on cdk, it could be imported in a almost straightforward way? But maybe, it would be better to use / mix both implementations in a efficient way. Do you have some suggestions ?
