### ISSUE TITLE
In order to use MDC component, there needs to be an Angular Component wrapper around each?

### ISSUE THREAD

**Issue by rjsteinert** [trimox/angular-mdc-web#7]
Just passing through, am I reading this right that for every MDC Component you need to also make an Angular Component like https://github.com/trimox/angular-mdc-web/blob/master/src/components/button/button.ts ?

**Comment by trimox** [comment]
If you're planning to use the component with Angular, React or another framework, a wrapper is the way to go. It's pretty sweet because you can also use the components with straight JS or vanilla html..

**Comment by trimox** [comment]
Closing issue. If you have any other questions, feel free to ask or visit the MDC repo https://github.com/material-components/material-components-web
Thanks!
