### ISSUE TITLE
feat: Transpile material-components-web during build

### ISSUE THREAD

**Issue by PlatanoBailando** [trimox/angular-mdc-web#708]
I'm inquiring as to the reason that from version 0.6.1 to version 0.6.2 the target of the tsconfig was changed from es5 to es2015.  It appears this causes issues with Internet Explorer compatibility.  Indeed the Angular MDC Web demo page crashes on opening the page in IE 11.

**Comment by PlatanoBailando** [comment]
Slight update.  It appears the issue doesn't necessarily have to do with the target in the tsconfig (although that is confusing), but more to do with the material-components-web javascript files getting included as is into the build.  If one is using the angular cli, for example, then those javascript files get included as is into the vendor.bundle.js  Prior to 0.6.2 this did not occur.

**Comment by trimox** [comment]
Appreciate you taking the time to find the `tsconfig` problem. :+1:  Great timing, prepping new build.

You brought up a good point. Currently, each `material-components-web` package is set as a Rollup global. If we instead we set each as an external, it allows consuming apps to decide.

**Comment by trimox** [comment]
I had a few minutes while waiting for the build of v0.31.0 to complete. To clear up the confusion on `tsconfig`, we downlevel to both ES2015 and ES5 using separate Rollup bundles. Let me know if it's still unclear.

`angular-cli` has a flag specifically to remove vendor code from apps. Run the following, and do let me know if it's not working.
>  ng build --prod --build-optimizer

**Comment by PlatanoBailando** [comment]
Running the `angular-cli` using `ng build --prod --build-optimizer` does not remove the offending code.  As near as I can tell, [this](https://www.npmjs.com/package/@angular-devkit/build-optimizer) is what that flag does in the cli.  None of what's in there does any downgrading to es5 unfortunately.  In addition to that, it doesn't remove 3rd party code from the build.  What it does is instead of placing 3rdparty code into a separate vendor.bundle.js, it places it into main.bundle.js with the app code.

**Comment by trimox** [comment]
Makes sense. Experimenting with build transpiling `material-components-web`, would you be interested in testing?

**Comment by PlatanoBailando** [comment]
Sure I can do that.

**Comment by trimox** [comment]
Sorry for the delay. While working on this issue, I stumbled on a fix for https://github.com/trimox/angular-mdc-web/issues/568

Internal testing looking good!

**Comment by trimox** [comment]
PR incoming..

**Comment by trimox** [comment]
Updated our demo site using transpiled version, and Internet Explorer 11 works now.

**Comment by PlatanoBailando** [comment]
Awesome, I look forward to trying it out.

**Comment by trimox** [comment]
Published. UMD build working great with StackBlitz.

**Comment by trimox** [comment]
@PlatanoBailando Thanks again for bringing this to my attention. Much appreciated.
