### ISSUE TITLE
Chrome Autofill covers outline text field

### ISSUE THREAD

**Issue by jdeanwaite** [trimox/angular-mdc-web#711]
### What Angular MDC version are you using? 
**0.31.0**

### What browser(s) is this bug affecting? 
**Chrome**

### What OS are you using? 
**MacOS High Sierra**

### What are the steps to reproduce the bug?

1. Create a form with inputs named "email" and "password". Set outlined to true.
2. Use the form so Chrome remembers your input.
3. Go back to the page, see chrome clobber the outline and label of the outlined textfield.

### What is the expected behavior?

1. The label and outlines of the field should remain visible through Chrome's autofill.

### What is the actual behavior?

2. The label and outlines are covered up by Chrome's ugly yellow box.

### Any other information you believe would be useful?

![screen shot 2018-02-22 at 2 25 46 pm](https://user-images.githubusercontent.com/8517615/36567878-caa00b92-17dc-11e8-9a4d-e50372895d7b.png)

As you can see in the screenshot, most of the field has been clobbered by the yellow box. A hack does exist to eliminate the yellow on inputs:

```
mdc-text-field {
  /deep/ {
    @-webkit-keyframes autofill {
      to {
        color: #666;
        background: transparent;
      }
    }

    input:-webkit-autofill {
      -webkit-animation-name: autofill;
      -webkit-animation-fill-mode: both;
    }
  }
}
```

This successfully hides the yellow box, but feels very hacky (obtained from [this](https://stackoverflow.com/a/37432260/4216035) SO post)

**Comment by trimox** [comment]
Yikes, that's a problem. I'm testing a workaround, will update thread in a bit.

**Comment by trimox** [comment]
Proving to be a challenge..

[Paul Kinlan](https://paul.kinlan.me/detecting-when-autofill-happens/) has a viable solution. In the end, I may have to fix upstream in `material-components-web`.

**Comment by jdeanwaite** [comment]
Thanks for the updates, that hack I'm using is working up on Chrome but doesn't work in safari so far. You would think that the Material Design team would have already worked through something like this.

**Comment by trimox** [comment]
Minor update from upstream.
https://github.com/material-components/material-components-web/issues/2802

**Comment by trimox** [comment]
Closing. Issue being tracked upstream.

https://github.com/material-components/material-components-web/issues/2802
