### ISSUE TITLE
Trouble theming angular-mdc-web into my project

### ISSUE THREAD

**Issue by cpru2** [trimox/angular-mdc-web#712]
### What Angular MDC version are you using?
That latest
### What browser(s) is this bug affecting?
Chrome
### What OS are you using?
Mac OS Sierra
### What are the steps to reproduce the bug?
So I am really enjoying the modularity of angular-mdc so far in our angular-cli project, but am having trouble theming components in one go. It seems like every time I add a new component, I must re-declare colors, despite setting my primary and secondary theme colors before importing the library into my main SCSS file.

Here is an example.

HTML:

```
<mdc-drawer drawer='permanent'>
	<div class='mdc-layout-grid__inner'>
		<div class='mdc-layout-grid__cell--span-1'>
		</div>
		<div class='mdc-layout-grid__cell--span-10 space-between-y vh-100'>
			<tabs></tabs>
		</div>
		<div class='mdc-layout-grid__cell--span-1'>
		</div>
	</div>
</mdc-drawer>

```
SCSS:

```
/* colors */
$cod-gray: rgb(26, 26, 26);
$athens-gray: rgb(245, 245, 247);

// primary
$mdc-theme-primary: $cod-gray;

// secondary
$mdc-theme-secondary: $athens-gray;

@import "~@angular-mdc/theme/material";
```

### What is the expected behavior?
I would expect text color to follow the theme colors set initially across components. As you can see in my SCSS, I've chosen a dark theme with a black background and white text. 

### What is the actual behavior?
Each time I add a new component (like "tabs") the default color is set to black. 

### Any other information you believe would be useful?
I've imported the library after variable declarations, but before class overrides.

**Comment by trimox** [comment]
@cpru2 You're Sass is correct for setting a primary and secondary theme color. However, primary/secondary **theme** color is not primary/secondary **text.**

The former refers to the primary/secondary theme color that is used to establish a visual identity and color many parts of your application. The latter refers to the style of text that is most prominent (low opacity, high contrast), and used to display most content.

To customize the ink color of any part of the `tab`, use the following mixins. 

#### `mdc-tab-ink-color`
Use this mixin to set the color of all ink on the tab.

#### `mdc-tab-icon-ink-color`
This mixin customizes the icon ink color.

#### `mdc-tab-label-ink-color`
This mixin customizes the label ink color.

#### `mdc-tab-bar-indicator-ink-color`
This mixin customizes the indicator ink color.

### Example
```sass
.demo-toolbar--with-tab-bar {
  .mdc-tab:not(.mdc-tab--active) {
    @include mdc-tab-ink-color(rgba(mdc-theme-prop-value(text-primary-on-primary), 0.54));
  }

  .mdc-tab--active,
  .mdc-tab:hover {
    @include mdc-tab-ink-color(text-primary-on-primary);
  }
}
```

For `tab-bar`, we have `primary` and `secondary` properties; however ink is only applied on the indicator. I'm thinking we need `primary: boolean` and `secondary: boolean` on `tab` as well to set the label and icon ink?

**Comment by trimox** [comment]
Closing. PR #720 adds `primary` and `secondary` properties to `mdc-tab-bar`.
