### ISSUE TITLE
Dynamically populating tabs with scroller

### ISSUE THREAD

**Issue by EdwinChua** [trimox/angular-mdc-web#720]
### What Angular MDC version are you using?
0.31.0

### What browser(s) is this bug affecting?
Chrome, Firefox

### What OS are you using?
Ubuntu 17.04

### What are the steps to reproduce the bug?

1. If ngFor is used to populate the tabs dynamically from an API call, the scroll-forward and scroll-back arrows don't show up. 

2. Also, `[primary]` and `[secondary]` options cause the tabs to become black/gray. Leaving them out doesn't help either

 Code chunk placed in mdc-toolbar:
```html
  <mdc-tab-bar-scroller *ngIf="tags != null">
    <mdc-tab-bar-scroll-back>
      <mdc-icon>navigate_before</mdc-icon>
    </mdc-tab-bar-scroll-back>
    <mdc-tab-bar-scroll-frame *ngIf="tags != null && tags.length > 0">
      <mdc-tab-bar>
        <mdc-tab [routerLink]="['/']"><mdc-tab-icon-text>Home</mdc-tab-icon-text></mdc-tab>
        <mdc-tab *ngFor="let tag of tags" [active]="tag.tag == categoryTag"><mdc-tab-icon-text>{{tag.tag}}</mdc-tab-icon-text></mdc-tab>
      </mdc-tab-bar>
    </mdc-tab-bar-scroll-frame>
    <mdc-tab-bar-scroll-forward>
      <mdc-icon>navigate_next</mdc-icon>
    </mdc-tab-bar-scroll-forward>
  </mdc-tab-bar-scroller>
```
### What is the expected behavior?

1. Arrows show up correctly
2.  Text and indicator were initially white (upgraded from version 0.7.1)

### What is the actual behavior?

1. Arrows are not appearing till window is resized.
2.  Text and indicator are black/gray

### Any other information you believe would be useful?

1. Interim solution to get the arrows to show up is to simulate a window resize event after the API call is made
```typescript
ngOnInit() {
        this.webCallsService.getTags().subscribe(tags => {
        this.tags = tags;
        if (isPlatformBrowser(this.platformId)) {
            window.dispatchEvent(new Event('resize')); // helps the arrow on the scroller show up
        }
    });
}
```

**Comment by trimox** [comment]
@EdwinChua Thanks for reporting.

> Arrows are not appearing till window is resized.
- Duplicated. Will fix.

> Text and indicator are black/gray
- See answer and example: https://github.com/trimox/angular-mdc-web/issues/712

**Comment by EdwinChua** [comment]
@trimox thanks 😁

i saw #712, but i've no idea how to use mixins, so i'll probably kiv it for now.

**Comment by trimox** [comment]
No problem. Using Angular CLI? If so, just make sure the project is set to use `scss`.
Copy the example code from #712, apply class name on a `tab-bar`. 

If ya have questions, please do let me know.
