### ISSUE TITLE
Popup for mdc select menu showing on right instead of centered

### ISSUE THREAD

**Issue by ajonesb** [trimox/angular-mdc-web#722]
### What Angular MDC version are you using?
angular-mdc/web: 0.31.0
### What browser(s) is this bug affecting?
Chrome
### What OS are you using?
Windows 10
### What are the steps to reproduce the bug?
clicking on mdc-select-surface to show a dropdown,  popup dropdown shows on the right, not centered to the parent of mdc-select. 
### What is the expected behavior?
Popup should show in the middle not show on the right. 
### What is the actual behavior?
Popup is showing on the right instead of centered in the middle. 
### Any other information you believe would be useful?
trying to modify:

mdc-select-menu {
    width: 50rem;
    top: 90.5px;
    transform-origin: center 0px 0px;
    /* left: 614px; */ removed

**Comment by trimox** [comment]
@ajonesb I've not been able to duplicate yet. By chance is the `mdc-select` inside a dialog?

Could you duplicate on [StackBlitz](https://stackblitz.com/edit/angular-mdc?embed=1&file=app/select-demo.html)?

**Comment by trimox** [comment]
Anyone else duplicated?

**Comment by trimox** [comment]
Closing. If we need to reopen, we can.
