### ISSUE TITLE
Demo site's drawers don't work on IE 11

### ISSUE THREAD

**Issue by gline9** [trimox/angular-mdc-web#731]
### What Angular MDC version are you using?
v0.31.1

### What browser(s) is this bug affecting?
IE 11

### What OS are you using?
Windows 7

### What are the steps to reproduce the bug?
Navigate [here](https://trimox.github.io/angular-mdc-web/#/drawer-demo) in IE 11.
The drawers look like they are loosing focus and display space but they don't disappear from the view

### What is the expected behavior?
The drawers shouldn't be visible when they are collapsed.

### What is the actual behavior?
The drawers are visible when they are collapsed

### Any other information you believe would be useful?
![image](https://user-images.githubusercontent.com/25394791/36845783-a71b276a-1d1d-11e8-9309-0c4d318ac695.png)

**Comment by gline9** [comment]
After some additional testing it looks like this is only an issue on release builds.

**Comment by trimox** [comment]
Thanks for reporting and testing. Any luck figuring it out? If not, I'll take a look.

**Comment by gline9** [comment]
I haven’t found the underlying reason. For now we are using a workaround where we give the drawer display: none when it doesn’t contain the class mdc-drawer—open on IE. This, however, will remove the animation for the drawer, but for IE we don’t care.

**Comment by trimox** [comment]
Glad you got a workaround, I'll take a look.

IE11, the web just can't get rid of it :smile:

**Comment by trimox** [comment]
@gline9 Ok, been testing. Interesting results..

I modified `demo-app`'s webpack config to transpile to es5 in `production` mode. The drawers worked as good as expected for IE11. 

I then took and moved all `demo-app`'s code (minus `webpack` of course) into an `angular-cli` project;  drawers were broken just as you described.

I'm throwing up a `help-wanted` for anyone willing to do some research.

**Comment by trimox** [comment]
@gline9 Fixed. Including as part of v0.34.5 release later today.
