### ISSUE TITLE
Prefilled Select is set as dirty

### ISSUE THREAD

**Issue by inradius** [trimox/angular-mdc-web#733]
### What Angular MDC version are you using?
v0.31.0
### What browser(s) is this bug affecting?
Tested in Chrome only
### What OS are you using?
Mac High Sierra
### What are the steps to reproduce the bug?
https://stackblitz.com/edit/angular-mdc-d4gfwj
### What is the expected behavior?
The prefilled form should leave the form's dirty value as false until the user makes a change.
### What is the actual behavior?
Prefilling the select causes the form to become dirty right away.
### Any other information you believe would be useful?
I use the form's dirty state to determine if the user has changed a value in a form. If the user does change something then tries to navigate away, they are shown a dialog to confirm that they want to navigate away without saving. Since the mdc select is set to dirty right away, the user will see this dialog even if they didn't make a change to the form.

**Comment by trimox** [comment]
Fixed. PR incoming
