### ISSUE TITLE
How to style various elements w/o mdc-theme-dark

### ISSUE THREAD

**Issue by TonySpegel** [trimox/angular-mdc-web#739]
### What Angular MDC version are you using?
0.31.1
### What browser(s) is this bug affecting?
All

### 

As of version [0.31.0](https://github.com/trimox/angular-mdc-web/blob/f00bd5cbb1b0656456f42e14c9fca121ba996703/CHANGELOG.md#0310-2018-02-21) it's not longer possible to use mdc-theme-dark to automatically change an elements colors. It's recommended doing this in Sass. 

However I can't figure out how to style input elements at all.
The element in question is a radio-button
```
<mdc-form-field>
    <label>all</label>
    <mdc-radio class="tsp" value="all" name="radioBuildings" [checked]="true"></mdc-radio>
</mdc-form-field>
```
And i tried to style it like this - which is the selector used by MDC, also adding an additional class to be more specific
```
.tsp.mdc-radio .mdc-radio__native-control:enabled:not(:checked) + .mdc-radio__background .mdc-radio__outer-circle {
    border-color: red;
}
```

I'm applying styles by using the components decorator styleUrls: ['./filter-menu.component.scss'] which is in the same dir as the template and controller. However I can't find these rules to be overwritten by MDC Styles at all. The same applys for basic textfield inputs

### Expected behaviour
An "easy" way to style input elements

### Suggestion
Examples along the documentation for these elements

**Comment by trimox** [comment]
Hey @TonySpegel, great question.

It's actually pretty easy.

#### Style `checked` & `unchecked`
```sass
.tsp {
  $color: $material-color-red-500;

  @include mdc-radio-unchecked-stroke-color($color);
  @include mdc-radio-checked-stroke-color($color);
}
```

#### Kitchen sink (everything)
```sass
.tsp {
  $color: $material-color-red-500;

  @include mdc-radio-unchecked-stroke-color($color);
  @include mdc-radio-checked-stroke-color($color);
  @include mdc-radio-ink-color($material-color-orange-500);
  @include mdc-radio-focus-indicator-color($color);
  @include mdc-states($color);
}
```

I'll be sure to add custom color examples for each component to help out.
-trimox

**Comment by TonySpegel** [comment]
Thank you! This looks indeed pretty easy. Is there a list available for these variables?
I'll try this asap today.

**Comment by trimox** [comment]
Not a problem. I'll include as part of future documentation but here's the related Sass.

[Material Design Color Palette](https://github.com/trimox/angular-mdc-web/blob/master/src/theme/material-components-web/theme/_color-palette.scss)
[Mixins for Radio button](https://github.com/trimox/angular-mdc-web/blob/master/src/theme/material-components-web/radio/_mixins.scss)

**Comment by TonySpegel** [comment]
I'm sorry but I'm not seeing a effect using either of these methods.
I have a main styles.scss file located at
```
"styles": [
    "theme/styles.scss"
]
```
styles.scss includes as mentioned in your docs these lines:
```
$mdc-theme-primary: #e91e63;
$mdc-theme-secondary: #e91e63;

@import '~@angular-mdc/theme/material';
```

and one stylesheet in each component. In this case it's filter-menu.component.scss.
Here I had to include ```@import '~@angular-mdc/theme/material';``` too to use these variables.

I've put this in my file:
```
.tsp {
    $color: $material-color-red-500;

    @include mdc-radio-unchecked-stroke-color($color);
    @include mdc-radio-checked-stroke-color($color);
    @include mdc-radio-ink-color($material-color-orange-500);
    @include mdc-radio-focus-indicator-color($color);
    @include mdc-states($color);
}
```
```
<mdc-form-field>
    <label>all</label>
    <mdc-radio class="tsp" value="all" name="radioBuildings" [checked]="true"></mdc-radio>
</mdc-form-field>
```
But the all radio box doesn't change at all.
Anything wrong with this approach?

**Comment by trimox** [comment]
@TonySpegel Couple suggestions. Again, a lot depends on `angular-cli` and`webpack` configurations.

For your approach, set `styleUrls` and `encapsulation: ViewEncapsulation.None` in `app.component.ts` or equivalent.
```ts
@Component({
  selector: 'app-root',
  template: '<app-layout></app-layout>',
  styleUrls: ['./theme/styles.scss')],
  encapsulation: ViewEncapsulation.None,
})
```

You may need to import these at the top of `filter-menu.component.scss`.
```sass
@import '~@angular-mdc/theme/material-components-web/theme/mixins';
@import '~@angular-mdc/theme/material-components-web/radio/mixins';
 ```

**Comment by TonySpegel** [comment]
To wrap this up: key is to use ```encapsulation: ViewEncapsulation.None``` as well as the provided mixins. Using these mixins is the easiest way styling the MDC components. The last two ansers of @trimox are basically the answer to this thread. Thanks again! :)
