### ISSUE TITLE
material-components-web dependencies are no longer in the package.json

### ISSUE THREAD

**Issue by JSMike** [trimox/angular-mdc-web#769]
### What Angular MDC version are you using?
0.31.1

### What browser(s) is this bug affecting?
N/A

### What OS are you using?
OSX + Docker (Linux)

### What are the steps to reproduce the bug?
update from 0.31.0 to 0.31.1 and npm install, then try to run code the depends on material-component-web.

You can view the difference in dependencies by running on the npm CLI

```
$ npm view @angular-mdc/web@0.31.0 dependencies
{ '@angular-mdc/theme': '0.31.0',
  'material-components-web': '0.31.0',
  tslib: '^1.9.0' }

$ npm view @angular-mdc/web@0.31.1 dependencies
{ '@angular-mdc/theme': '0.31.0' }

```

### What is the expected behavior?
`material-components-web` should be installed as a dependency of `@angular-mdc/web`

### What is the actual behavior?
material-components-web isn't set as a dependency in the package.json for `@angular-mdc/web`

### Any other information you believe would be useful?
I was assuming that we should rely on the version of material-components-web that's required by `@angular/mdc-web` in order to ensure that the versions are in sync. This isn't something that I expected to change in a patch version.

**Comment by trimox** [comment]
@JSMike We now transpile `material-components-web`'s javascript into each of our library bundles (e.g.: line-ripple), which takes the burden off consumers to transpile dependencies javascript themselves. With this approach the version matching is performed during `@angular-mdc/web`'s build process to prevent version mismatches on consumer systems.

>  then try to run code the depends on material-component-web.

Can you elaborate on what happens? If our library is missing a `material-components-web` package, just let me know.

For the time being, you could include `material-components-web` as a developer dependency of your project now without impacting `@angular-mdc/web`.

If I misunderstood the question, please let me know.

**Comment by JSMike** [comment]
In our case it was more about theming and scss. We run our own customizations/overrides by pulling in the stylesheets from @material, which was getting pulled in by material-components-web, which was getting pulled in by `@angular-mdc` to keep all of the versions in-line.

**Comment by trimox** [comment]
@JSMike Ah gotcha. I'd imagine you could switch from `@material/*` to  `@angular-mdc/theme` for stylesheets, since it's the same scss, mixins, functions etc..

Let me know if that works, or if I can help in some fashion.

**Comment by trimox** [comment]
Feel free to checkout history on this https://github.com/trimox/angular-mdc-web/issues/67. The long and short, an upstream versioning problem led us to provide an _optional_ import of the scss.

**Comment by JSMike** [comment]
Yea we suffered through the same `material-components-web` versioning issues, but shouldn't this be resolved now that all of the `@material/*` versions match the `material-components-web` version?

**Comment by JSMike** [comment]
Actually, nm, just double checked, they still aren't fixing the versions problems that they're having with material-components-web.... all those ^

```
$ npm view material-components-web dependencies

{ '@material/animation': '^0.25.0',
  '@material/auto-init': '^0.32.0',
  '@material/base': '^0.29.0',
  '@material/button': '^0.32.0',
  '@material/card': '^0.32.0',
  '@material/checkbox': '^0.32.0',
  '@material/chips': '^0.32.0',
  '@material/dialog': '^0.32.0',
  '@material/drawer': '^0.30.0',
  '@material/elevation': '^0.28.0',
  '@material/fab': '^0.32.0',
  '@material/floating-label': '^0.32.0',
  '@material/form-field': '^0.32.0',
  '@material/grid-list': '^0.30.0',
  '@material/icon-toggle': '^0.32.0',
  '@material/layout-grid': '^0.24.0',
  '@material/line-ripple': '^0.32.0',
  '@material/linear-progress': '^0.30.0',
  '@material/list': '^0.32.0',
  '@material/menu': '^0.31.0',
  '@material/radio': '^0.32.0',
  '@material/ripple': '^0.32.0',
  '@material/rtl': '^0.30.0',
  '@material/select': '^0.32.0',
  '@material/selection-control': '^0.32.0',
  '@material/slider': '^0.32.0',
  '@material/snackbar': '^0.30.0',
  '@material/switch': '^0.32.0',
  '@material/tabs': '^0.32.0',
  '@material/textfield': '^0.32.0',
  '@material/theme': '^0.30.0',
  '@material/toolbar': '^0.32.0',
  '@material/top-app-bar': '^0.32.0',
  '@material/typography': '^0.28.0' }
```

**Comment by JSMike** [comment]
ok, thank you for the update/background info, I updated our project to pull the scss from `@angular-mdc/theme/material-components-web/*` in place of `@material/*`. I'll close this for now and reach out if I run into any issues.
