### ISSUE TITLE
Enable setting different types for mdc-text-field

### ISSUE THREAD

**Issue by cpru2** [trimox/angular-mdc-web#773]
### What Angular MDC version are you using?

Current

### What browser(s) is this bug affecting?

All

### What OS are you using?

MacOs

### What are the steps to reproduce the bug?

1. Create input using <mdc-text-field></mdc-text-field>. 

```
<mdc-text-field
        class="waypoint"
        [(ngModel)] = "waypoint.dt"
        #step></mdc-text-field>

```
2. Set type property to "number". 

```
<mdc-text-field
        type="number"
        class="waypoint"
        [(ngModel)] = "waypoint.dt"
        #step></mdc-text-field>
```

3. Submit [(ngModel)]="property" and log to console.

```
onSubmit() {
    console.log(waypoint.dt);
}
```
4. Type number input into field.

5. See now that the type has been converted from a number to a string. 

```
Waypoint {
    dt: "2"
}
```

### What is the expected behavior?

I would expect to be able to set the type to anything just like the HTML5 input element. But currently, can only set the type to a string. 

### What is the actual behavior?

The type logs as a string, which means I need to parse the data before it is usable to our backend. This is ok if every type in the object is the same (a bunch of strings I want to convert to numbers), but makes things more complicated when I have to map over an object with different input types.

### Any other information you believe would be useful?

Not really, this is more of a new feature request.

**Comment by cpru2** [comment]
could this be implemented by just changing the type from "string" to  "string | number", or would this break things? https://github.com/trimox/angular-mdc-web/blob/master/src/lib/textfield/text-field.ts

**Comment by trimox** [comment]
@cpru2 Yep, agree. I'll tackle this next.

**Comment by trimox** [comment]
Duplicated. Let ya know in a bit.

**Comment by cpru2** [comment]
Yay thank you!

**Comment by trimox** [comment]
@cpru2 All set. 

PR #794

**Comment by cpru2** [comment]
Hey — just tested on my end, but am still seeing the number input convert to a string. I tested with a regular input again, and the value returns correctly as a number. Would this have anything to do with me binding to ngModel instead of the value property of mdc-text-field?

**Comment by trimox** [comment]
Hrmm. No, it should not matter. Binding with `ngModel` or `FormsControl` the values are bridged via `ControlValueAccessor`, and `FormsControl` returns a `number`. Not sure why `ngModel` is not. 

Let me convert our new FormControl example to ngModel, let ya know.

**Comment by trimox** [comment]
@cpru2 I've added additional examples, including an example numeric ngModel form. 
Hope this helps.

**Comment by sunmarjo** [comment]
I've encountered the same problem as of today.
When using `mdc-text-field` and `type="number"` with the `[(ngModel)]` two way bindings banana in the box, it still returns a string.

**Comment by trimox** [comment]
Thanks for reporting this. I'll take a look now

**Comment by trimox** [comment]
Duplicated. Thought this was resolved but it's not.

**Comment by trimox** [comment]
@sunmarjo Well, I thought this was a problem with our library but it's not. Angular currently doesn't support type checking in the property binding and event bindings.

Please reference this open issue for angular: https://github.com/angular/angular/issues/16952

You could do the following,
```ts
import { toNumber } from '@angular-mdc/web';

// and convert the value using mdc-text-field (change) event
onChange(value: string) {
  this.banana = toNumber(value);
}
```

**Comment by trimox** [comment]
@sunmarjo @cpru2 I stand corrected. Did more research, and got this working as expected. Pushing PR in a few..
