### ISSUE TITLE
Bug: Menu (Handling selection events)

### ISSUE THREAD

**Issue by MrGrigri** [trimox/angular-mdc-web#79]
# Bug: Menu

According to [Material Design Components - Web](https://material.io/components/web/catalog/menus/#handling-selection-events) The selection event should not only include the index but also include the item as an HTML Element. 

Currently, the repo only returns the index. I am needing this for my project because the menu items perform different actions and the list is dynamic. So I don't know the index but will have an ID for each item. In turn, by returning the item as well, I will be able to target that ID and then act upon it. 

![image](https://user-images.githubusercontent.com/4528551/29325021-70c0f732-81a3-11e7-9dde-8bc83af54cb7.png)

Thanks for all that you do and for providing this amazing middleware repository. 

---
#### Angular MDC - Web (0.2.5)

**Comment by trimox** [comment]
@MrGrigri Appreciate your support! Thank you for filing the issue, just submitted a PR.
