### ISSUE TITLE
chore: Update node-sass to 4.8.3 and fix ripple regression #2459

### ISSUE THREAD

**Issue by atmosuwiryo** [trimox/angular-mdc-web#825]
material component web v0.33.0 contains this issue: 

> $opacity sass variable value not compiled

[#2410](https://github.com/material-components/material-components-web/issues/2410)
and
[#2458](https://github.com/material-components/material-components-web/issues/2458)

solved by this pull request
[#2459](https://github.com/material-components/material-components-web/pull/2459)

fixed on just released material component web v0.34.0

quick fix:
update
`node_modules/@angular-mdc/theme/material-components-web/ripple/_mixins.scss`
from
`--mdc-ripple-fg-opacity: $opacity;`
to
`--mdc-ripple-fg-opacity: #{$opacity};`

**Comment by trimox** [comment]
@atmosuwiryo Yep, another quick fix is downgrading `node-sass` to 4.7.2 for the time-being.

I'm evaluating v0.34.0, and starting a development branch today.

**Comment by atmosuwiryo** [comment]
> Yep, another quick fix is downgrading node-sass to 4.7.2 for the time-being.

A better quick fix.

> I'm evaluating v0.34.0, and starting a development branch today.

Awesome.
