### ISSUE TITLE
Add display: block to .mdc-list to apply padding

### ISSUE THREAD

**Issue by visurel** [trimox/angular-mdc-web#826]
### What Angular MDC version are you using?
0.33.0
### What browser(s) is this bug affecting?
All
### What OS are you using?
Windows
### What are the steps to reproduce the bug?
Create a `<mdc-list>` and take a look at the padding. In the .mdc-list class the style is set as `padding: 8px 0;` but it's not being displayed because the <mdc-list> element has no display property.

StackBlitz:
https://stackblitz.com/edit/angular-mdc-list-yk4dcn

**Comment by trimox** [comment]
@visurel Sorry, I've been unable to duplicate. Could you fork the StackBlitz project and demonstrate the issue? Any assistance to duplicate is appreciated.

https://stackblitz.com/edit/angular-mdc-list

**Comment by visurel** [comment]
@trimox Added a StackBlitz: https://stackblitz.com/edit/angular-mdc-list-yk4dcn

**Comment by trimox** [comment]
PR incoming.
