### ISSUE TITLE
Using a Component inside MdcList breaks interactive behaviour

### ISSUE THREAD

**Issue by visurel** [trimox/angular-mdc-web#829]
### What Angular MDC version are you using?
0.33.0
### What browser(s) is this bug affecting?
All
### What OS are you using?
Windows
### What are the steps to reproduce the bug?
https://stackblitz.com/edit/angular-mdc-list-7n3ty5
### What is the expected behavior?
The "activated" + "selected" states should update correctly and add + remove the states.
### What is the actual behavior?
The "activated" state is added on click, but not removed on click on another item.

**Comment by trimox** [comment]
Thanks for the StackBlitz example, taking a look.

**Comment by trimox** [comment]
All set, PR incoming.
