### ISSUE TITLE
Discuss creating an Angular MDC - Showcase App

### ISSUE THREAD

**Issue by trimox** [trimox/angular-mdc-web#83]
Is there interest in creating a seed app? Some of the larger starter kits are a bit overwhelming for newcomers, and it'd be awesome to show what's possible with MDC.

The [demo-app](https://github.com/trimox/angular-mdc-web/tree/master/src/demo-app) is more or less meant for docs, testing components, and soon will undergo a presentation facelift to api/examples.

Wanted to open this up to discussion, in case there was other feedback.

**Comment by jibbers42** [comment]
> it'd be awesome to show what's possible with MDC

It sounds like you want something that is interesting to look at and dig into, not just a starter - is that right?

I tend to think of "seed" apps and "starters" as more of a template - something pretty bare bones that has the dependencies and structure already set up.

[demo-app](https://github.com/trimox/angular-mdc-web/tree/master/src/demo-app) probably would make a nice name if you wanted to rename that one to "test-app" or something.

Teradata calls their app a [quickstart](https://github.com/Teradata/covalent-quickstart) - that's not a bad name.

Maybe call it a "showcase" app?

Anyway, back to the point; whether it's just a simple starter or a full blown quickstart/showcase app, I think having something that shows how to properly setup and get started with this library is probably a good idea.

**Comment by trimox** [comment]
@jibbers42 Great feedback! I really like the idea of a "showcase" app with architectural best practices.  It would be an opportunity to demonstrate MDC's flexible customization and wide range of innovative possibilities. 
_changing issue title to "Showcase App"_

**Comment by pvamshi** [comment]
Should we have that as another repo or a part of this like demo-app

**Comment by trimox** [comment]
@pvamshi Sorry!! I didn't see your question before today ugh.
Great question. I'm open to feedback on both options. I can say some benefits of using this repo is I know the community would support and maintain the code. We could also offer it under our existing npm scope (e.g.: `@angular-mdc/showcase-app`) if needed.

Great question, thanks again!

**Comment by trimox** [comment]
Closing. Thanks for the feedback! Going to start by renaming demo-app.
