### ISSUE TITLE
Trailing comma in demo-app/tsconfig.json

### ISSUE THREAD

**Issue by agiledigits** [trimox/angular-mdc-web#837]
Someone submitted this repo to angulardoc.org for analysis, but the analyzer couldn't parse this file ((https://github.com/trimox/angular-mdc-web/blob/master/src/demo-app/tsconfig.json) because there is a trailing comma at line 18.

**Comment by trimox** [comment]
All set. Thanks!

**Comment by agiledigits** [comment]
Thanks for the quick turnaround! The repo is now on angulardoc.org: https://angulardoc.org/home/detail/github/88184430/angular2/%252F/summary
