### ISSUE TITLE
input field with ngModel cannot reset input field after setting value to '' or 0 

### ISSUE THREAD

**Issue by 3lhagvaasuren** [trimox/angular-mdc-web#848]
### What Angular MDC version are you using?
^0.33.1
### What browser(s) is this bug affecting?
google chrome
### What OS are you using?
windows 10
### What is the expected behavior?
resetting input field after setting value to '' or 0
### What is the actual behavior?
input field stays with the old value

**Comment by trimox** [comment]
Hi @3lhagvaasuren, thanks for reporting. I'm assuming this is for `mdc-select`? 
Could you fork the associated StackBlitz to demonstrate?
https://stackblitz.com/edit/angular-mdc-select

**Comment by 3lhagvaasuren** [comment]
hi @trimox. It's not for only mdc-select textfields also don't work.

**Comment by trimox** [comment]
Duplicated. Fixing

**Comment by trimox** [comment]
@3lhagvaasuren For a temporary solution, use `MdcTextField`'s `setValue('')` method.

**Comment by trimox** [comment]
All set. PR is #861.
