### ISSUE TITLE
Base-level rules cannot contain the parent-selector-referencing character '&'. theme/material-components-web/checkbox/_mixins.scss

### ISSUE THREAD

**Issue by grmaciel** [trimox/angular-mdc-web#873]
### What Angular MDC version are you using?
Latest one 
### What OS are you using?
MacOS

### What are the steps to reproduce the bug?
Just try to run the project that was working before

**Comment by trimox** [comment]
Hey @grmaciel, I've tried duplicating with demo-app and a quick cli app to no avail. Could you provide  development environment (e.g.: angular-cli), and dependency versions?

**Comment by trimox** [comment]
@grmaciel Thank you. Just need the `@angular/cli` version? 

Also, v0.34.4 was published yesterday if you'd like to try it.

**Comment by trimox** [comment]
@grmaciel I tested on a brand new `@angular/cli` project, no issues. If you have a repo, I can take a look.

**Comment by trimox** [comment]
Closing. Can be reopened if needed.
