### ISSUE TITLE
Toolbar displays beneath the drawer

### ISSUE THREAD

**Issue by MogauGeeky** [trimox/angular-mdc-web#892]
### What Angular MDC version are you using?
0.34.4

### What browser(s) is this bug affecting?
Google Chrome Version 66.0.3359.117
### What OS are you using?
Windows 10 64bit
### What are the steps to reproduce the bug?
Download the drawer example from here https://stackblitz.com/edit/angular-mdc-drawer
and run it on your local, note this issue persists even when I am reproducing the steps from a clean angular cli project.

### What is the expected behavior?
The placement of the toolbar and drawer behavior to be the same as the example.

### What is the actual behavior?
The drawer does not push the content and toolbar down leaving a huge white space

### Any other information you believe would be useful?

![image](https://user-images.githubusercontent.com/10864511/39060390-838828c2-44c1-11e8-8c93-977b9f672450.png)

**Comment by trimox** [comment]
@MogauGeeky Thank you for reporting this. I'll take a look.

**Comment by trimox** [comment]
I've upgraded the StackBlitz example to v0.34.4, if you'd like to re-pull. Pretty sure this is an invalid display property, will investigate.

**Comment by trimox** [comment]
Duplicated. Working on a fix now.

**Comment by trimox** [comment]
@MogauGeeky Published v0.34.5

**Comment by MogauGeeky** [comment]
@trimox Sorry for the delayed response, I pulled the latest stackblitz example and everything is working as expected. Thanks for your help
