### ISSUE TITLE
Text Field as a FormControl: clearing the text field does not propagate as a change to the form control value

### ISSUE THREAD

**Issue by ibelenski** [trimox/angular-mdc-web#939]
The issue can be observed in the text field [stackblitz demo](https://stackblitz.com/edit/angular-mdc-text-field) (Text Field - FormControl) in Chrome.

To reproduce:

1. Type some text in the Username field.

![2](https://user-images.githubusercontent.com/8331406/39580287-ceb51086-4eb6-11e8-9e6e-e23ea425b5bc.png)

2.  Use the backspace key to delete all characters but one; observe the Value changing.

![3](https://user-images.githubusercontent.com/8331406/39580328-eca78574-4eb6-11e8-9e5b-6fb139c212f7.png)

3. Tap the backspace key once more to delete the last remaining character; the Value should change to blank and the Valid status should revert to false but they don't.

![4](https://user-images.githubusercontent.com/8331406/39580456-3ab201e0-4eb7-11e8-8186-c7f2f5880c84.png)

**Comment by Capt-Lance** [comment]
I'm having the same issue in a project I am working on. Going from any value to an empty value in an `mdc-text-field` causes the value to not change via` [(ngModel)]`. I am using `@angular-mdc/web@0.34.5`.

**Comment by trimox** [comment]
@ibelenski @Capt-Lance Thanks for reporting this. I've duplicated, and PR will be available in a few.

**Comment by colin-davis** [comment]
I was looking into this also. Seems to be cause by:
line 450 (and 454) of `lib/text-field/text-field.ts`

```
  if (this.value) {
      this._onChange(this.value);
  }

  if (this.required && !this.value) {
      this.setRequired(false);
      setTimeout(() => this.setRequired(true));
  }
```

The lines the if conditions fail when the value === '' and therefore its not update when the last letter is cleared.
