### ISSUE TITLE
text-field: Prefilled form containing mdc-text-field is dirty

### ISSUE THREAD

**Issue by ngepin** [trimox/angular-mdc-web#941]
### What Angular MDC version are you using?
0.34.5

### What browser(s) is this bug affecting?
all

### What OS are you using?
windows 10

### What are the steps to reproduce the bug?
https://stackblitz.com/edit/angular-zfzevb

### What is the expected behavior?
Prefilled form should be pristine.

### What is the actual behavior?
Prefilled form dirty

**Comment by trimox** [comment]
@ngepin Thanks for reporting, and the helpful StackBlitz. I re-tested an upcoming pull request #940, and it'll resolve this issue as well.

Expect a release today, as I do final testing and cleanup.

**Comment by trimox** [comment]
Closing. Merged PR #940
