### ISSUE TITLE
Option text visible on top of placeholder text when options are loaded after mdc-select is initialised

### ISSUE THREAD

**Issue by NickMoores** [trimox/angular-mdc-web#963]
### What Angular MDC version are you using?
0.35.3

### What browser(s) is this bug affecting?
Chrome 66

### What OS are you using?
Windows 10

### What are the steps to reproduce the bug?
Add options to an mdc-select after it has been initialised. See here for a reproduction: https://stackblitz.com/edit/angular-mdc-select-orr8gk

### What is the expected behavior?
After 2.5 seconds, the new \<option\>s should be loaded into the mdc-select, but remain hidden.

### What is the actual behavior?
The first non-disabled option, "Steak", is visible on top of the placeholder text.

### Any other information you believe would be useful?
This might be a problem with material-web-components rather than @angular-mdc/web. As far as I can tell, the selectedIndex of the select control changes from -1 to 1 when the new <option> elements are loaded into the markup.

**Comment by trimox** [comment]
@NickMoores Thanks for the StackBlitz! 

Here's a simple workaround while I investigate.

Remove this line from html.
```html
<option disabled></option>
```

Add the `disabled:true` line into food array.
```ts
    setTimeout(() => this.foods = [
      { disabled: true },
      { value: 'steak-0', description: 'Steak' },
      { value: 'pizza-1', description: 'Pizza' },
      { value: 'tacos-2', description: 'Tacos is disabled', disabled: true },
      { value: 'fruit-3', description: 'Fruit' },
    ], 2500);
```

**Comment by trimox** [comment]
PR incoming.
