### ISSUE TITLE
Angular 6 is not compatible with  v0.35.3

### ISSUE THREAD

**Issue by edjeezy** [trimox/angular-mdc-web#982]
### What Angular MDC version are you using?
0.35.3

### What browser(s) is this bug affecting?
angular cli
### What OS are you using?
Mac OS High Sierra
### What are the steps to reproduce the bug?
node 8 and npm 5
Instal angular cli v6
ng new dummy
npm i @angular-mdc/web
### What is the expected behavior?
compiled successfully
### What is the actual behavior?
Failed to compile
### Any other information you believe would be useful?
using npm view @angular-mdc/web i saw that the peer dependency on npm registry is still on 5+... might help

**Comment by trimox** [comment]
@edjeezy Angular v6 compatible build is due today 😄

**Comment by trimox** [comment]
Later than expected today, but build is underway. Fixing #987 took a bit to get just right.
