### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by danieldaeschle** [trimox/angular-mdc-web#988]
Same error: https://github.com/angular/angular/issues/23994

**Comment by trimox** [comment]
Thanks for reporting. Working on it.

**Comment by sir-boformer** [comment]
I can confirm that it is not working in IE 11.

**Comment by trimox** [comment]
Thanks. Testing a fix, and planning an update in a bit.

**Comment by trimox** [comment]
Much better, new build underway 😄 

![image](https://user-images.githubusercontent.com/11887843/40261550-3cbac228-5acf-11e8-881e-2ae256965671.png)

**Comment by sir-boformer** [comment]
Awesome!

**Comment by trimox** [comment]
Go ahead and grab `v0.35.6`. I'm working on updating the demo page now.

**Comment by danieldaeschle** [comment]
Awesome, will test it soon.
