### ISSUE TITLE
mdc-select not displaying if placeholder text is not set

### ISSUE THREAD

**Issue by ngepin** [trimox/angular-mdc-web#996]
### What Angular MDC version are you using?
0.35.7

### What browser(s) is this bug affecting?
all

### What OS are you using?
windows 10

### What are the steps to reproduce the bug?
omit placeholder in mdc-select
https://stackblitz.com/edit/angular-w6ngia

### What is the expected behavior?
mdc-select should display selected option without label

### What is the actual behavior?
mdc-select not displaying

### Any other information you believe would be useful?
mdc-select without placeholder has 0 width

**Comment by trimox** [comment]
@ngepin Thanks for the StackBlitz and reporting! PR incoming.

**Comment by trimox** [comment]
@ngepin Forgot to mention, here's a quick workaround until next published version.

```html
<mdc-select [autosize]="false">
```
