### ISSUE TITLE
Items in a non-interactive list should probably not have their selected state affected by clicks.

### ISSUE THREAD

**Issue by ibelenski** [trimox/angular-mdc-web#999]
Version 0.35.6

Clicking an item in an non-interactive list alters its selected state. Maybe this is by design but it does make the list "somewhat" interactive. The workaround of handling the selectionChange event and clearing the selection can get a bit tedious.

```
<mdc-list [interactive]="false">
  <mdc-list-item>Some item</mdc-list-item>
  <mdc-list-item>Another item</mdc-list-item>
  <mdc-list-item>Yet another item</mdc-list-item>
</mdc-list>
```

![image](https://user-images.githubusercontent.com/8331406/40551603-75ec5200-600b-11e8-89d5-e1cd779a76a1.png)

![image](https://user-images.githubusercontent.com/8331406/40551637-892dfdf0-600b-11e8-9d86-1170d4ea3dc7.png)

**Comment by trimox** [comment]
@ibelenski Thanks for reporting on this. I'll investigate `material-components-web` specs and let ya know.

**Comment by ibelenski** [comment]
Thanks, @trimox. This is a fantastic library and I really appreciate your good work, even if I keep nitpicking at it.

**Comment by trimox** [comment]
@ibelenski Thanks! It's appreciated having extra eyes on things, no worries :smile:

**Comment by trimox** [comment]
Fixing to match material spec. PR incoming..

**Comment by trimox** [comment]
@ibelenski Delaying PR to v0.36.1 for more testing.

**Comment by trimox** [comment]
PR merged. Look for v0.36.3 publish tomorrow (06-16)
